### PR TITLE
Fix incorrect docblock for custom builder resolvers

### LINKED ISSUE #56152: blueprintResolver type mismatch
### Laravel Version

12.19.3

### PHP Version

8.4.8

### Database Driver & Version

_No response_

### Description

In Illuminate/Database/Schema/Builder.php there is type mismatch how `$resolver` is defined.
It seems like it is outdated, since we now call it like this:
```
return call_user_func($this->resolver, $connection, $table, $callback);
```

https://github.com/laravel/framework/blob/12.x/src/Illuminate/Database/Schema/Builder.php#L704

```
@param  \Closure(string, \Closure, string): \Illuminate\Database\Schema\Blueprint|null  $resolver
````

https://github.com/laravel/framework/blob/12.x/src/Illuminate/Database/Schema/Builder.php#L633

```
return call_user_func($this->resolver, $connection, $table, $callback);
```

### Steps To Reproduce

Call blueprintResolver() and validate with phpstan

### PR DESCRIPTION
**Pull request by LukeTowers**
Fixes #56152 which was caused by the incorrect parameters being used for a more specific type hint docblock merged in #55687. 

This currently causes issues with projects that use static analysis and make use of the $builder->blueprintResolver() method to resolve custom blueprints.

See https://github.com/LukeTowers/framework/blob/patch-1/src/Illuminate/Database/Schema/Builder.php#L621-L637 for the proof of the corrected typehints.

Example below:

```
 ------ ---------------------------------------------------------------------------------------------------------- 
  Line   Database/DatabaseServiceProvider.php                                                                      
 ------ ---------------------------------------------------------------------------------------------------------- 
  :109   Parameter #1 $connection of class Winter\Storm\Database\Schema\Blueprint constructor expects              
         Illuminate\Database\Connection, string given.                                                             
         🪪  argument.type                                                                                         
  :109   Parameter #2 $table of class Winter\Storm\Database\Schema\Blueprint constructor expects string, Closure   
         given.                                                                                                    
         🪪  argument.type                                                                                         
  :109   Parameter #3 $callback of class Winter\Storm\Database\Schema\Blueprint constructor expects Closure|null,  
         string given.                                                                                             
         🪪  argument.type                                                                                         
 ------ ----------------------------------------------------------------------------------------------------------
```

### CODE REVIEW

File: src/Illuminate/Database/Schema/Builder.php [hunk 1]
```diff
@@ -30,7 +30,8 @@ class Builder
     /**
      * The Blueprint resolver callback.
      *
-     * @var \Closure(string, \Closure, string): \Illuminate\Database\Schema\Blueprint|null
+     * @var \Closure(\Illuminate\Database\Connection, string, \Closure): \Illuminate\Database\Schema\Blueprint
+     *
```
Comment (LukeTowers) [inline src/Illuminate/Database/Schema/Builder.php]:
```suggestion
```

**Comment by LukeTowers** [comment]
@crynobone I've submitted a PR to fix #56152 as requested.

File: src/Illuminate/Database/Schema/Builder.php [hunk 2]
```diff
@@ -698,7 +698,7 @@ public function getConnection()
     /**
      * Set the Schema Blueprint resolver callback.
      *
-     * @param  \Closure(string, \Closure, string): \Illuminate\Database\Schema\Blueprint|null  $resolver
+     * @param  \Closure(\Illuminate\Database\Connection, string, \Closure): \Illuminate\Database\Schema\Blueprint  $resolver
```
Comment (LukeTowers) [inline src/Illuminate/Database/Schema/Builder.php]:
```suggestion
     * @param  \Closure(\Illuminate\Database\Connection, string, \Closure|null): \Illuminate\Database\Schema\Blueprint  $resolver
```

File: src/Illuminate/Database/Schema/Builder.php [hunk 3]
```diff
@@ -30,7 +30,7 @@ class Builder
     /**
      * The Blueprint resolver callback.
      *
-     * @var \Closure(string, \Closure, string): \Illuminate\Database\Schema\Blueprint|null
+     * @var \Closure(\Illuminate\Database\Connection, string, \Closure): \Illuminate\Database\Schema\Blueprint
```
Comment (LukeTowers) [inline src/Illuminate/Database/Schema/Builder.php]:
```suggestion
     * @var \Closure(\Illuminate\Database\Connection, string, \Closure|null): \Illuminate\Database\Schema\Blueprint
```
