### PR TITLE
[10.x] Disconnecting the database connection after testing

### LINKED ISSUE #49311: Some traits of database tests do not close the connection even after the test is finished
### Laravel Version

10.35.0

### PHP Version

8.3.0

### Database Driver & Version

PostgreSQL 16.1 for MacOS(MacPorts) / Probably all databases

### Description

`DatabaseMigrations` and `DatabaseTruncation` do not close the database connection at the end of each test. Therefore, the database connection remains open for the number of tests.

As a result, when running a large number of tests, we may encounter a maximum number of connections error or a lack of resources on the database side.

`DatabaseTransactions` and `RefreshDatabase` do not have this problem.

### Steps To Reproduce

In the following example, I adjusted the PostgreSQL config to make it easier to see what happens. It probably happens with other databases as well.

1. Start the server with postgresql.conf set as follows.
   ```ini
   max_connections = 3 # intentionally small value
   log_connections = on
   log_disconnections = on
   ```

2. Run the following test:
   ```php
   use DatabaseTruncation; // or `DatabaseMigrations`
   
   public static function repeat(): array
   {
        // Run the test more times than the maximum number of concurrent connections
        return array_fill(0, 4, []);
   }
   
   /** @dataProvider repeat */
   public function test(): void
   {
   }
   ```

3. The test will fail with the following error for example:
   ```
   SQLSTATE[08006] [7] connection to server on socket "/tmp/.s.PGSQL.5432" failed: FATAL: sorry, too many clients already (Connection: pgsql, SQL: SET CONSTRAINTS ALL DEFERRED;)
   ```

3. The following is recorded in the database server log:
   ```
   LOG: connection received: host=[local]
   LOG: connection authorized: user=postgres database=postgres
   LOG: connection received: host=[local]
   LOG: connection authorized: user=postgres database=postgres
   LOG: connection received: host=[local]
   LOG: connection authorized: user=postgres database=postgres
   LOG: connection received: host=[local]
   FATAL: sorry, too many clients already
   LOG: connection received: host=[local]
   FATAL: sorry, too many clients already
   LOG: disconnection: session time: 0:00:00.012 user=postgres database=postgres host=[local]
   LOG: disconnection: session time: 0:00:00.024 user=postgres database=postgres host=[local]
   LOG: disconnection: session time: 0:00:00.058 user=postgres database=postgres host=[local]
   ```

* In the case of `DatabaseTransactions` and `RefreshDatabase`, the connection is closed after each test as per their implementation, so no error occurs and the log is recorded as follows.
   ```
   LOG: connection received: host=[local]
   LOG: connection authorized: user=postgres database=postgres
   LOG: disconnection: session time: 0:00:00.034 user=postgres database=postgres host=[local]
   LOG: connection received: host=[local]
   LOG: connection authorized: user=postgres database=postgres
   LOG: disconnection: session time: 0:00:00.030 user=postgres database=postgres host=[local]
   LOG: connection received: host=[local]
   LOG: connection authorized: user=postgres database=postgres
   LOG: disconnection: session time: 0:00:00.030 user=postgres database=postgres host=[local]
   LOG: connection received: host=[local]
   LOG: connection authorized: user=postgres database=postgres
   LOG: disconnection: session time: 0:00:00.029 user=postgres database=postgres host=[local]
   LOG: connection received: host=[local]
   LOG: connection authorized: user=postgres database=postgres
   LOG: disconnection: session time: 0:00:00.031 user=postgres database=postgres host=[local]
   ```

### PR DESCRIPTION
**Pull request by KentarouTakeda**
fixes #49311

~~I only fixed the case using `DatabaseMigrations` and `DatabaseTruncation`.~~

~~Cases that do not use traits have not been fixed. I thought it was too broad to fix this as it would affect all tests not related to the database.~~

~~(However, this approach also covers the case mentioned by @crynobone where the user is interacting with the database in `beforeApplicationDestroyed`, so I think it might be worth considering in the next major version.)~~

This pull request prevents connections from being flooded in all situations, even when no traits are used.

/cc @crynobone @driesvints @mpyw

---

*update: 2023-12-12 10:28 JST*

I found that tests using `orchestral/testbench` do not work properly if disconnected during `DatabaseMigrations` or `DatabaseTruncation`.

Therefore, instead of the method originally proposed, I changed the way to disconnect in the `tearDown` process rather than in a separate trait. If the connection does not exist, nothing happens, so the existing behavior remains unchanged.

### CODE REVIEW

**Comment by KentarouTakeda** [comment]
Sorry, I failed the test, so I'll look into it later.

**Comment by KentarouTakeda** [comment]
Fixed to pass CI. I changed the way I fix it in the process.

Ready for review.

**Review by mpyw — COMMENTED** [review]
LGTM, thanks a lot

File: src/Illuminate/Foundation/Testing/TestCase.php [hunk 1]
```diff
@@ -197,6 +197,11 @@ protected function tearDown(): void
 
             ParallelTesting::callTearDownTestCaseCallbacks($this);
 
+            $database = $this->app['db'];
```
Comment (crynobone) [inline src/Illuminate/Foundation/Testing/TestCase.php:200]: It is possible to run an application without `db`

File: src/Illuminate/Foundation/Testing/TestCase.php [hunk 2]
```diff
@@ -197,6 +197,11 @@ protected function tearDown(): void
...
+            foreach (array_keys($database->getConnections()) as $name) {
+                $database->purge($name);
+            }
```
Comment (mpyw) [inline src/Illuminate/Foundation/Testing/TestCase.php:203]: Would be better?

```suggestion
            if ($database = $this->app['db'] ?? null) {
                foreach (array_keys($database->getConnections()) as $name) {
                    $database->purge($name);
                }
            }
```

File: src/Illuminate/Foundation/Testing/TestCase.php (hunk 1 above)
Comment (KentarouTakeda) [reply src/Illuminate/Foundation/Testing/TestCase.php]: Ah.. Exactly!
Fixed in https://github.com/laravel/framework/pull/49327/commits/8dc1054f3e907b019ef26b1ee288d1d40d94ae96.

File: src/Illuminate/Foundation/Testing/TestCase.php (hunk 2 above)
Comment (KentarouTakeda) [reply src/Illuminate/Foundation/Testing/TestCase.php]: Oops, without realizing this, I fixed it in a different way.
Thank you!

File: src/Illuminate/Foundation/Testing/RefreshDatabase.php [hunk 3]
```diff
@@ -109,7 +109,6 @@ public function beginDatabaseTransaction()
                 $connection->unsetEventDispatcher();
                 $connection->rollBack();
                 $connection->setEventDispatcher($dispatcher);
-                $connection->disconnect();
```
Comment (crynobone) [inline src/Illuminate/Foundation/Testing/RefreshDatabase.php:112]: Shouldn't it just been `$database->purge($name);`?

File: src/Illuminate/Foundation/Testing/DatabaseTransactions.php [hunk 4]
```diff
@@ -33,7 +33,6 @@ public function beginDatabaseTransaction()
                 $connection->unsetEventDispatcher();
                 $connection->rollBack();
                 $connection->setEventDispatcher($dispatcher);
-                $connection->disconnect();
```
[the remark this answers is not in the document]
Comment (KentarouTakeda) [reply src/Illuminate/Foundation/Testing/DatabaseTransactions.php:36]: Fixed in https://github.com/laravel/framework/pull/49327/commits/71d57c294d408fce140e091ca1c71b39f3bb95b8

Immediately after this part is processed by `callBeforeApplicationDestroyedCallbacks`, the newly added processing will also be performed. The intention was to eliminate waste, but since there is no harm in having it, the way you mentioned may have been better in the sense that it does not change the existing behavior. Thanks!

File: src/Illuminate/Foundation/Testing/RefreshDatabase.php (hunk 3 above)
Comment (KentarouTakeda) [reply src/Illuminate/Foundation/Testing/RefreshDatabase.php:112]: Fixed in https://github.com/laravel/framework/pull/49327/commits/71d57c294d408fce140e091ca1c71b39f3bb95b8

**Comment by KentarouTakeda** [comment]
Thanks!

**Comment by driesvints** [comment]
@KentarouTakeda this seems like a breaking change unfortunately. You could maybe re-attempt 11.x/master: https://github.com/laravel/framework/issues/49359
