### PR TITLE
Fix breaking change - Revert "[11.x] Replace string class names with ::class constants"

### LINKED ISSUE #54184: new release v11.38.0 breaks redirect routes
### Laravel Version

11.38.0

### PHP Version

8.3.x

### Database Driver & Version

_No response_

### Description

Redirect-routes are broken. It throws the 'Invalid route action:' error since the class resolves to an unknown class.

This PR seems to break it: https://github.com/laravel/framework/pull/54134

Image

Image

### Steps To Reproduce

Make a redirect in your routes..

### PR DESCRIPTION
**Pull request by SanderMuller**
Reverts laravel/framework#54134

fixed #54184

@taylorotwell I think this is a breaking change on the old route namespacing eg
```
Route::namespace('Admin')

    ->group(function (): void {

        Route::view('dashboard', 'admin.dashboard');

    });
```

this now throws `Invalid route action: [App\Http\Controllers\Admin\Illuminate\Routing\ViewController].` because the namespace in this PR was changed from `\Illuminate\Routing\ViewController` to `Illuminate\Routing\ViewController` I think.

image

### CODE REVIEW

**Review by GrahamCampbell — APPROVED** [review]

**Comment by SanderMuller** [comment]
The same test change has been added in #54186 which shows that the added test fails on the `11.x` branch but not in this revert PR with regression test

File: src/Illuminate/Foundation/Console/RouteListCommand.php [hunk 1]
```diff
@@ -250,8 +250,8 @@ protected function isVendorRoute(Route $route)
     protected function isFrameworkController(Route $route)
     {
         return in_array($route->getControllerClass(), [
-            \Illuminate\Routing\RedirectController::class,
-            \Illuminate\Routing\ViewController::class,
+            '\Illuminate\Routing\RedirectController',
+            '\Illuminate\Routing\ViewController',
```
Comment (shaedrich) [inline src/Illuminate/Foundation/Console/RouteListCommand.php:254]:
```suggestion
            '\' . Illuminate\Routing\RedirectController::class,
            '\' . Illuminate\Routing\ViewController::class,
```
probably isn't much better, is it?
