### PR TITLE
[12.x] Fix text truncation on syntax-highlighted queries

### LINKED ISSUE #57246: New lines in querys in exception page breaks frontend and built-in syntax on the page
### Laravel Version

12.32.5

### PHP Version

8.4.13

### Database Driver & Version

12.0.2-MariaDB-ubu2404 (Docker)

### Description

Hi,

There is a frontend issue, where in the layout and syntax highlighter breaks on the query component, this also causes text to overlay on other components on the page.

The problem happens here:
https://github.com/laravel/framework/blob/e821bfd3fc4013c11b3558fe6b33c8e6e26c7097/src/Illuminate/Foundation/resources/exceptions/renderer/components/query.blade.php#L113

It shows like this:
Image

### Steps To Reproduce

Make sure to create a model you can create a item to the database. in this example i've used the model `Audit`. 

Make the changes to `bootstrap/app.php` look like this:
```PHP
<?php

use Illuminate\Foundation\Application;
use Illuminate\Foundation\Configuration\Exceptions;
use Illuminate\Foundation\Configuration\Middleware;

return Application::configure(basePath: dirname(__DIR__))
    ->withRouting(
        web: __DIR__.'/../routes/web.php',
        commands: __DIR__.'/../routes/console.php',
        health: '/up',
    )
    ->withMiddleware(function (Middleware $middleware) {
        //
    })
    ->withExceptions(function (Exceptions $exceptions) {
        \App\Models\Audit::create([
            'log' => "A long text \n Look i'm on a new line! \n Another new line! \n Wheeee! \n We also break syntax! select from\n a new line! \n a new line! \n a new line! \n a new line!\n a new line! \n a new line! \n a new line! \n a new line\n a new line! \n a new line! \n a new line! \n a new line\n a new line! \n a new line! \n a new line! \n a new line!!!"
        ]);
    })->create();
```

### PR DESCRIPTION
**Pull request by avosalmon**
Fixes https://github.com/laravel/framework/issues/57246.

On the local exception page, syntax-highlighted queries are not properly truncated and overflow the row when the query contains newlines.

## Before

CleanShot 2025-10-09 at 14 59 29

## After

CleanShot 2025-10-09 at 14 58 41

### CODE REVIEW

File: src/Illuminate/Foundation/resources/exceptions/renderer/scripts.js [hunk 1]
```diff
@@ -63,9 +63,6 @@ window.highlight = function (
                 pre(node) {
                     this.addClassToHast(node, ['bg-transparent!', truncate ? 'truncate' : 'w-fit min-w-full']);
                 },
-                code(node) {
-                    this.addClassToHast(node, 'flex flex-col');
-                },
```
Comment (avosalmon) [inline src/Illuminate/Foundation/resources/exceptions/renderer/scripts.js:68]: This breaks text truncation.

File: .github/workflows/update-assets.yml [hunk 2]
```diff
@@ -3,10 +3,15 @@ name: 'update assets'
...
+      - '*.x'
     paths:
-      - '/src/Illuminate/Foundation/resources/exceptions/renderer/package-lock.json'
-  workflow_dispatch:
+      - 'src/Illuminate/Foundation/resources/exceptions/renderer/**'
+      - '!src/Illuminate/Foundation/resources/exceptions/renderer/dist/**'
+  pull_request:
+    paths:
+      - 'src/Illuminate/Foundation/resources/exceptions/renderer/**'
+      - '!src/Illuminate/Foundation/resources/exceptions/renderer/dist/**'
```
Comment (avosalmon) [inline .github/workflows/update-assets.yml:14]: Automatically builds assets on PR.
