### PR TITLE
[5.8] Note that the GD extension is required for generating images

### LINKED ISSUE #29769: [5.8] Possible undocumented dependency
When I run Laravel's test suite on one of my machines, I run into the following issue:

```
1) Illuminate\Tests\Http\HttpTestingFileFactoryTest::testImageJpeg
Error: Call to undefined function Illuminate\Http\Testing\imagejpeg()

/data/src/Illuminate/Http/Testing/FileFactory.php:55
/data/src/Illuminate/Support/helpers.php:1124
/data/src/Illuminate/Http/Testing/FileFactory.php:63
/data/src/Illuminate/Http/Testing/FileFactory.php:34
/data/tests/Http/HttpTestingFileFactoryTest.php:23
```

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Closes #29769. // cc @fiskolini

### CODE REVIEW

**Review by fiskolini — APPROVED** [review]

File: tests/Http/HttpTestingFileFactoryTest.php [hunk 1]
```diff
@@ -9,6 +9,10 @@ class HttpTestingFileFactoryTest extends TestCase
 {
     public function testImagePng()
     {
+        if (! function_exists('imagejpeg')) {
```
Comment (fiskolini) [inline tests/Http/HttpTestingFileFactoryTest.php]: Should test against `imagepng`
`if (! function_exists('imagepng')) {......`

Comment (GrahamCampbell) [reply tests/Http/HttpTestingFileFactoryTest.php]: Yeh. You're right. I'll update.
