### PR TITLE
[10.x] Fix "after commit" callbacks not running on nested transactions using `RefreshDatabase` or `DatabaseMigrations`

### LINKED ISSUE #48451: `RefreshDatabase` + double wrapping in `DB::transaction()` breaks `$afterCommit` functionality
### Laravel Version

10.23.1

### PHP Version

8.2.10

### Database Driver & Version

8.0.33

### Description

In tests, model observer `created` does not run if all condition applies:
1. Test uses mysql DB connection.
2. Test uses `RefreshDatabase` trait.
3. Using `createOrFirst()` or `firstOrCreate()` method and the method is inside `DB::transaction()`.

This issue started to appear in laravel/framework 10.21. I think it was introduced in https://github.com/laravel/framework/pull/48144

cc: @tonysm / @mpyw 

### Steps To Reproduce

1. Clone [TestDBTransaction](https://github.com/ryanldy/TestDBTransaction) sample project.
2. Make sure to update mysql database connection in your .env file.
3. Run `vendor/bin/phpunit`. Test should pass but it fails.
4. Try to comment the lines under Failing Test (line 27 and 30) section and uncomment a line from the Passing Tests (line 35 or 38) in `NoteObserverTest`. Test now passes.

### PR DESCRIPTION
**Pull request by crynobone**
Separate `db.transactions` instance between normal requests and tests. PR based from #48466 and fixes https://github.com/laravel/framework/issues/48451

### CODE REVIEW

File: src/Illuminate/Database/DatabaseTransactionsManager.php [hunk 1]
```diff
@@ -112,13 +112,22 @@ public function callbacksShouldIgnore(DatabaseTransactionRecord $transaction)
...
      *
-     * @return \Illuminate\Support\Collection
+     * @return \Illuminate\Support\Collection<int, \Illuminate\Database\DatabaseTransactionRecord>
      */
     public function callbackApplicableTransactions()
     {
-        return $this->transactions->reject(function ($transaction) {
-            return $transaction === $this->callbacksShouldIgnore;
-        })->values();
+        return $this->transactions->values();
```
Comment (crynobone) [inline src/Illuminate/Database/DatabaseTransactionsManager.php:119]: We can simplify this to just 
```suggestion
        return $this->transactions;
```

File: src/Illuminate/Database/Concerns/ManagesTransactions.php [hunk 2]
```diff
@@ -194,12 +194,12 @@ public function commit()
             $this->getPdo()->commit();
         }
 
-        $this->transactions = max(0, $this->transactions - 1);
-
         if ($this->afterCommitCallbacksShouldBeExecuted()) {
             $this->transactionsManager?->commit($this->getName());
         }
 
+        $this->transactions = max(0, $this->transactions - 1);
```
Comment (crynobone) [inline src/Illuminate/Database/Concerns/ManagesTransactions.php:201]: Reset `$this->transactions` after calling `afterCommitCallbacksShouldBeExecuted()` so we can get the true transaction levels during the commit.

**Comment by mpyw** [comment]
Great work!!!!!!!!

File: src/Illuminate/Database/DatabaseTransactionsManager.php (hunk 1 above)
Comment (tonysm) [reply src/Illuminate/Database/DatabaseTransactionsManager.php:119]: I thought about that, but it would return the same collection instance. I figured it would be better to clone it or create a new one instead.

**Comment by tonysm** [comment]
@crynobone Nice work! I think it will still be needed, even after #48531, because it's more about nested transactions on tests, which was only surfaced by the `createOrFirst` method... so I think it's still worth it.

**Comment by crynobone** [comment]
Verified this changes still solve transaction + after commit issue using RefreshDatabase.

File: src/Illuminate/Foundation/Testing/DatabaseTransactionsManager.php [hunk 3]
```diff
@@ -0,0 +1,47 @@
...
+    /**
+     * Get the transactions that are applicable to callbacks.
+     *
+     * @return \Illuminate\Support\Collection<int, \Illuminate\Database\DatabaseTransactionRecord>
+     */
+    public function callbackApplicableTransactions()
+    {
+        return $this->transactions->reject(
+            fn ($transaction) => $transaction === $this->transactions->first()
+        )->values();
```
Comment (tonysm) [inline src/Illuminate/Foundation/Testing/DatabaseTransactionsManager.php:34]: Could be re-written like this, right?!

```suggestion
        return $this->transactions->skip(1)->values();
```

**Comment by taylorotwell** [comment]
Thanks!

**Comment by azgooon** [comment]
Hey, the project I am working on uses heavily nested transactions and they used to work flawlesly however I've updated laravel framework and now I keep getting errors:
`PDOException: SQLSTATE[25P01]: No active sql transaction: 7 ERROR: SAVEPOINT can only be used in transaction blocks in /var/www/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php:159`
I decided to check recent commits in laravel project and came accross this one, I suspect that this change could be responsible for this error.

**Comment by mpyw** [comment]
Hi @azgooon

Are you consistently using `DB::transaction()` instead of independent `DB::beginTransaction()` `DB::commit()`?

**Comment by crynobone** [comment]
This PR only change behaviour while running tests and doesn't affect your application code. Submit new bug report with reproducing code.

**Comment by azgooon** [comment]
Hi @mpyw yes, DB::transaction() is the approach we use.

**Comment by tonysm** [comment]
@azgooon Which database are you using and can you share a test where this issue appears (if you can reduce it down to a simple test, that would be great)? As @crynobone mentioned, the changes here should only affect tests, so I assume your _tests_ failed, right? Pls share more context on the tests, which traits you're using and things like that. Thanks!

**Comment by azgooon** [comment]
@tonysm I will happily provide as much details as I can. To start from I am not refering to the test as we don't have any. I was refering to the actual functionality of the project which partially stopped working in places where DB::transaction calls methods which are also performing DB::transaction(); Please bear with me a while, I will do my best to extract a piece of code which does not work anymore, We use PostgreSQL.

**Comment by crynobone** [comment]
Not related to this PR, please compile new bug report with reproducing code and continue there.
