### PR TITLE
[10.x] Add POSIX compliant cleanup to artisan serve

### LINKED ISSUE #49941: Artisan serve doesn't kill it's subprocess if killed with a signal instead of Ctrl + C
### Laravel Version

10.4.1

### PHP Version

8.3

### Database Driver & Version

_No response_

### Description

When running `php artisan serve` it creates a subprocess for the server, but it seems to simply forward all it's input to the subprocess which is only listening for Ctrl + C on the keyboard to close, this is is not POSIX compliant

As such when we kill the `php artisan serve` command it doesn't do any cleanup itself and the subprocess keeps running

### Steps To Reproduce

1. Run `php artisan serve`
2. Open a second terminal
3. Run `ps aux` and get the pid of `php artisan serve`
image
4. Run `kill -SIGTINT $the_pid` which should be equivalent to a Ctrl + C signal
5. Check `ps aux` and notice that the main process is gone but the subprocess is still there
image

This is a big problem when spawning `php artisan serve` from within another program, because programs should only use signals to kill their offsprings

### PR DESCRIPTION
**Pull request by Tofandel**
Fixes #49941

### Description

When running `php artisan serve` it creates a subprocess for the server, but it seems to simply forward all it's input to the subprocess which is only listening for Ctrl + C on the keyboard to close itself which in turn exits the parent, this is is not POSIX compliant

As such when we kill the `php artisan serve` command it doesn't do any cleanup itself and the subprocess keeps running

### Steps To Reproduce

1. Run `php artisan serve`
2. Open a second terminal
3. Run `ps aux` and get the pid of `php artisan serve`
image
4. Run `kill -SIGTINT $the_pid` which should be equivalent to a Ctrl + C signal
5. Check `ps aux` and notice that the main process is gone but the subprocess is still there
image

This is a big problem when spawning `php artisan serve` from within another program, because programs should only use signals to kill their offsprings

With this PR if pcntl is enabled (it's optional but recommended in composer) any termination signal will trigger the cleanup of the subprocess

### CODE REVIEW

**Comment by driesvints** [comment]
@Tofandel could you please add a full description to your PR and not just link to an issue? (See the template when you open PR's). Thanks!

**Comment by rojtjo** [comment]
You might be able to use the built in signal abstractions: https://laravel.com/docs/10.x/artisan#signal-handling

**Comment by Tofandel** [comment]
@rojtjo Indeed it's much better, didn't know about it

File: src/Illuminate/Foundation/Console/ServeCommand.php [hunk 1]
```diff
@@ -140,6 +140,18 @@ protected function startProcess($hasEnvironment)
...
+                if ($process->isRunning()) {
+                    $process->stop(10, $signo);
+                }
+                exit;
+            };
+            pcntl_signal(SIGINT, $cleanup);
+            pcntl_signal(SIGTERM, $cleanup);
+            pcntl_signal(SIGHUP, $cleanup);
+        }
+
```
Comment (Tofandel) [inline src/Illuminate/Foundation/Console/ServeCommand.php:154]:
```suggestion
        $this->trap([SIGTERM, SIGINT, SIGHUP, SIGUSR1, SIGUSR2, SIGQUIT], function ($signo) use ($process) {
            if ($process->isRunning()) {
                $process->stop(10, $signo);
            }
            exit;
        });

```

**Review by Tofandel — COMMENTED** [review]
Use built in signal abstraction

**Comment by driesvints** [comment]
Heya. We got a report that this doesn't works on Windows: https://github.com/laravel/framework/issues/50022 so just skipping that there for now: https://github.com/laravel/framework/pull/50023

**Comment by Tofandel** [comment]
It would be the case if pcntl wasn't activated in any env I think

I got a false sense of security using the wrapper, that it would only run with pcntl enabled, but I forgot that the constants would be evaluated even if the callback doesn't run
https://github.com/laravel/framework/blob/1d0f002172d1570389e72fb474d16a6996fc943d/src/Illuminate/Console/Concerns/InteractsWithSignals.php#L26

A quick fix would be to wrap the `->trap` in `Signals::whenAvailable(fn () => $this->trap())`

A future improvement for `trap` then might be to provide the signals in a callback as well
