### PR TITLE
[5.8] Fix ambiguous UPDATED_AT columns

### LINKED ISSUE #13909: updated_at not fully qualified, creates ambiguous column errors
When attempting to use delete() or update() on an eloquent model you can not use any joins because you will get an ambiguous column name error on updated_at.  This is because the Eloquent/Builder.php does not prefix updated_at with the proper table name.  I attempted to do a pull request for this, but the issue is further complicated by Arr::add (used in addUpdatedAtColumn) doing automatic dot notation exploding.  This prevents me from adding a table.columnName string similar to the operation of SoftDeletes trait.

Laravel 5.2

### PR DESCRIPTION
**Pull request by staudenmeir**
#13519 attempted to fix ambiguous `UPDATED_AT` columns in `JOIN` queries:

```php
class Country extends Model {
    public function posts() {
        return $this->hasManyThrough(Post::class, User::class);
    }
}

$country->posts()->update(['foo' => 'bar']);
```

```sql
update `posts` inner join `users` on `users`.`id` = `posts`.`user_id`
set `foo` = bar, `updated_at` = 2018-10-10 01:56:14
where `users`.`country_id` = 1
```

If both tables have an `updated_at` column, you get an "ambiguous column name" error (on MySQL).

To fix this, the previous PR qualified the column with the table name. This didn't work because PostgreSQL and SQLite don't allow qualified columns in `UPDATE` queries (#13707).

#22366 updated the `SQLiteGrammar` to remove the table name from qualified columns when an `UPDATE` query is compiled. This PR applies the same behavior to the `PostgresGrammar`.

We can now safely qualify the column on all platforms. We have to replace `Arr::add()` with `array_merge()` because the former interprets a qualified column as a nested key. `$values` is the second argument so that the users can override the `updated_at` value (as they can now).

Fixes #13909.

### CODE REVIEW

File: tests/Database/DatabaseEloquentBuilderTest.php [hunk 1]
```diff
@@ -1049,6 +1050,26 @@ public function testOldestWithColumn()
         $builder->oldest('foo');
     }
 
+    public function testUpdate()
+    {
+        Carbon::setTestNow(
```
Comment (mfn) [inline tests/Database/DatabaseEloquentBuilderTest.php]: You can just write `Carbon::setTestNow($now = '2017-10-10 10:10:10');` it uses `::parse` internally here.

**Comment by samrap** [comment]
Great work! 😁

**Comment by jimmypuckett** [comment]
@driesvints Is there anyway to get this merged into 5.7? I understand that because 5.5 is LTS it gets fixed, but it would be nice to let the current stable version get the fix too?

**Comment by mfn** [comment]
I'm afraid it's not possible, as the change to `compileUpdateColumns` would be a breaking change in the middle of a release cycle.

**Comment by jimmypuckett** [comment]
> I'm afraid it's not possible, as the change to `compileUpdateColumns` would be a breaking change in the middle of a release cycle.

@mfn Thanks for the feedback. It is interesting that 5.5 was able to be patched without breaking it, but that the current stable 5.7 cannot be patched.

I appreciate you taking the time to answer.

**Comment by staudenmeir** [comment]
@jimmypuckett Are you referring to #26022? We had to revert it in #26024.
