### PR TITLE
[10.x] 'hashed' cast - do not rehash already hashed value

### LINKED ISSUE #47028: Newly added 'hashed' cast may be incorrect.
### Laravel Version

10.10.0

### PHP Version

8.2

### Database Driver & Version

_No response_

### Description

Newly added `hashed` cast may have been implemented incorrectly.
https://github.com/laravel/framework/pull/46947

As I understand it, Hash::needsRehash() is supposed to take a hashed string as an argument.
https://laravel.com/docs/10.x/hashing
https://www.php.net/manual/en/function.password-needs-rehash

And an already hashed string will be double-hashed if it needs rehashing.

### Steps To Reproduce
```php
$user->password = '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi';
$user->save();
```

### PR DESCRIPTION
**Pull request by gdebrauwer**
Fixes https://github.com/laravel/framework/issues/47028

### CODE REVIEW

File: src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php [hunk 1]
```diff
@@ -1310,7 +1310,7 @@ public static function encryptUsing($encrypter)
      */
     protected function castAttributeAsHashedString($key, $value)
     {
-        return Hash::needsRehash($value) ? Hash::make($value) : $value;
+        return $value !== null && password_get_info($value)['algo'] === null ? Hash::make($value) : $value;
```
Comment (nunomaduro) [inline src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:1313]: If we hard-code the password_get_info function here, aren't we limiting ourselves to a specific hashing implementation? In my opinion, it is the responsibility of the hashing driver to inform us whether the provided string value has been hashed or not.

However, let's see what @taylorotwell thinks.

Comment (gdebrauwer) [reply src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:1313]: the `password_get_info` returns an `algo` value from one of the hashing constants in PHP https://www.php.net/manual/en/password.constants.php
