### PR TITLE
[8.x] phpredis lock serialization and compression support

### LINKED ISSUE #1939: Not reproducible compression results with LZ4
I just tested the LZ4 and ZSTD compression options against the REDLOCK algorithm with the laravel cache lock library and it seems like I have the same problem as in #1477. ZSTD worked out of the box with different compression levels.

For LZ4 I am not able to get the same result by calling `lz4_compress($string, $compressionLevel)` with any compression level. Most of the time the difference is the first byte, which seems to be off.

With compression level 0 (default lz4), I get the following result:

```
1614439016.383115 [0 10.150.2.1:56450] "SET" "laravel_database_laravel_cache:foo" "\xef\x10\x00\x00\x00\xf0\x011r2fM79GOE1goTTj" "EX" "10" "NX"
1614439016.383433 [0 10.150.2.1:56450] "EVAL" "if redis.call(\"get\",KEYS[1]) == ARGV[1] then\n    return redis.call(\"del\",KEYS[1])\nelse\n    return 0\nend" "1" "laravel_database_laravel_cache:foo" "\x10\x00\x00\x00\xf0\x011r2fM79GOE1goTTj"
1614439016.383451 [0 lua] "get" "laravel_database_laravel_cache:foo"
```

As you can see the first SET and the EVAL ARGV[1] should be the same, they are but just the first view bytes are different. For the redlock algorithm the user needs to serialize/compress the arguments himself for the EVAL to work, because phpredis is not doing that for the user. For LZF, ZSTD it works fine. As a result the key is never deleted and thus the lock never released until it times out.

### Expected behaviour

```
1614439016.383115 [0 10.150.2.1:56450] "SET" "laravel_database_laravel_cache:foo" "\xef\x10\x00\x00\x00\xf0\x011r2fM79GOE1goTTj" "EX" "10" "NX"
```

and

```
1614439016.383433 [0 10.150.2.1:56450] "EVAL" "if redis.call(\"get\",KEYS[1]) == ARGV[1] then\n    return redis.call(\"del\",KEYS[1])\nelse\n    return 0\nend" "1" "laravel_database_laravel_cache:foo" "\x10\x00\x00\x00\xf0\x011r2fM79GOE1goTTj"
```

should have the same value.

### Actual behaviour

phpredis compresses the string differently than the php extension lz4 by calling `lz4_compress`. (https://github.com/kjdev/php-ext-lz4).

### I'm seeing this behaviour on
- OS: Ubuntu 20.04
- Redis: 5.0.9
- PHP: 8.0.2
- phpredis: 5.3.3

### Steps to reproduce, backtrace or example script

This is the EVAL script that is running to remove the locked key. See #1477 for examples.

```
if redis.call("get",KEYS[1]) == ARGV[1] then
    return redis.call("del",KEYS[1])
else
    return 0
end
``

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

### PR DESCRIPTION
**Pull request by TheLevti**
laravel/framework#36337: Respect serialization and compression settings of the phpredis extension when using it for locking via the cache service.

- Support phpredis serialization when locking (none, php, json, igbinary, msgpack).
- Support phpredis compression when locking (none, lzf, zstd, lz4).

This is a bug that will cause locking to not release the lock if the redis connection is configured to use serialization and/or compression of data. LZ4 code support was added, but is not working yet as phpredis implemented it not consistent to the lz4 php extension. Waiting for this issue on phpredis to be resolved: https://github.com/phpredis/phpredis/issues/1939. All other compression options resolve this bug.

Also once the phpredis issue https://github.com/phpredis/phpredis/issues/1938 is resolved, we might have a consistent way to call the same compression logic that the extension is using without the need to check for each implementation.

Tested locally with all extensions enabled/configured (lzf, zstd, lz4, igbinary, msgpack).

Solves #36337

### CODE REVIEW

**Comment by it-can** [comment]
Would also be nice to have laravel also support compression and serializer function… like this https://github.com/laravel/framework/pull/31262

**Comment by TheLevti** [comment]
> Would also be nice to have laravel also support compression and serializer functions for phpredis… like this #31262

I know, but before we can add those options to the laravel redis config, we should properly support the locking mechanism. So this pull request should be a prerequisite for the options to be added.

File: src/Illuminate/Cache/RedisLock.php [hunk 1]
```diff
@@ -48,7 +50,42 @@ public function acquire()
...
+                } else {
+                    throw new UnexpectedValueException(sprintf(
+                        'Unknown phpredis compression in use (%d). Unable to release lock.',
+                        $this->redis->client()->getOption(constant('Redis::OPT_COMPRESSION'))
+                    ));
+                }
+            }
+        }
+
+        return (bool) $this->redis->eval(LuaScripts::releaseLock(), 1, $this->name, $owner);
```
Comment (derekmd) [inline src/Illuminate/Cache/RedisLock.php:88]: This `release()` method can be kept simple by moving the "phpredis" extension-specific code into another method:

```php
public function release()
{
    return (bool) $this->redis->eval(LuaScripts::releaseLock(), 1, $this->name, $this->phpRedisOwner() ?? $owner);
}

protected function phpRedisOwner()
{
    if (! $this->isPhpRedisCompressionEnabled()) {
        return;
    }

    $owner = $this->redis->client()->_serialize($this->owner);

    // etc.
}
```

Here's a Gist with an updated `RedisLock.php` class: https://gist.github.com/derekmd/039d1b7b83326fc69790552fb30c9cc8 Then a 220 line class is shortened to 181 lines.

Another option is to move these additions into a completely new class with a constructor that accepts dependencies `$this->owner` and `$this->redis->client()`.

File: src/Illuminate/Cache/RedisLock.php [hunk 2]
```diff
@@ -80,4 +117,104 @@ public function getConnectionName()
...
+    private function isPhpRedis()
+    {
+        $client = $this->redis->client();
+        $clientClass = get_class($client);
+        if ($clientClass === 'Redis' || $clientClass === 'RedisCluster') {
+            return true;
+        }
+
+        return false;
+    }
```
Comment (derekmd) [inline src/Illuminate/Cache/RedisLock.php:219]: Can the calls to `constant()` be avoided since you don't need to worry about classes `\Redis` and `\RedisCluster` not existing? Updating `isPhpRedis()` to use `instanceof`:

```php
use Redis;
use RedisCluster;

// ...

protected function isPhpRedis()
{
    $client = $this->redis->client();

    return $client instanceof Redis || $client instanceof RedisCluster;
}
```

This short-circuits the other `is*()` methods from being called. The `instanceof` keyword can accept any symbol, even for classes that don't exist. e.g., `$client instanceof ThisClassDoesNotExist` won't throw an exception - it just returns `false`.

Then the other predicate methods can be simplified to a single expression. e.g.,

```php
protected function isPhpRedisLz4Enabled()
{
    return defined('Redis::COMPRESSION_LZ4') &&
        $this->redis->client()->getOption(Redis::OPT_COMPRESSION) === Redis::COMPRESSION_LZ4;
}
```

Comment (TheLevti) [reply src/Illuminate/Cache/RedisLock.php:219]: Sure, I was just not sure how static analyzers will react if classes/constants do not exist as they are added bases on compile config on phpredis

File: src/Illuminate/Cache/RedisLock.php (hunk 1 above)
Comment (TheLevti) [reply src/Illuminate/Cache/RedisLock.php]: I have moved this whole code into a different class.

Comment (TheLevti) [reply src/Illuminate/Cache/RedisLock.php]: Also I added a new test class for this new one. Seems to be a lot cleaner now as this code is very specific to the extension and should not be mixed with the general redis code.

**Comment by TheLevti** [comment]
For the tests that need the specific extensions I am waiting for https://github.com/shivammathur/setup-php/issues/419.

Currently in the pipeline only the serialization (php/json/none) are run. The more rare usecase of also enabled compression works fine locally.

image

Once it is possible, I will submit another merge request to install those extension in the pipeline so those are also run. Currently they are skipped.

**Comment by taylorotwell** [comment]
@TheLevti is this ready for review now?

**Comment by TheLevti** [comment]
> @TheLevti is this ready for review now?

Yes, LZ4 support is added and should work once the phpredis extension fixes/adjusts their code. All other compression/serialization methods are working.

File: src/Illuminate/Cache/PhpRedisLock.php [hunk 3]
```diff
@@ -0,0 +1,89 @@
...
+        $client = $this->redis->client();
+
+        /* If a serialization mode such as "php" or "igbinary" and/or a
+         * compression mode such as "lzf" or "zstd" is enabled, the owner
+         * must be serialized and/or compressed by us, because phpredis does
+         * not do this for the eval command.
+         *
+         * Name must not be modified!
+         */
+        $owner = $client->_serialize($this->owner);
```
Comment (taylorotwell) [inline src/Illuminate/Cache/PhpRedisLock.php:40]: So adding this call will not break any existing locks that were created before this change? I could imagine a scenario where locks exist - application is deployed with this changed - will those locks still be able to be regathered and released?

Comment (TheLevti) [reply src/Illuminate/Cache/PhpRedisLock.php:40]: Yes they will be. If phpredis has serialization disabled, this will return the same value as passed down. I wrote a test for this case, which passes. (See: https://github.com/phpredis/phpredis/blob/develop/library.c#L3029)

Comment (TheLevti) [reply src/Illuminate/Cache/PhpRedisLock.php:40]: Nothing changes in regards of the redlock algorithm. The same eval call is done with the same lua script executed. This change is all about modifying the passed arguments to the eval call the same way as phpredis did on the initial lock set command.

**Comment by it-can** [comment]
> > Would also be nice to have laravel also support compression and serializer functions for phpredis… like this #31262
> 
> I know, but before we can add those options to the laravel redis config, we should properly support the locking mechanism. So this pull request should be a prerequisite for the options to be added.

Cool this pr is merged!
