### PR TITLE
[7.x] Fix route helper with custom binding key

### LINKED ISSUE #32201: route() helper doesn't generate correct URI's for routes with a custom binding key
- Laravel Version: 7.4.0 (since 7.0.0)
- PHP Version: 7.3.13
- Database Driver & Version: MySQL 5.7 (MariaDB)

### Description:
The `route()` helper doesn't account for the Laravel 7 way of specifying a custom route model binding key inside the route parameter when passing a Model to use implicit binding. It will generate the URL with ID's as parameters instead of the expected column (like a slug).

### Steps To Reproduce:
1. Create a route like this:
```
Route::get('/profile/{user:slug}', function (User $user) {
    return $user;
})->name('profile');
```
2. Try to generate a URI using the `route()` helper: `route('profile, $user)`
3. Inspect/view the given URI, it should look something like: `https://app.test/profile/1` instead of expected: `https://app.test/profile/@johndoe` (assuming the `slug` is `@johndoe`)

### PR DESCRIPTION
**Pull request by BSN4**
fix #32201

thanks to @abdumu for helping me with this issue

### CODE REVIEW

File: src/Illuminate/Routing/Route.php [hunk 1]
```diff
@@ -485,6 +485,10 @@ public function signatureParameters($subClass = null)
      */
     public function bindingFieldFor($parameter)
     {
+        if (is_int($parameter)) {
```
Comment (rbuzzibarrios) [inline src/Illuminate/Routing/Route.php:488]: It just a suggestion. 
```
    $bindingFields = $this->bindingFields;
    if (is_int($parameter)) {
        $bindingFields = array_values($bindingFields);
    }
    
    return $bindingFields[$parameter] ?? null;
```

Or

```
    $bindingFields = $this->bindingFields;
    
	return (is_int($parameter) ? array_values($bindingFields)[$parameter] : bindingFields[$parameter]) ?? null;
```

Comment (if4lcon) [reply src/Illuminate/Routing/Route.php:488]: I did it first like 

```php
    $bindingFields = is_int($parameter) ? array_values($this->bindingFields) : $this->bindingFields;

        return $bindingFields[$parameter] ?? null;
```

but I wanted the code to be more readable

**Review by rbuzzibarrios — APPROVED** [review]
