### PR TITLE
[11.x] Fix double-quoted string literals on SQLite

### LINKED ISSUE #51609: SQLiteGrammar.php compileColumns failing on quotes around table name
### Laravel Version

11.8

### PHP Version

8.3

### Database Driver & Version

sqlite3 3.45.1 (freebsd)

### Description

Ref: https://github.com/laravel/framework/discussions/51562

Error is `SQLSTATE[HY000]: General error: 1 no such column:`

This originally popped up in testing. Not sure why this is not working but maybe a change in sqlite? It works ok in Ubuntu with sqlite3 version 3.37.2-2ubuntu0.3.

### Steps To Reproduce

In an attempt to reproduce, the closest I have come is to run a command line in sqlite3:
```
sqlite>  select name, type, not "notnull" as "nullable", dflt_value as "default", pk as "primary", hidden as "extra" from pragma_table_xinfo("users_sockets") order by cid asc;
Parse error: no such column: users_sockets
  imary", hidden as "extra" from pragma_table_xinfo("users_sockets") order by ci
                                      error here ---^
```

However, when run with single quotes:
```
sqlite>  select name, type, not "notnull" as "nullable", dflt_value as "default", pk as "primary", hidden as "extra" from pragma_table_xinfo('users_sockets') order by cid asc;
user_id|INTEGER|0||0|0
socket_id|varchar(191)|0||0|0
created_at|timestamp|1|NULL|0|0
updated_at|timestamp|1|NULL|0|0
```

### PR DESCRIPTION
**Pull request by hafezdivandari**
Fixes #51609 

As of SQLite 3.41.0 the [double-quoted string literals misfeature](https://www.sqlite.org/quirks.html#dblquote) is disabled by default for CLI builds.

### CODE REVIEW

File: src/Illuminate/Database/Schema/Grammars/SQLiteGrammar.php [hunk 1]
```diff
@@ -106,7 +106,7 @@ public function compileIndexes($table)
         return sprintf(
             'select "primary" as name, group_concat(col) as columns, 1 as "unique", 1 as "primary" '
```
Comment (garrettboone) [inline src/Illuminate/Database/Schema/Grammars/SQLiteGrammar.php:107]: Also `'select \'primary\' as name` here

Comment (hafezdivandari) [reply src/Illuminate/Database/Schema/Grammars/SQLiteGrammar.php]: Thanks!
