### PR TITLE
[11.x] Ignoring column definitions when determining if a blueprint has a create command

### LINKED ISSUE #52175: Cannot add column named `create` to an existing table
### Laravel Version

^11.15

### PHP Version

8.2.18

### Database Driver & Version

N/A

### Description

Unable to add a column named `create` to any existing table.

This appears to be the offending commit https://github.com/laravel/framework/commit/980e8d5cd0bfe72f2cd878a785e8d2c22eefaf18 

### Steps To Reproduce

Create a table and then attempt to add a column named `create` to it via a migration.

See https://github.com/workhouse-advertising/laravel-framework/tree/bugfix/cannot-add-column-called-create for example tests.

### PR DESCRIPTION
**Pull request by kingsven**
Fixes https://github.com/laravel/framework/issues/52175

### CODE REVIEW

File: tests/Integration/Database/DatabaseSchemaBlueprintTest.php [hunk 1]
```diff
@@ -507,6 +507,61 @@ public function testAddUniqueIndexWithNameWorks()
...
+            $table->string('create')->nullable(false);
+        });
+
+        $queries = $blueprintSqlServer->toSql(DB::connection(), new SqlServerGrammar);
+
+        $expected = [
+            'alter table "users" add "create" nvarchar(255) not null',
+        ];
+
+        $this->assertEquals($expected, $queries);
```
Comment (hafezdivandari) [inline tests/Integration/Database/DatabaseSchemaBlueprintTest.php:562]:
```suggestion
        Schema::create('users', function (Blueprint $table) {
            $table->string('name');
        });

        Schema::table('users', function (Blueprint $table) {
            $table->string('create');
        });

        $this->assertTrue(Schema::hasColumn('users', 'create'));
```

**Review by hafezdivandari — COMMENTED** [review]
You may simplify the integration test.

**Comment by driesvints** [comment]
@hafezdivandari your changes apparently are failing this test. Could you perhaps have a new look and send in a fix?
