### PR TITLE
[8.x] Fix appendable attributes in Blade components

### LINKED ISSUE #35128: Prepending component attributes causes an exception when said attribute is missing in calling template
- Laravel Version: 8.13
- PHP Version: 7.4
- Database Driver & Version: none

### Description:

Rendering a component with prepended attributes but without overriding that attribute in the calling template yields an error.

### Steps To Reproduce:

- `composer create-project laravel/laravel testing`
- `php artisan make:component TestComponent`
- Copy the example from the docs into the template

```blade
<div {{ $attributes->merge(['data-controller' => $attributes->prepends('profile-controller')]) }}>
    {{ $slot }}
</div>
```
- attempt to render the component without 'data-controller' specified.

Rendering this component like so: `<x-test-component data-controller="some-controller" />` works as expected.

Rendering this component like so: `<x-test-component />` yields the following error:
Screen Shot 2020-11-06 at 13 59 09

I would expect to have the string `profile-controller` to be the default and only value present if no attribute named `data-controller` is specified.

### PR DESCRIPTION
**Pull request by panda-madness**
Currently, attempting to render a component which prepends a non-class attribute in it's template without actually overriding it in the calling template yields an Exception.

For example, given the following component called `test-component`:

```blade
<div {{ $attributes->merge(['data-controller' => $attributes->prepends('profile-controller')]) }}>
    {{ $slot }}
</div>
```

Rendering this component like so: `<x-test-component data-controller="some-controller" />` works as expected.

Rendering this component like so: `<x-test-component />` yields the following error:

Screen Shot 2020-11-06 at 13 59 09

This PR fixes this behavior. `<x-test-component />` will now properly render as
```
<div data-controller="profile-controller"></div>
```

See #35128 for more details.

### CODE REVIEW

File: src/Illuminate/View/AppendableAttributeValue.php [hunk 1]
```diff
@@ -21,4 +21,9 @@ public function __construct($value)
     {
         $this->value = $value;
     }
+
+    public function __toString()
+    {
+        return (string)$this->value;
```
Comment (driesvints) [inline src/Illuminate/View/AppendableAttributeValue.php:27]:
```suggestion
        return (string) $this->value;
```

File: src/Illuminate/View/AppendableAttributeValue.php [hunk 2]
```diff
@@ -21,4 +21,9 @@ public function __construct($value)
     {
         $this->value = $value;
     }
+
+    public function __toString()
```
Comment (driesvints) [inline src/Illuminate/View/AppendableAttributeValue.php:25]: Add a docblock in the same formatting as the rest of the framework.

**Comment by driesvints** [comment]
@panda-madness it's also best that you provide a thorough explanation in your PR description (see our PR templates) so Taylor knows what this is about and why it's needed. Don't just link to an issue.

**Comment by panda-madness** [comment]
@driesvints I've updated the PR description.

I've also modified the test to include this use case, but I'm not quite sure why an unrelated test started failing...

**Comment by driesvints** [comment]
@panda-madness your whitespace change from here seems to be the culprit: https://github.com/laravel/framework/pull/35131/commits/8b2e529a1e4c6fc8dc4138f6d22b1a5798e4b588#diff-9e28a6d9f9f352efc3960eab4ff2d081a25459d765d3f1ac2c9735dd4356dd50L45

Think I got it now.

**Comment by panda-madness** [comment]
This is a little nitpicky, but should we change the `AppendableAttributeValue` class name to `PrependableAttributeValue` so it maches the method name better?

**Comment by driesvints** [comment]
@panda-madness probably not worth the breaking change.
