### PR TITLE
[9.x] Prevent error in db/model commands when using unsupported columns

### LINKED ISSUE #43630: New command php artisan db:show returns exception on laravel version 9.24 with mysql 5.7 database
- Laravel Version: 9.24.0
- PHP Version: 8.1.9
- Database Driver & Version: Mysql 5.7.38

### Description:
php artisan db:show returns "Unknown database type enum requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it." on mysql 5.7

``` 
   Doctrine\DBAL\Exception 

  Unknown database type enum requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it.

  at vendor/doctrine/dbal/src/Platforms/AbstractPlatform.php:418
    414▕ 
    415▕         $dbType = strtolower($dbType);
    416▕ 
    417▕         if (! isset($this->doctrineTypeMapping[$dbType])) {
  ➜ 418▕             throw new Exception(
    419▕                 'Unknown database type ' . $dbType . ' requested, ' . static::class . ' may not support it.'
    420▕             );
    421▕         }
    422▕ 

      +19 vendor frames 
  20  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()

```

### Steps To Reproduce:
Run command `php artisan db:show` on laravel version 9.24 with mysql 5.7 database

### PR DESCRIPTION
**Pull request by joedixon**
The PR resolves #43630 #43622 

The `doctrine/dbal` package does not support enum types when listing database columns. This PR adds support for mapping `enum` and `sysname` (issue with some distributions of sqlsrv) to `string`. The Artisan `db:show`, `db:table` and `model:show` commands have all been updated to use it.

Additonally, `db:show` uses the `rescue` helper to prevent an error if the engine type is not available. This PR also prevents the error from being reported.

### CODE REVIEW

**Comment by mziraki** [comment]
@jbrooksuk @joedixon
model:show command needs this mapping too

**Review by jbrooksuk — APPROVED** [review]

File: src/Illuminate/Database/Console/DatabaseInspectionCommand.php [hunk 1]
```diff
@@ -193,4 +193,17 @@ protected function installDependencies()
...
     }
+
+    /**
+     * Register custom Doctrine type mappings.
+     *
+     * @param  \Doctrine\DBAL\Platforms\AbstractPlatform  $platform
+     * @param  string  $database
+     * @return void
+     */
+    protected function regsisterTypeMapping(AbstractPlatform $platform)
```
Comment (Sergiobop) [inline src/Illuminate/Database/Console/DatabaseInspectionCommand.php:204]: Is this a typo? regsister

Comment (nunomaduro) [inline src/Illuminate/Database/Console/DatabaseInspectionCommand.php:204]: Typo here.

File: src/Illuminate/Database/Console/DatabaseInspectionCommand.php [hunk 2]
```diff
@@ -193,4 +193,17 @@ protected function installDependencies()
             }
         }
     }
+
+    /**
+     * Register custom Doctrine type mappings.
+     *
+     * @param  \Doctrine\DBAL\Platforms\AbstractPlatform  $platform
+     * @param  string  $database
```
Comment (nunomaduro) [inline src/Illuminate/Database/Console/DatabaseInspectionCommand.php:201]: This argument is not needed.

**Review by nunomaduro — CHANGES_REQUESTED** [review]

File: src/Illuminate/Database/Console/DatabaseInspectionCommand.php (hunk 1 above)
Comment (joedixon) [reply src/Illuminate/Database/Console/DatabaseInspectionCommand.php]: Thank you!

**Comment by lupinitylabs** [comment]
Thanks for addressing this @joedixon ! I opened a PR at #43645 for the same issue, so I guess it can be closed.

There are two things to consider concerning your implementation:

1. the issue with `enum` types only seems to exist on MySQL databases, so we probably might want register the type mapping only on MySQL platforms.
2. the issue also exists for `point` types, so a mapping for these should probably also be added.

**Comment by joedixon** [comment]
Hey @lupinitylabs - thanks for bringing the additional missing mapping to my attention. I've gone ahead and added some more that we were missing support for.

I'm not sure it's worth conditionally checking the database type as if it's only an issue with, for instance, MySQL, the other database types won't be impacted anyway.

**Comment by lupinitylabs** [comment]
Yes, I guess since we are just reading the structure anyways, just mapping it all to string might be fine.
