### PR TITLE
[11.x] Fixes `config:publish` with `dontMergeFrameworkConfiguration()` set to `true`

### LINKED ISSUE #51736: Config stub does not match default config file. Causes error when using dontMergeFrameworkConfiguration()
### Laravel Version

11.1.1

### PHP Version

8.2.13

### Database Driver & Version

_No response_

### Description

When publishing all configuration files the stub for app.php does not contain all used keys.
Should the stubs contain everything that is required?

I found this issue because I am using the new `dontMergeFrameworkConfiguration()` app setting.
To use this setting I believe you must publish all config files and maintain them yourself.
But once you have done that you get errors as there are missing config keys.

if you run `composer install` after publishing all config files and using  the setting `dontMergeFrameworkConfiguration()`, this error is produced.

```
In RegisterProviders.php line 59:

  array_merge(): Argument #1 must be of type array, null given
```

The below repository is a new Laravel install with all config published that shows it errors when running `composer install`
https://github.com/MaxGiting/publish-config-example

### Steps To Reproduce

1. New Laravel install `composer create-project laravel/laravel publish-config-example`
2. Publish all config files `php artisan config:publish --all --force`
3. Turn off config merging with `dontMergeFrameworkConfiguration()` https://github.com/MaxGiting/publish-config-example/commit/ced8045ea4379a691e5a1b961ae0afa8d2c4dad6
4. Run `composer install`

### PR DESCRIPTION
**Pull request by crynobone**
fixes #51736

### CODE REVIEW

File: src/Illuminate/Foundation/Bootstrap/RegisterProviders.php [hunk 1]
```diff
@@ -57,7 +58,7 @@ protected function mergeAdditionalProviders(Application $app)
         $app->make('config')->set(
             'app.providers',
             array_merge(
-                $app->make('config')->get('app.providers'),
+                $app->make('config')->get('app.providers') ?? ServiceProvider::defaultProviders()->toArray(),
```
Comment (crynobone) [inline src/Illuminate/Foundation/Bootstrap/RegisterProviders.php:61]: Fixed scenario where `app.php` configuration file is not available. Verified with tests below.
