### PR TITLE
[12.x] Rollback lingering PDO transaction before retrying on commit deadlock

### LINKED ISSUE #58894: "There is already an active transaction" when using DB::transaction
### Laravel Version

12

### PHP Version

8.4

### Database Driver & Version

MySQL

### Description

We occasionally get the PDOException: "There is already an active transaction" when using DB::transaction with a retry. This happens mainly during peak hours when there's a significant amount of concurrent queries on the Galera cluster. Before I dove deeper into this, I've confirmed there are no overlapping transactions in code. The reason I eventually did a deep dive is because [this issue](https://github.com/laravel/framework/issues/37358) has been reported (in 2021) and closed without an explanation as to why this may be happening.

So hopefully the observations and conclusions I made are the explanation for this occurrence:
1) Without DB::transaction, we get deadlocks at approximately the same rate as we'd get the exception described above.

2) Laravel thinks there's no transactions active. The PDO driver obviously does and since this driver fetches the session state from the database (as can be seen [here](https://github.com/php/php-src/blob/master/ext/pdo_mysql/mysql_driver.c#L641)), I'd say the driver is always right.

3) Internally we've discussed whether the `autocommit` may be disabled on execution, though this is always the case when you explicitly start a transaction as described [here](https://mariadb.com/docs/server/reference/sql-statements/transactions/start-transaction#autocommit):
`To disable autocommit mode for a single series of statements, use the START TRANSACTION statement. To disable autocommit mode for a single series of statements, use the START TRANSACTION statement.`.
Something similar is stated in the MySQL-documentation [here](https://dev.mysql.com/doc/refman/9.6/en/commit.html): `To disable autocommit mode implicitly for a single series of statements, use the START TRANSACTION statement`

4) From what I can see in `ManagesTransactions.php` [here](https://github.com/laravel/framework/blob/12.x/src/Illuminate/Database/Concerns/ManagesTransactions.php) is that the same PDO object is used when retrying, so I assumed the same session is used.

5) Finally, based on 3 and 4, I assume the database starts a new transaction after a deadlock occurs, since a session is still active. Then after this, a second try of the query is performed in DB::transaction meaning `START TRANSACTION` is executed again. And because there is an implicit transaction started by the database, the "There is already an active transaction"-exception is thrown.

In conclusion, what I suspect happens is:
1. DB::transaction executes `pdo->beginTransaction()` and autocommit is disabled.
2. Write queries are executed.
3. Commit fails due to a deadlock.
4. Database starts a new transaction since the session is kept active and autocommit is disabled for the session.
5. DB::transaction executes `pdo->beginTransaction()`
6. PDO requests the state and the database replies that there's a transaction active.
7. `PDOException: "There is already an active transaction"`

I've suggested the developers of the project (where this exception occurs), to manually write the retries with beginTransaction where each time a commit fails, the rollback-function is called & `autocommit` is enabled before trying beginTransaction again. This will force the implicit transaction to be rolled back and beginTransaction starts a new transaction, disabling autocommit again.

This could be the solution for `DB::transaction` as well, but it does not feel like the cleanest approach so I am open to suggestions.

### Steps To Reproduce

The deployment is as follows: 
- The Galera Cluster consists of 3 nodes.
- There's 60 pods of the Laravel-app which, combined, probably write to the database around 1000-1500 times a second.

EDIT:

I've initially overlooked the following in [MySQL documentation](https://dev.mysql.com/doc/refman/9.6/en/commit.html) (there is not something similar stated in MariaDB): 
`With START TRANSACTION, autocommit remains disabled until you end the transaction with COMMIT or ROLLBACK. The autocommit mode then reverts to its previous state.`
Though, since this is an exception it could be possible that this revert does not happen (which I'm currently looking into).

EDIT 2:

A rollback is implemented at the project before enabling `autocommit`, which is a bit redundant but this is to be sure there's nothing committed due to setting enabling autocommit again.

### PR DESCRIPTION
**Pull request by dxnter**
Fixes #58894

When `DB::transaction()` retries after a deadlock during commit, the PDO connection may still have an active (implicit) transaction because MySQL keeps autocommit disabled for the session. The next `beginTransaction()` call then throws `PDOException: "There is already an active transaction"`.

This adds a simple `$pdo->rollBack()` in `handleCommitTransactionException` before returning for retry, matching how `handleTransactionException` already cleans up PDO state through `performRollback()` when deadlocks occur during the callback.

### CODE REVIEW

File: tests/Database/DatabaseConnectionTest.php [hunk 1]
```diff
@@ -317,16 +317,37 @@ public function testTransactionMethodRunsSuccessfully()
...
     {
         $this->expectException(PDOException::class);
         $this->expectExceptionMessage('Serialization failure');
 
-        $pdo = $this->getMockBuilder(DatabaseConnectionTestMockPDO::class)->onlyMethods(['beginTransaction', 'commit', 'rollBack'])->getMock();
+        $pdo = $this->getMockBuilder(DatabaseConnectionTestMockPDO::class)->onlyMethods(['inTransaction', 'beginTransaction', 'commit', 'rollBack'])->getMock();
         $mock = $this->getMockConnection([], $pdo);
         $pdo->expects($this->exactly(3))->method('commit')->will($this->throwException(new DatabaseConnectionTestMockPDOException('Serialization failure', '40001')));
         $pdo->expects($this->exactly(3))->method('beginTransaction');
-        $pdo->expects($this->never())->method('rollBack');
```
Comment (taylorotwell) [inline tests/Database/DatabaseConnectionTest.php:329]: It feels a bit spooky to me we used to explicitly test that rollBack was specifically not called. I wonder why? Did we not roll back for a reason?

Comment (taylorotwell) [reply tests/Database/DatabaseConnectionTest.php:329]: https://github.com/laravel/framework/pull/29067/changes relevant PR where it says the transaction is rolled back automatically and we shouldn't roll back again

Comment (dxnter) [reply tests/Database/DatabaseConnectionTest.php:329]: > [#29067 (changes)](https://github.com/laravel/framework/pull/29067/changes) relevant PR where it says the transaction is rolled back automatically and we shouldn't roll back again

That is correct for the database-level transaction, MySQL does roll it back on deadlock.

The problem is that `PDO::beginTransaction()` also disables autocommit for the session. After MySQL rolls back the deadlocked transaction, autocommit remains off, so MySQL implicitly starts a new transaction. PDO then sees an active transaction on the next `beginTransaction()` call and throws the exception

Comment (semvankoutrik) [reply tests/Database/DatabaseConnectionTest.php:329]: To correct my assumptions in the bug report which I see repeated here: 

I've actually found the code in MariaDB that _does_ revert the autocommit flag [here](https://github.com/MariaDB/server/blob/637f8c4db7533fc4f22433f042cc83f7ba3bfb41/sql/transaction.cc#L448) (the comment above those lines actually describes that they prevent what I suspected might've been the issue). 

I still think there is a small window, possibly bigger with Galera, where the autocommit flag can be overwritten to false where it should've been true. However, a similar fix to this PR where the PDO is checked for active transactions, did work for us.
