### PR TITLE
[5.7] Improve eager loading performance on MySQL

### LINKED ISSUE #26051: Performance issue with WhereIn (and with eager loading)
- Laravel Version: 5.7.9
- PHP Version: 7.1.21
- Database Driver & Version: MySQL 5.5.5 -10.2.15-MariaDB

### Description:

Doing a whereIn with prepared query take much more time than doing a raw query

### Steps To Reproduce:

Create 10000 users

do : 

```
$user_ids = \App\User::pluck('id');
 \App\User::whereIn('id', $user_ids->sort())->get();
```

this request take 908ms to execute ,

But when doing : 

```
 \DB::table('users')->select('*')->whereRaw("id in ('1', '2', '3', '4', [...],'10000')")->get();
```

This on is taking only 68ms to execute.

I have made a demo project here : https://github.com/Arkhas/laravel-perf-wherein

(just run `php artisan migrate:refresh --seed` and visit the homepage (PHP Debug bar is enable))

it seems that it's an issue with prepared queries of php PDO : 

https://laracasts.com/discuss/channels/general-discussion/eloquent-is-so-slow?page=2
https://stackoverflow.com/questions/4350718/why-are-certain-types-of-prepared-queries-using-pdo-in-php-with-mysql-slow

when doing eager loading with eloquent, it seems that it use the first synthax and take a lot more time to process

the question here is : Is it required to do prepared queries for eloquent eager loading ? Or is it possible to eager load using the second synthax?

### PR DESCRIPTION
**Pull request by staudenmeir**
There is an old [bug](https://bugs.php.net/bug.php?id=53458) in the `PDO` implementation for MySQL that slows down larges `WHERE IN` queries. When the query has a few thousand bindings, the time execution time of `fetchAll()` increases non-linearly.

In Laravel, this especially affects eager loading. For models with integer keys, we can fix this by using raw `WHERE IN` clauses. The new `whereInRaw()` method applies `intval()` to all values, so this is as secure as a prepared statement.

It's certainly not a very elegant solution but still worth considering for the core. Since most Laravel sites run on MySQL/MariaDB and most sites use eager loading with integer keys (my assumptions), this would improve the performance on *a lot* of sites – even if they aren't eager loading thousands of records at once. The individual query may only gain a few milliseconds, but over all sites combined, this adds up.

This PR shows a sample implementation for `HasMany` relationships. The same changes would apply to all the other relationships.

Fixes #26051.

### CODE REVIEW

**Comment by laurencei** [comment]
Given this is a performance related PR - would be worth providing some performance comparisons to see if the changes actually make a meaningful difference?

**Comment by JayBizzle** [comment]
Just as a quick headline statistics from the referenced issue (#26051), some examples show a performance improvement of over 90% in query time

**Comment by mfn** [comment]
I don't see anything mysql specific, is this change for all drivers then?

**Comment by staudenmeir** [comment]
@mfn Yes, the change affects all drivers. We could make it MySQL-specific, but I don't think that makes sense. All databases benefit from a raw query in this case, even if the performance improvement is smaller than on MySQL.

**Comment by mfn** [comment]
> All databases benefit from a raw query in this case, even if the performance improvement is smaller than on MySQL.

Awesome, and well, great to see it's already merged; thx!

**Comment by vlakoff** [comment]
Do we really need the `array_map('intval', $values)`?

* I guess it brings a performance hit
* What if someone tries to use `$builder->whereInRaw()` with something other than ints? The cast seems really unexpected in this scenario ("raw" means "raw" after all)

**Comment by vlakoff** [comment]
I'd think of replacing `$builder->whereInRaw` with 2 methods: `whereInRawInts` and `whereInRawStrings`

* `whereInRawInts`: expects to be provided with ints
* `whereInRawStrings`: escapes the values: encloses with quotes, escapes the quotes, etc.

**Comment by vlakoff** [comment]
Ok, let's just forget about my `whereInRawStrings` (no bindings, "manual" escaping), as it hasn't been requested for yet, and outside the scope of the current case.

Still, I'd suggest renaming `whereInRaw` to `whereInRawInts`, to avoid confusion.

I'd also suggest replacing the `array_map('intval', $values)` with the following, slightly faster (~10%):

```php
foreach ($values as &$value) {
    $value = (int) $value;
}
```

File: src/Illuminate/Database/Query/Builder.php [hunk 1]
```diff
@@ -948,6 +948,30 @@ protected function whereInExistingQuery($column, $query, $boolean, $not)
...
+     * @param  array   $values
+     * @param  string  $boolean
+     * @param  bool    $not
+     * @return $this
+     */
+    public function whereInRaw($column, array $values, $boolean = 'and', $not = false)
+    {
+        $type = $not ? 'NotInRaw' : 'InRaw';
+
+        if ($values instanceof Arrayable) {
```
Comment (vlakoff) [inline src/Illuminate/Database/Query/Builder.php]: Because of the `array $values` typehint in the parameters definition above, `$values` is forcibly an array here.

For consistency with `whereIn()` I think the typehint should be removed.

Comment (staudenmeir) [reply src/Illuminate/Database/Query/Builder.php]: Thanks!
