### PR TITLE
[11.x] `Cache::flexible` improvements

### LINKED ISSUE #52847: Cache::forget() doesn't delete cache created via Cache::flexible()
### Laravel Version

11.23

### PHP Version

8.3

### Database Driver & Version

_No response_

### Description

I potentially found a bug with `Cache::flexible()`. Not sure if it is intended or not... but I guess not.

When using `Cache::flexible()`, two items are stored in the cache. Whenever I `Cache::forget()` an item that was created via flexible, it doesn't delete the second item (`...:created`). Now I have to manually delete that item, so the cache is actually gone.

### Steps To Reproduce

**Step 1:**
```php
Cache::flexible('foo', [1, 100], function () {
    return 'bar';
});
```

Two items are cached:
1. `"example"`
2. `"example:created"`

**Step 2:**
```php
Cache::forget('foo');
```

One item is deleted, `example`.
The other `example:created` still exists.

### PR DESCRIPTION
**Pull request by timacdonald**
## Bugfix

Addresses a potential bug in `Cache::flexible` where the main key has been forgotten, via `Cache::forget('foo')`, but the TTL key, i.e., `foo:created`, remains in the cache.

When `Cache::flexible` is called again, `null` is returned rather than calling the `Closure $callback` and refreshing the value in the cache.

There is a race condition in this solution where the `$value` is intentionally `null` and the value expires after we retrieve it from the cache but before we check `$this->missing($key)`. I don't really see any real-world problem with refreshing the cache in that situation though. The value just expired after all. Heck, I'd even call it a feature.

## Cleanup flexible TTL keys

The database and file driver may leave behind TTL keys when the main key has been forgotten. Both the database and file driver will now attempt to cleanup the flexible TTL keys as well.

## TTL key rename

Because we now implicitly clean up flexible TTL keys in the database and file driver, I felt it best we rename the TTL key, as `...:created` could easily be a user land key that we accidentally delete.

We now namespace the key `illuminate:cache:flexible:created:{key}`.

I suppose this is a breaking change, but I think removing the possibility of accidentally deleting user-land keys is more breaking than having the cache value refreshed early for this one off change.

## Standardise key names

While I was in here making this change I also updated the defer key and the cache lock name to match the `illuminate:cache:flexible:*` pattern.

fixes #52847

### CODE REVIEW

File: tests/Cache/CacheFileStoreTest.php [hunk 1]
```diff
@@ -285,14 +285,15 @@ public function testRemoveDeletesFileDoesntExist()
...
         $store = new FileStore($files, __DIR__);
         $store->put('foobar', 'Hello Baby', 10);
-        $files->expects($this->once())->method('exists')->with($this->equalTo(__DIR__.'/'.$cache_dir.'/'.$hash))->willReturn(true);
-        $files->expects($this->once())->method('delete')->with($this->equalTo(__DIR__.'/'.$cache_dir.'/'.$hash));
+
+        $this->assertFileExists($store->path('foobar'));
+
         $store->forget('foobar');
+
+        $this->assertFileDoesNotExist($store->path('foobar'));
```
Comment (timacdonald) [inline tests/Cache/CacheFileStoreTest.php:296]: I'm modified this test so it really does check that the file is cleaned up. There was an issue with the mock because of the new key being deleted. Mockery just burnt my time trying to make it work.

This test is 1000% better without the mocks anyway.

**Comment by Tklaversma** [comment]
@timacdonald Maybe it's just me, but I think this is still not working as expected when using Redis (I didn't test other drivers). When I do `Cache::forget('foo')`, it still leaves `illuminate:cache:flexible:created:foo` in the database.

Although after re-creating the same cache item it replaces the existing `illuminate:cache:flexible:created:foo`, which is a good thing, I think it's still best to remove it when `Cache::forget()` is being called. I can imagine a scenario where `Cache::flexible()` is used extensively with very high TTLs and the database is filled with unnecessary data after forget is called.

**Comment by timacdonald** [comment]
@Tklaversma, we have decided to leave the flexible keys to naturally expire for the cache drivers that respect a TTL.

As you mentioned, they would be replaced correctly when called again, so functionally there is no issue, and otherwise they would naturally expire over time.

This is similar to what happens with cache tags. It is not an ideal solution but the direction we are heading for now.

We manually clean out the database and file drivers because they won't naturally expire over time.

**Comment by RoodFruit** [comment]
@timacdonald I understand, but can't there be a middle ground for `Cache::flexible()` (and maybe `Cache::tags()` as well), where we introduce an extra parameter on `Cache::forget()` for example, that will also remove these :created keys? Heck, maybe even introduce an additional function called `Cache::forceForget()`.

In my particular case I don't want these remnants, because I have many cache items with high TTL's. I do have workarounds, but in the light of "keeping your database clean", having such an option to be able to delete those keys as well, would be great addition. And I don't think I'm the only one in this matter. 

I'm curious to your thought about this. Let me know 👍🏻

**Comment by Tklaversma** [comment]
@timacdonald I understand, but can't there be a middle ground for `Cache::flexible()` (and maybe `Cache::tags()` as well), where we introduce an extra parameter on `Cache::forget()` for example, that will also remove these :created keys? Heck, maybe even introduce an additional function called `Cache::forceForget()`.

In my particular case I don't want these remnants, because I have many cache items with high TTL's. I do have workarounds, but in the light of "keeping your database clean", having such an option to be able to delete those keys as well, would be great addition. And I don't think I'm the only one in this matter. 

I'm curious to your thought about this. Let me know 👍🏻

**Comment by timacdonald** [comment]
I don't think we have plans for this but will certainly keep an eye feedback around all this.

**Comment by Tklaversma** [comment]
@timacdonald Would you be open to this change if I supply a PR? Don't want to waste my time.

**Comment by Tklaversma** [comment]
@timacdonald Ok, readying a PR. I found out that you already did delete those `illuminate:cache:flexible:created:...` keys, but only for the database and file stores. I'll submit my PR that will align the other stores with this functionality as well.

**Comment by Tklaversma** [comment]
See https://github.com/laravel/framework/pull/52936.

**Comment by mra-dev** [comment]
This PR is actually breaking my **_CLI App_** when using `Cache` with `file-driver`

In this line:
[#diff-4a1de3db154fb3881008aacba13f82699df89754a68b9d913077177d36821f63R251](https://github.com/laravel/framework/pull/52891/files#diff-4a1de3db154fb3881008aacba13f82699df89754a68b9d913077177d36821f63R251)
**Note: I checked it & by deleting that line. everything went back to normal.**

There's actually **no file** named that. but it tries to delete it and the holy `Exception` comes up.

Mustn't there be an `exists()` check and then delete it ???

Exception ([Full](https://sourceb.in/a1NYng7oDr)):
> [2024-10-01 xx:xx:xx] local.ERROR: unlink(/home/storage/framework/cache/data/2f/a0/2fa0e....95e779): No such file or directory {"exception":"[object] (Exception: unlink(/home/storage/framework/cache/data/2f/a0/2fa0...e779): No such file or directory at /home/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:308)

**Comment by timacdonald** [comment]
@mra-dev, that is rather strange.

Do you have a custom implementation of the filesystem in your application? I can't seem to replicate that behaviour locally.

I tried with the following in a fresh Laravel application.

```php
Cache::driver('file')->forget('key');

Cache::driver('file')->put('key', 'value', ttl: 5);
Cache::driver('file')->forget('key');

return 'ok';
```

I've opened a PR with a passing test for this behaviour: https://github.com/laravel/framework/pull/53018

Could you provide a way for me to replicate the issue to ensure we have an appropriate test in place?

**Comment by mra-dev** [comment]
@timacdonald I'm using pure Laravel (nothing custom)
Situation: I'm processing incoming "messages" in Laravel's Queue.
Each has to be checked in a check-wall which involves "rememberForever" & "forget" (no flexible, just simple cache access)
In versions prior to 11.24, everything's were fine. 
After upgrading, i got the Exception i mentioned above.

The problem is that i'm in CLI. Inside web side, everything's fine.

**Comment by mra-dev** [comment]
Oh, and by the way, there are cases which may there be "race condition" or "concurrency".
Means: with a 20~80 ms between each cache access or forget

**Comment by timacdonald** [comment]
Thanks for the additional info.

Can you see why my [test in my PR](https://github.com/laravel/framework/pull/53018) would be passing without adding any changes?

I've tried this on both the web and the CLI and everything is working as expected. Not seeing any logs or exceptions.

```php
// console.php

Artisan::command('dev', function () {
    Cache::driver('file')->forget('key');

    Cache::driver('file')->put('key', 'value', ttl: 5);
    Cache::driver('file')->forget('key');

    echo 'ok';
});

// web.php

Route::get('/', function () {
    Cache::driver('file')->forget('key');

    Cache::driver('file')->put('key', 'value', ttl: 5);
    Cache::driver('file')->forget('key');

    return 'ok';
});
```

Wondering if there is some `php.ini` configuration needed to make this throw an exception?

We will get it fixed for you. Just want to make sure we have a test in place for future developers modifying the code.

**Comment by mra-dev** [comment]
One potential thing could be write-protection that Laravel does on the file.
And when another process with another user or group, tries to do operations on it; it throws the error.

One another weak possibility could be the Queue's long running process not knowing PHP's "clearstatcache" !!!?

But, 100% sure that this line corrupts the APP.

Maybe it isn't created at all in normal cache puts ??! (i mean the flexible cache file)

**Comment by mra-dev** [comment]
And, yes. sorry for double message bug i have.
I checked it in normal circumstances (so raw) in a queue job. (it works like your tests)
This thing happens when using "rememberForever" & "forget" together in long running processes (Queues) + using Events in conjunction with it.

**Comment by mra-dev** [comment]
They key thing i remembered to point out:
Even cache folders permissions were right: 755
and then i saw a 2 prefixed for "/storage" folder; like: 2755

**Comment by mra-dev** [comment]
I tried to replicate this in a similar situation.
But it seems this happens in certain scenarios. (Fibers in Foreach & vice versa)
Can't we just put and ENV key to indicate if it should delete "flexible" keys too and set false by default. (It's not a good idea to just downgrade to not having this weird BUG)

**Comment by mra-dev** [comment]
@timacdonald

**Comment by timacdonald** [comment]
Can you please confirm the change made here fixes your problem?

I have no way to confirm my fix even works.

https://github.com/laravel/framework/pull/53018/files#diff-4a1de3db154fb3881008aacba13f82699df89754a68b9d913077177d36821f63

**Comment by mra-dev** [comment]
@timacdonald I'm gonna check it right away. and shoot a video for it.

**Comment by mra-dev** [comment]
✅ I'm confirming that this is the solution. 
😍 Everything's working as before and expected.
thanks @timacdonald 

P.S: I tested it by manually changing code in `/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php`

```
// From this: 

public function forget($key)
{
    if ($this->files->exists($file = $this->path($key))) {
        $this->files->delete($this->path("illuminate:cache:flexible:created:{$key}"));

        return $this->files->delete($file);
    }

    return false;
}
```

```
// To this:

public function forget($key)
{
    if ($this->files->exists($file = $this->path("illuminate:cache:flexible:created:{$key}"))) {
        $this->files->delete($file);
    }
    
    if ($this->files->exists($file = $this->path($key))) {
        return $this->files->delete($file);
    }

    return false;
}
```

**Comment by mra-dev** [comment]
BTW; @timacdonald Do you think using `declare(strict_types=1);` would cause the errors to pop, even when using `@unlink()` ?!

**Comment by timacdonald** [comment]
Are you modifying the files in `vendor/laravel/framework` to apply `declare(strict_types=1);`?


That flag only applies only to the files it is within.

**Comment by mra-dev** [comment]
> Are you modifying the files in `vendor/laravel/framework` to apply `declare(strict_types=1);`?
@timacdonald 
No No. I just wanted to fill all the blank holes with information.
I just applied the part you specifically said. (one comment above)
And boom; Everything went back to normal.

**Comment by mra-dev** [comment]
@timacdonald Should I create an issue for this, or has it already been fixed?

**Comment by timacdonald** [comment]
I'll fix this in https://github.com/laravel/framework/pull/53018. Will have it opened today.
