### PR TITLE
[6.x] Fix Monolog v2 handler instantiation

### LINKED ISSUE #30026: [6.0] Monolog Channel can't use NullHandler in Monolog 2.0
- Laravel Version: 6.0.3
- PHP Version: 7.3

### Description:
I used [Monolog Channe](https://readouble.com/laravel/6.0/en/logging.html)l with [NullHandler](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/NullHandler.php) on Laravel 5.8. It is worked fine.
But Laravel 6.0 throw following exception.

```
[2019-09-18 09:59:05] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (Error(code: 0): Call to undefined method Monolog\\Handler\\NullHandler::setFormatter() at /vagrant/server/vendor/laravel/framework/src/Illuminate/Log/LogManager.php:376)
[stacktrace]
#0 /vagrant/server/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(347): Illuminate\\Log\\LogManager->prepareHandler(Object(Monolog\\Handler\\NullHandler), Array)
#1 /vagrant/server/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(185): Illuminate\\Log\\LogManager->createMonologDriver(Array)
```

I guess it is Monolog 1.x -> 2.0 compatibility problem.
Laravel 6.0 newly depend on Monolog 2.0 instead 1.x.

`Illuminate/Log/LogManager.php` use [`Monolog\Handler\HandlerInterface`](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/HandlerInterface.php).
The interface has `setFormatter()` in Monolog 1.x ([old](https://github.com/Seldaek/monolog/blob/1.x/src/Monolog/Handler/HandlerInterface.php)).
However In Monolog 2.0, `setFormatter()` moved to [`Monolog\Handler\FormattableHandlerInterface`](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/FormattableHandlerInterface.php).
LogManager must check `FormattableHandlerInterface` before call `setFormatter()` if there are Monolog 2.0.

### Steps To Reproduce:
My `config/logging.php` is following.
```
'fluent' => [
    'driver'  => 'monolog',
    'level' => 'info',
    'handler' => env('FLUENTD_ENABLE', true) ? App\Logging\FluentdHandler::class : Monolog\Handler\NullHandler::class,
],
```

### PR DESCRIPTION
**Pull request by X-Coder264**
Monolog 1 has the `setFormatter` method on the [HandlerInterface](https://github.com/Seldaek/monolog/blob/1.x/src/Monolog/Handler/HandlerInterface.php#L82) while Monolog 2 extracted that method from the `HandlerInterface` to a [FormattableHandlerInterface](https://github.com/Seldaek/monolog/blob/2.0.0/src/Monolog/Handler/FormattableHandlerInterface.php). This now means that a bunch of handlers in Monolog 2 don't have that method aka they are not formattable. The problem is that Laravel is calling the `setFormatter` method without checking if it actually exists on the handler when using Monolog 2 which causes an exception to be thrown.

This PR fixes the problem by checking for the `FormattableHandlerInterface` if Monolog 2 is being used. A test has also been added which tests the instantiation of a logger which has the `NullHandler` handler which is no longer formattable in Monolog 2. This test will be run with Monolog 1 in the CI with the low deps option and with Monolog 2 in the newest deps pipeline so it confirms that the instantiation now works with both Monolog versions. This test of course doesn't pass without the fix in this PR.

Fixes #30026

### CODE REVIEW

File: src/Illuminate/Log/LogManager.php [hunk 1]
```diff
@@ -372,9 +373,17 @@ protected function prepareHandlers(array $handlers)
...
+        if (Monolog::API === 1) {
+            $isHandlerFormattable = true;
+        } elseif (Monolog::API === 2 && $handler instanceof FormattableHandlerInterface) {
+            $isHandlerFormattable = true;
+        }
+
+        if ($isHandlerFormattable && ! isset($config['formatter'])) {
             $handler->setFormatter($this->formatter());
-        } elseif ($config['formatter'] !== 'default') {
+        } elseif ($isHandlerFormattable && $config['formatter'] !== 'default') {
```
Comment (driesvints) [inline src/Illuminate/Log/LogManager.php]: Can't we just check for the `FormattableHandlerInterface` instance everywhere instead of tall the extra if statements and `$isHandlerFormattable` variable?

Comment (driesvints) [reply src/Illuminate/Log/LogManager.php]:
```suggestion
        } elseif ($handler instanceof FormattableHandlerInterface && $config['formatter'] !== 'default') {
```

Comment (X-Coder264) [reply src/Illuminate/Log/LogManager.php]: @driesvints 

> elseif ($handler instanceof FormattableHandlerInterface && $config['formatter'] !== 'default')

This would always return `false` on Monolog 1 as the `FormattableHandlerInterface` doesn't exist on Monolog 1.

Comment (driesvints) [reply src/Illuminate/Log/LogManager.php]: Ah gotcha. nvm

**Review by driesvints — APPROVED** [review]
