### PR TITLE
[7.x] Fix a bug with slash prefix

### LINKED ISSUE #31759: Route prefix get truncated when using ->prefix('/') fluent routing registration
- Laravel Version: 7.0.4
- PHP Version: 7.4.3
- Database Driver & Version: N/A

### Description:

Certain fluent route registration will truncate the first URL prefix, this issue has been reported in:

* https://github.com/laravel/framework/issues/31732#issuecomment-594904074
* https://github.com/laravel/nova-issues/issues/2410#issuecomment-595142222

### Steps To Reproduce:

Create a new project

```
composer create-project laravel/laravel sandbox
```

Delete the content of `routes/api.php` since you can't cache closure based route.

Then update the default `routes/web.php` from 

```php
Route::get('/', function () {
    return view('welcome');
});
```

to

```php
Route::middleware(['web'])
    ->domain(null)
    ->name('web.')
    ->prefix('/')
    ->group(function ($router) {
        $router->view('welcome/user', 'welcome');
    });
```

Screenshot 2020-03-05 at 8 16 12 PM

Excepted to received `/welcome/user` but gotten `/user`

### PR DESCRIPTION
**Pull request by driesvints**
Fixes an issue where the prefix could be a slash. Can maybe use some polishing.

```
Route::prefix('/')->group(function ($router) {
    $router->view('welcome/user', 'welcome');
});
```

Fixes https://github.com/laravel/framework/issues/31759

### CODE REVIEW

**Comment by crynobone** [comment]
@driesvints tested locally 👍

File: src/Illuminate/Routing/CompiledRouteCollection.php [hunk 1]
```diff
@@ -229,10 +229,13 @@ protected function newRoute(array $attributes)
...
             $baseUri = $attributes['uri'];
         } else {
+            $prefixParts = trim($attributes['action']['prefix'], '/');
+            $prefixParts = $prefixParts !== '' ? explode('/', $prefixParts) : [];
+
             $baseUri = trim(implode(
                 '/', array_slice(
                     explode('/', trim($attributes['uri'], '/')),
-                    count(explode('/', trim($attributes['action']['prefix'], '/')))
+                    count($prefixParts)
```
Comment (crynobone) [inline src/Illuminate/Routing/CompiledRouteCollection.php]:
```suggestion
                    count($prefixParts !== '' ? explode('/', $prefixParts) : [])
```

File: src/Illuminate/Routing/CompiledRouteCollection.php [hunk 2]
```diff
@@ -229,10 +229,13 @@ protected function newRoute(array $attributes)
         if (empty($attributes['action']['prefix'] ?? '')) {
             $baseUri = $attributes['uri'];
         } else {
+            $prefixParts = trim($attributes['action']['prefix'], '/');
+            $prefixParts = $prefixParts !== '' ? explode('/', $prefixParts) : [];
```
Comment (crynobone) [inline src/Illuminate/Routing/CompiledRouteCollection.php]:
```suggestion
            $prefixParts = trim($attributes['action']['prefix'], '/');
```

File: src/Illuminate/Routing/CompiledRouteCollection.php (hunk 1 above)
Comment (crynobone) [reply src/Illuminate/Routing/CompiledRouteCollection.php]: `$prefixParts` is not used anywhere else. I would think this is good enough.

Comment (driesvints) [reply src/Illuminate/Routing/CompiledRouteCollection.php]: Done. Thanks.

File: src/Illuminate/Routing/CompiledRouteCollection.php (hunk 2 above)
Comment (driesvints) [reply src/Illuminate/Routing/CompiledRouteCollection.php]: Done. Thanks.
