### PR TITLE
[11.x] Use `null` as default cursor value for PHP Redis

### LINKED ISSUE #53087: Issues with latest phpredis breaking RedisTaggedCache
### Laravel Version

11.9

### PHP Version

Docker/Linux php:8.3.7-fpm-bookworm

### Database Driver & Version

N/A

### Description

OS: Docker / Linux
PHP: 8.3.7
Laravel: 11.9
Redis server: 7.4
phpredis: 6.1.0

The latest version of phpredis (6.1.0) has been changed to use an unsigned 64-bit cursor.
See https://github.com/phpredis/phpredis/pull/2458 and https://github.com/phpredis/phpredis/pull/2462.

There is a bug report here https://github.com/phpredis/phpredis/issues/2562, but this is intended behaviour going forward.

This means it breaks tagged caching on redis.

This is the line causing the issue with the latest version of the extension: https://github.com/laravel/framework/blob/master/src/Illuminate/Cache/RedisStore.php#L298

### Steps To Reproduce

To recreate I did `composer create-project laravel/laravel:^11 .` in a new directory. Then I added a docker-compose.yml and Dockerfile to it along with some examples in `routes/web.php`.

The problem is shown in this repo: https://github.com/scottasmith/laravel-phpredis-problems

If you clone it, run `docker compose up -d` and navigate to the urls in https://github.com/scottasmith/laravel-phpredis-problems/blob/main/routes/web.php.

- `http://localhost/not-working` shows phpredis and how laravel currently works
- `http://localhost/working` shows phpredis and how laravel should work (with this version)
- `http://localhost/laravel-failing` demonstrates that the flush isn't working
- `http://localhost/laravel-entries` shows its not getting the entries for the flush

### PR DESCRIPTION
**Pull request by jayan-blutui**
Fixes #53087

Additional context: https://github.com/phpredis/phpredis/issues/2562

This PR attempts to fix the current issue with the changes made in PHP Redis 6.1.0 where the default cursor value of `'0'` is handled differently. With some testing, setting this to `null` fixes this issue.

I have attempted to only make its fix available to PHP Redis and continue to use the previous value of `'0'` for PRedis. If this change isn't as per the framework's standard. Happy to make changes or totally understand if this is closed. 😄

### CODE REVIEW

**Comment by jayan-blutui** [comment]
Not sure why the Windows builds failed here at the setup PHP step 🤔

Perhaps it needs to be re-run?

File: src/Illuminate/Cache/RedisTagSet.php [hunk 1]
```diff
@@ -35,12 +36,19 @@ public function addEntry(string $key, ?int $ttl = null, $updateWhen = null)
      */
     public function entries()
     {
-        return LazyCollection::make(function () {
+        $connection = $this->store->connection();
+
+        $defaultCursorValue = match (true) {
+            $connection instanceof PhpRedisConnection => null,
```
Comment (scottasmith) [inline src/Illuminate/Cache/RedisTagSet.php:42]: As above

File: src/Illuminate/Cache/RedisStore.php [hunk 2]
```diff
@@ -292,10 +292,15 @@ protected function currentTags($chunkSize = 1000)
             default => '',
         };
 
+        $defaultCursorValue = match (true) {
+            $connection instanceof PhpRedisConnection => null,
```
Comment (scottasmith) [inline src/Illuminate/Cache/RedisStore.php:296]: This probably should also do a version check as well as checking its PhpRedisConnection. That way it doesn't bread it for people who have help back on upgrading the extension
```
if (version_compare(phpversion('redis'), '6.1.0', '>=')) {
    ...
}
```

Comment (jayan-blutui) [reply src/Illuminate/Cache/RedisStore.php:296]: That's a good idea. How about I do something like:

```php
$defaultCursorValue = match (true) {
    $connection instanceof PhpRedisConnection && version_compare(phpversion('redis'), '6.1.0', '>=') => null,
    default => '0',
};
```

Comment (scottasmith) [reply src/Illuminate/Cache/RedisStore.php]: I'm not a maintainer, but for me this would work 😄

**Comment by inserve-paul** [comment]
@taylorotwell @jayan-blutui @scottasmith Could this issue also be backported to Laravel 10.x ? We're still running Laravel 10.x and are running into the same issue with Redis.
