### PR TITLE
[5.1] Fix some valdiation rules

### LINKED ISSUE #9438: False positive in 'confirmed' rule
Password confirmation is working really well, except when I introduce this combination (I only use it locally to do some tests).

Password 1: 000000
Password 2: 00000 / 0000000000 (or other different amount of zeros)

Although, it is not an important mistake, it should be fixed.

I have noticed the method **validateSame** in **Illuminate\Validation\Validator** uses double equals and I think it should be change to triple equals, due to both should already be of the same type apart from the same value.

        return isset($other) && $value === $other;

### PR DESCRIPTION
**Pull request by arrilot**
PHP  type juggling strikes again.

Closes #9438

### CODE REVIEW

File: src/Illuminate/Validation/Validator.php [hunk 1]
```diff
@@ -747,7 +747,7 @@ protected function validateDifferent($attribute, $value, $parameters)
 
         $other = Arr::get($this->data, $parameters[0]);
 
-        return isset($other) && $value != $other;
+        return isset($other) && $value !== $other;
```
Comment (GrahamCampbell) [inline src/Illuminate/Validation/Validator.php]: This one doesn't need changing.

Comment (GrahamCampbell) [inline src/Illuminate/Validation/Validator.php]: Infact, it's wrong to change it.

Comment (Arrilot) [inline src/Illuminate/Validation/Validator.php]: Imagine we have a form with a couple of `<input type="text">`, for names e.g.
We type "100" in the first one and "1e2" in the second one. 
Why should `different` rule fail in this case?

Could you provide an example where strict check is wrong?

Comment (davex69) [inline src/Illuminate/Validation/Validator.php]: @GrahamCampbell, check this out https://blog.whitehatsec.com/magic-hashes/

Comment (taylorotwell) [inline src/Illuminate/Validation/Validator.php]: I agree we probably can't change this right now, as its a breaking change and would cause things like "0" against 0 to fail.

Comment (Arrilot) [inline src/Illuminate/Validation/Validator.php]: Are you strongly against or should I resend this to 5.2?

To my mind the fact that you can confirm your "1000" password with "1e3" is pretty meh.

Comment (taylorotwell) [inline src/Illuminate/Validation/Validator.php]: I guess this probably makes sense. You wouldn't really compare a string vs
an integer I don't think.

Comment (RomainLanz) [inline src/Illuminate/Validation/Validator.php]: Maybe cast both variable to string?

**Comment by franzliedke** [comment]
@Arrilot Please send a PR to `master` then. :)
This needs to be fixed!

**Comment by taylorotwell** [comment]
I'm gonna go ahead and merge this on 5.1... I think it's unlikely to cause any major problems.
