### PR TITLE
[5.7] Bug Fix: Allow Null Broadcast Connection Driver

### LINKED ISSUE #27132: Unable to Use "Null" Broadcast Driver
- Laravel Version: 5.7.20
- PHP Version: 7.3
- Database Driver & Version: N/A

### Description:

"Null" is described in the documentation as a valid broadcast driver. However, setting `BROADCAST_DRIVER` to be `null`, "null", or empty does not actually select the null driver. Essentially, this is a repeat of https://github.com/laravel/framework/issues/11051 in a new context.

### Steps To Reproduce:

1. Uncomment `App\Providers\BroadcastServiceProvider::class,` in `config/app.php`.
2. Set `BROADCAST_DRIVER=null` in `.env`.
3. Attempt to load a page to trigger an error.

### PR DESCRIPTION
**Pull request by ahinkle**
Fixes #27132 

via Docs:

> Additionally, a  null driver is included which allows you to totally disable broadcasting

However, `BROADCAST_DRIVER=null` returns `Broadcaster [] is not defined.` within app.

This PR will allow a `null` Broadcast Driver to be disabled within the app.

### CODE REVIEW

File: src/Illuminate/Broadcasting/BroadcastManager.php [hunk 1]
```diff
@@ -269,7 +265,11 @@ protected function createNullDriver(array $config)
      */
     protected function getConfig($name)
     {
-        return $this->app['config']["broadcasting.connections.{$name}"];
+        if (! is_null($name) && $name !== 'null') {
```
Comment (mfn) [inline src/Illuminate/Broadcasting/BroadcastManager.php]: > BROADCAST_DRIVER=null

Can you explain why the special case needs to be done in the `$name` ? Thanks
