### PR TITLE
[5.1] Be super careful making sure the csrf tokens are strings

### LINKED ISSUE #11124: Array to string conversion when _token is array
When I submit form with *_token* variable as array:

```html
<form>
<input name="_token[]" value="..." type="hidden">
.....
</form>
```

 I get:

```
ErrorException in Str.php line 296: Array to string conversion
```

Stacktrace:

```php
....
Str::equals(string, array) in VerifyCsrfToken.php line 87
VerifyCsrfToken->tokensMatch(object(Request)) in VerifyCsrfToken.php line 49
VerifyCsrfToken->handle(object(Request), object(Closure))
...
```

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Closes #11124.

### CODE REVIEW

**Comment by taylorotwell** [comment]
I would move that check up to right after you assign the variables in the method.

**Comment by GrahamCampbell** [comment]
We can't because token is reasigned later so needs checking again. This is the earliest point, we can check really.

File: src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php [hunk 1]
```diff
@@ -82,13 +82,19 @@ protected function shouldPassThrough($request)
      */
     protected function tokensMatch($request)
     {
+        $sessionToken = $request->session()->token();
+
         $token = $request->input('_token') ?: $request->header('X-CSRF-TOKEN');
 
         if (! $token && $header = $request->header('X-XSRF-TOKEN')) {
             $token = $this->encrypter->decrypt($header);
```
Comment (GrahamCampbell) [inline src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php]: see here, we're assigning again
