### PR TITLE
[5.5] Update docblock render() method to return a string, rather than View

### LINKED ISSUE #22633: Incorrect return type on Mailer & Mailable
- Laravel Version: 5.5

### Description:

The following mismatch between actual implementation and docblock came up in [StackOverflow question #48096964](https://stackoverflow.com/questions/48096783/how-can-i-render-laravel-mailable-to-variable/48096964)

The [docblock on Mailable::render()](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Mail/Mailable.php#L170) says it returns an `\Illuminate\View\View`. Same for the underlying [Mailer::render()](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Mail/Mailer.php#L180) that's being called and which return value is passed on. In actuality a string is being returned from [Mailer::renderView()](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Mail/Mailer.php#L322-L324).

### Steps To Reproduce:

Create an object that extends Mailable and call `render()` on it.
Expected outcome (as per docblock): Method returns a View-object
Actual outcome: Method returns a string

### PR DESCRIPTION
**Pull request by kevinruscoe**
Update docblock, fixes #22633

### CODE REVIEW

File: src/Illuminate/Mail/Mailer.php [hunk 1]
```diff
@@ -177,7 +177,7 @@ public function plain($view, array $data, $callback)
      *
      * @param  string|array  $view
      * @param  array  $data
-     * @return \Illuminate\View\View
+     * @return string
```
Comment (GrahamCampbell) [inline src/Illuminate/Mail/Mailer.php]: Please update the contracts too if needed.
