### PR TITLE
[5.0] Add reset method to migrator to fix infinite loop.

### LINKED ISSUE #8262: Calling migrate:reset --pretend wil cause Infinite Loop
Hi !

I discovered a weird issue today, not sure if it's from me or Laravel but
when i'm calling 

```
$> php artisan migrate:reset --pretend
```

That causes an infinite loop.

Please get back to me if you have more infos !

PS: Sorry for my english, not my native language.

EDIT: I tried from a fresh install with the two default migrations (users and reset_password), infinite loop too.

### PR DESCRIPTION
**Pull request by willrowe**
This adds a `reset` method to the `Migrator` class in order to fix #8262 and move some migration logic out of the console command. Everything else still functions as before, but it is now possible to call `migrate:reset` with the `--pretend` option without it going into an infinite loop.
The tests associated with the console command were altered accordingly and new test were added for the `reset` method. Moving the logic into a new method also removed the reliance on a `while(true)` loop which wasn't easily testable.

### CODE REVIEW

**Comment by willrowe** [comment]
I'm aware of the issues, working on it now...

**Comment by willrowe** [comment]
Should be good to go now.

File: src/Illuminate/Database/Migrations/Migrator.php [hunk 1]
```diff
@@ -176,6 +176,33 @@ public function rollback($pretend = false)
 	}
 
 	/**
+	 * Rolls all of the currently applied migrations back.
+	 *
+	 * @param  bool  $pretend
+	 * @return in
```
Comment (taiyaei) [inline src/Illuminate/Database/Migrations/Migrator.php]: `int`

Comment (willrowe) [inline src/Illuminate/Database/Migrations/Migrator.php]: Oops thanks for pointing that out.
