### PR TITLE
[12.x] Preserve numeric keys on the first level of the validator rules

### LINKED ISSUE #51499: Rules with numeric keys do not validate properly
### Laravel Version

10.48.10

### PHP Version

8.3

### Database Driver & Version

_No response_

### Description

Numeric rules (Eg: `[4 => 'required', 8 => 'required']`) when added to a validator are not saved properly, they are transformed into`[0 => 'required', 1 => 'required']` in the constructor

I tracked it down to this line
https://github.com/laravel/framework/blob/bf7046f37a03ac006f60a811148f91393f305283/src/Illuminate/Validation/Validator.php#L1208-L1210

It seems the array merge recursive treats any numeric key differently and just appends it to the array instead of preserving the keys, this is explained in the php doc, but undesirable behavior in this case https://www.php.net/manual/en/function.array-merge-recursive.php

```php
array_merge_recursive([], ['foo' => 'required', 4 => 'required', 8 => 'required']);
= [
    "foo" => "required",
    0 => "required",
    1 => "required",
  ]
```

### Steps To Reproduce

Running the following in a tinker session is enough to reproduce
```php
Validator::validate(['foo' => 'baz', 4 => 'foo', 8 => 'baz'], ['foo' => 'required', 4 => 'required', 8 => 'required']);
```

Results in
```
   Illuminate\Validation\ValidationException  The 0 field is required. (and 1 more error).
```

A possible solution is a different implementation of the `array_merge_recursive` as seen here https://www.php.net/manual/en/function.array-merge-recursive.php#106985

Prior attempt at a fix https://github.com/laravel/framework/pull/39368

### PR DESCRIPTION
**Pull request by Tofandel**
Fixes #51499 without changing the merge behavior (see `testMergeRules` in the PR that #39368 wouldn't have passed), simply preserve all the keys passed to the validator rules

### Bug description

Running the following in a tinker session
```php
Validator::validate(['foo' => 'baz', 4 => 'foo', 8 => 'baz'], ['foo' => 'required', 4 => 'required', 8 => 'required']);
```

Results in
```
   Illuminate\Validation\ValidationException  The 0 field is required. (and 1 more error).
```

Because array_merge_recursive rekeys any numeric keys it encounters
```php
array_merge_recursive([], ['foo' => 'required', 4 => 'required', 8 => 'required']);
= [
    "foo" => "required",
    0 => "required",
    1 => "required",
  ]
```

### CODE REVIEW

File: src/Illuminate/Validation/Validator.php [hunk 1]
```diff
@@ -1205,9 +1205,9 @@ public function addRules($rules)
         $response = (new ValidationRuleParser($this->data))
                             ->explode(ValidationRuleParser::filterConditionalRules($rules, $this->data));
 
-        $this->rules = array_merge_recursive(
-            $this->rules, $response->rules
-        );
+        foreach ($response->rules as $key => $rule) {
+            $this->rules[$key] = array_merge_recursive($this->rules[$key] ?? [], $rule);
```
Comment (Tofandel) [inline src/Illuminate/Validation/Validator.php:1209]: We only need `array_merge`, given that rules are always nested only 2 levels deep and are always associative arrays (Asserted by the `ValidationRuleParser`)

File: src/Illuminate/Validation/Validator.php [hunk 2]
```diff
@@ -1205,9 +1205,9 @@ public function addRules($rules)
         $response = (new ValidationRuleParser($this->data))
                             ->explode(ValidationRuleParser::filterConditionalRules($rules, $this->data));
 
-        $this->rules = array_merge_recursive(
-            $this->rules, $response->rules
-        );
+        foreach ($response->rules as $key => $rule) {
+            $this->rules[$key] = array_merge($this->rules[$key] ?? [], $rule);
```
Comment (Tofandel) [inline src/Illuminate/Validation/Validator.php:1209]: We only need array_merge, given that rules are always nested only 2 levels deep and are always associative arrays (Asserted by the ValidationRuleParser)

**Comment by taylorotwell** [comment]
Any reason this was sent to master vs. 11.x?

**Comment by driesvints** [comment]
@taylorotwell as we suspected in the past this might be a breaking change: https://github.com/laravel/framework/pull/39368
