### PR TITLE
[12.x] Ensure related models is iterable on `HasRelationships@relationLoaded()`

### LINKED ISSUE #55518: Update to `relationLoaded()` causes problems when accessing attributes on a model containing a period
### Laravel Version

12.10.0

### PHP Version

8.3

### Database Driver & Version

_No response_

### Description

#55471 introduces a problem when attempting to access attributes on a model that contain a `.`. The framework calls the `relationLoaded()` method, which was updated to handle `.` as nested relationships in that PR.

Here is the link to the line that calls the method: https://github.com/laravel/framework/blob/3faeb0726cb55b4f672bf549cc93b716545b84c2/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L485

Here is a related test failure:
https://github.com/filamentphp/filament/actions/runs/14589554182/job/40966543141

### Steps To Reproduce

https://github.com/danharrin/laravel-relation-loaded-bug-report/commit/f29cef4eab3f50bc5e359da1019a93bf10434834

### PR DESCRIPTION
**Pull request by rodrigopedra**
Closes #55518

PR #55471 introduced changes to the `HasRelationships@relationLoaded()` to improve performance.

It introduced an oversight when loading nesting relations assuming all relations would return am iterable (e.g. `Collection`). That is the case for some relations, such as `HasMany`.

But not the case for relations such as `BelongsTo`, `HasOne`, `MorphOne`, which return a single model.

So when iterating one of these relations, the `foreach` works iterating through the `Model` instance public properties such as `incrementing`, `exists`, ...

This PR:

- Ensure the relation is iterable before iterating the affected `foreach`
- Add a test case

### CODE REVIEW

**Comment by danharrin** [comment]
This does solve #55518, but personally I think you should add a new test case to ensure that this doesn't regress

**Comment by rodrigopedra** [comment]
@danharrin thanks for reviewing it.

I just added a test case

File: src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php [hunk 1]
```diff
@@ -1086,7 +1086,11 @@ public function relationLoaded($key)
         }
 
         if ($nestedRelation !== null) {
-            foreach ($this->$relation as $related) {
+            $relatedModels = is_iterable($relatedModels = $this->$relation)
```
Comment (shaedrich) [inline src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php:1089]: Wouldn't it be more intuitive to narrow this down a little further?
```suggestion
            $relatedModels = ($relatedModels = $this->$relation) instanceof Collection
```
_(not sure about the `$relatedModels = ($relatedModels = ` though 🤔)_
or
```suggestion
            $relationship = $this->$relation();
            $relatedModels = $this->$relation;
            $relatedModels = ($relationship instanceof HasMany || $relationship instanceof BelongsToMany || $relationship instanceof HasManyThrough || $relationship instanceof MorphMany || $relationship instanceof MorphToMany)
```
_(There might be an Interface for `ManyToManyRelation` 🤔😅)_

Comment (rodrigopedra) [reply src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php:1089]: The assignment within parenthesis in `$relatedModels = is_iterable($relatedModels = $this->$relation) ? ... : ...`, is to avoid calling `$this->$relation` twice, and to prevent unnecessary calls to the rather expensive `Model@getAttribute()` method.

The choice for `is_iterable()` instead of checking for an instance of `Eloquent\Collection` or a `Relation` subclass, was due to users being able to set relations manually with the `Model@setRelation()` method, which accepts `mixed` as its value:

https://github.com/laravel/framework/blob/3faeb0726cb55b4f672bf549cc93b716545b84c2/src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php#L1099-L1106

There are some 3rd-party eloquent extensions out there (more famously the MongoDB one), and I can't assume all of them behave as the built-in ones. 

Note: I am not saying the MongoDB one, specifically, sets a non-collection manually with `Model@setRelation()`. I just used it as a known example of a 3rd-party Eloquent extension.

Comment (shaedrich) [reply src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php:1089]: > The assignment within parenthesis in `$relatedModels = is_iterable($relatedModels = $this->$relation) ? ... : ...`, is to avoid calling `$this->$relation` twice, and to prevent unnecessary calls to the rather expensive `Model@getAttribute()` method.

That makes sense. I just would have named that differently than the final variable.

File: src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php [hunk 2]
```diff
@@ -1086,7 +1086,11 @@ public function relationLoaded($key)
...
+                ? $relatedModels
+                : [$relatedModels];
+
+            foreach ($relatedModels as $related) {
                 if (! $related->relationLoaded($nestedRelation)) {
```
Comment (nicekiwi) [inline src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php:1094]: @rodrigopedra if one of the relations is not loaded, or does not exist, `$relatedModels` can be `[null]` leading to `Error: Call to a member function relationLoaded() on null`

Comment (rodrigopedra) [reply src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php:1094]: You are right, thanks for the heads-up, I will send a new PR addressing this case.

Comment (rodrigopedra) [reply src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php:1094]: @nicekiwi sent PR #55531 thanks again!
