### PR TITLE
[12.x] Fix Accept header cache invalidation when header is modified

### LINKED ISSUE #57868: Request wantsJson operates on cached acceptableContentTypes
### Laravel Version

12.39.0

### PHP Version

8.4.14

### Database Driver & Version

_No response_

### Description

`Request::wantsJson` uses Symfony's `getAcceptableContentTypes` internally which caches the headers so this doesn't work in a middleware:

```php
if ($request->acceptsAnyContentType()) {
    $request->headers->set('Accept', 'application/json');
}

if (!$request->wantsJson()) {
    return response()->json(['message' => 'Not Acceptable.'], 406);
}

return $next($request);
```

There is also no way to trigger a reset of `acceptableContentTypes`.

### Steps To Reproduce

Have the following code in a middleware:

```php
if ($request->acceptsAnyContentType()) {
    $request->headers->set('Accept', 'application/json');
}

dd($request->wantsJson());
```

Call an endpoint with `Accept` set to `*/*`.

### PR DESCRIPTION
**Pull request by faisuc**
When modifying the Accept header in middleware using `$request->headers->set('Accept', 'application/json')`, methods like `wantsJson()`, `acceptsJson()`, and `prefers()` would return stale values because Symfony's `getAcceptableContentTypes()` caches the result and doesn't clear it when headers are changed.

This caused issues in middleware scenarios like:

```php
if ($request->acceptsAnyContentType()) {
    $request->headers->set('Accept', 'application/json');
}
if (!$request->wantsJson()) {
    return response()->json(['message' => 'Not Acceptable.'], 406);
}
```

Even after setting the Accept header to `application/json`, `wantsJson()` would still return `false` because it was using the cached value from before the header change.

Fixes: https://github.com/laravel/framework/issues/57868

### CODE REVIEW

File: src/Illuminate/Http/Request.php [hunk 1]
```diff
@@ -812,4 +819,23 @@ public function __get($key)
...
+    #[\Override]
+    public function getAcceptableContentTypes(): array
+    {
+        $currentAcceptHeader = $this->headers->get('Accept');
+
+        if ($this->cachedAcceptHeader !== $currentAcceptHeader) {
+            $this->acceptableContentTypes = null;
+        }
+
+        $this->cachedAcceptHeader = $currentAcceptHeader;
```
Comment (rodrigopedra) [inline src/Illuminate/Http/Request.php]: I think this statement can be moved into the `if` block so the assignment only happens when needed.

Comment (faisuc) [reply src/Illuminate/Http/Request.php]: PR updated. Thanks for the review! :)
