### PR TITLE
[9.x] Fix MySqlSchemaState does not add --ssl-ca to mysql cli 

### LINKED ISSUE #41300: ERROR 2026 (HY000): SSL connection error: SSL_CTX_set_default_verify_paths failed
### Discussed in https://github.com/laravel/framework/discussions/41299

<div type='discussions-op-text'>

<sup>Originally posted by **Brenneisen** March  2, 2022</sup>

- Laravel Version: 9.3.0
- PHP Version: 8.1.1
- Database Driver & Version: 8.0.27

### Description:

I get an error when running `php artisan migrate`:

```
The command "mysql  --user="${:LARAVEL_LOAD_USER}" --password="${:LARAVEL_LOAD_PASSWORD}" --host="${:LARAVEL_LOAD_HOST}" --port="${:LARAVEL_LOAD_PORT}" --ssl-ca="${:LARAVEL_LOAD_SSL_CA}" --database="${:LARAVEL_LOAD_DATABASE}" < "${:LARAVEL_LOAD_PATH}"" failed.

Exit Code: 1(General error)

Output:
================

Error Output:
================
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 2026 (HY000): SSL connection error: SSL_CTX_set_default_verify_paths failed
```

### Steps To Reproduce:

Run `php artisan migrate`.
</div>

### PR DESCRIPTION
**Pull request by DeepDiver1975**
…gured

fixes #41300

### CODE REVIEW

File: src/Illuminate/Database/Schema/MySqlSchemaState.php [hunk 1]
```diff
@@ -103,9 +103,14 @@ protected function connectionString()
     {
         $value = ' --user="${:LARAVEL_LOAD_USER}" --password="${:LARAVEL_LOAD_PASSWORD}"';
 
-        $value .= $this->connection->getConfig()['unix_socket'] ?? false
+        $config = $this->connection->getConfig();
+        $value .= $config['unix_socket'] ?? false
                         ? ' --socket="${:LARAVEL_LOAD_SOCKET}"'
-                        : ' --host="${:LARAVEL_LOAD_HOST}" --port="${:LARAVEL_LOAD_PORT}" --ssl-ca="${:LARAVEL_LOAD_SSL_CA}"';
+                        : ' --host="${:LARAVEL_LOAD_HOST}" --port="${:LARAVEL_LOAD_PORT}""';
```
Comment (DeepDiver1975) [inline src/Illuminate/Database/Schema/MySqlSchemaState.php:109]: " is placed wrong .... will provide fix ...

**Comment by DeepDiver1975** [comment]
trying to add tests for this ....

**Comment by DeepDiver1975** [comment]
ready for review and make devs happy again ;-)
