### PR TITLE
[11.x] Fix `serve` command with `PHP_CLI_SERVER_WORKERS`

### LINKED ISSUE #54574: Env modification increments server port
As seen recenlty in that old issue : 

https://github.com/laravel/framework/issues/34121#issuecomment-2476881717

> This happend to me right now on lates Laravel and PHP installed from brave on mac.
> 
> 
> 
> 
> 
> ```
> 
>    INFO  Server running on [http://127.0.0.1:8000].  
> 
> 
> 
>   Press Ctrl+C to stop the server
> 
> 
> 
> 
> 
>    INFO  Environment modified. Restarting server...  
> 
> 
> 
>   Failed to listen on 127.0.0.1:8000 (reason: Address already in use)
> 
> 
> 
>    INFO  Server running on [http://127.0.0.1:8001].  
> 
> 
> 
>   Press Ctrl+C to stop the server
> 
> ```
> 
> 
> 
> And when i stop server using ctrl+c all process are stoped and when i start server again is on 8000 again... 

 _Originally posted by @gavalierm in [#34121](https://github.com/laravel/framework/issues/34121#issuecomment-2476881717)_

I am also encoutering that with that config: 

```
php -v
PHP 8.3.13 (cli) (built: Oct 22 2024 18:39:14) (NTS)

php artisan --version
Laravel Framework 11.42.0
macOS 15.3 (24D60)

```

### PR DESCRIPTION
**Pull request by crynobone**
By default, serve command would restart child process when there's modification to the `.env` file. However, with `PHP_CLI_SERVER_WORKERS` set to larger than 1 the process doesn't close properly (port is still being used) and this cause the restart process to pick an incremented port number.

The changes here will unset `PHP_CLI_SERVER_WORKERS` value unless the command is executed with `--no-reload` option.

fixes #54574

### CODE REVIEW

File: src/Illuminate/Foundation/Console/ServeCommand.php [hunk 1]
```diff
@@ -76,14 +78,33 @@ class ServeCommand extends Command
...
         'SYSTEMROOT',
         'XDEBUG_CONFIG',
         'XDEBUG_MODE',
         'XDEBUG_SESSION',
     ];
 
+    /**
+     * The number of PHP_CLI_SERVER_WORKERS.
+     *
+     * @var int|false
```
Comment (crynobone) [inline src/Illuminate/Foundation/Console/ServeCommand.php:91]:
```suggestion
     * @var int<2, max>|false
```

File: src/Illuminate/Foundation/Console/ServeCommand.php [hunk 2]
```diff
@@ -360,7 +381,7 @@ protected function flushOutputBuffer()
      */
     protected function getDateFromLine($line)
     {
-        $regex = ! windows_os() && env('PHP_CLI_SERVER_WORKERS', 1) > 1
+        $regex = ! windows_os() && $this->phpServerWorkers > 1
```
Comment (crynobone) [inline src/Illuminate/Foundation/Console/ServeCommand.php:384]:
```suggestion
        $regex = ! windows_os() && is_int($this->phpServerWorkers)
```

**Comment by BrainStone** [comment]
Hey there. Apologies for necroing this PR/thread.

However I do have a few questions regarding the changes made here. If this isn't the appropriate place to ask, I'm happy to ask where ever you recommend me to.

Now I am wondering why it has been chosen to silently ignore a configuration value under fairly intransparent conditions (I mean the code is clear, but to people not knowing this code, the conditions are very unclear) instead of addressing the underlying issue at hand.  
Is this an issue with the PHP development server? I've come across many comments and blurps that say something along the lines that the experimental support for `PHP_CLI_SERVER_WORKERS` in the built-in PHP development server either are or could be causing this issue where reloading doesn't free up the port, so the next instance gets a different port.

Additionally is there documentation for this behavior? I'm not saying there isn't any, just that I haven't come across any mention during my multi hour deep dive into why an update of Laravel suddenly caused timeouts in my dev server (which eventually lead me down the path of debugging why `PHP_CLI_SERVER_WORKERS` was getting ignored).
