### PR TITLE
[5.1] Fixes filesystem, mail, and queue AWS drivers' config

### LINKED ISSUE #9309: SqsConnector always creates 'key' and 'secret' array key configurations.
SqsConnector.php

Version 5.1.2
```
    public function connect(array $config)
    {
        $config += [
            'version' => 'latest',
            'credentials' => [
                'key'    => $config['key'],
                'secret' => $config['secret'],
            ],
        ];

        unset($config['key'], $config['secret']);

        return new SqsQueue(new SqsClient($config), $config['queue']);
    }
```
Version 5.0.*
```
	public function connect(array $config)
	{
		$sqs = SqsClient::factory($config);

		return new SqsQueue($sqs, $config['queue']);
	}
```
AWS SQS does not require key and secret keys to be set. In prior versions the SqsConnector worked with an IAM role on an EC2 instance simply by not setting a key and secret, with v5.1.2 this isn't the case. It always complains about a missing key and secret.

It's been a long day, I might be missing something. Can anyone with queue experience comment on this difference?

Thanks

### PR DESCRIPTION
**Pull request by jeremeamia**
Implicitly provided credentials (via environment variables or IAM instance profile credentials) are now read correctly when `key` and `secret` are not explicitly provided. This fixes #9309.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thank you for looking into this @jeremeamia. I'll let Talor know about this one. :)

File: src/Illuminate/Mail/TransportManager.php [hunk 1]
```diff
@@ -4,6 +4,7 @@
 
 use Aws\Ses\SesClient;
 use Illuminate\Support\Manager;
+use Illuminate\Support\Arr;
```
Comment (GrahamCampbell) [inline src/Illuminate/Mail/TransportManager.php]: Please sort imports by length.

File: src/Illuminate/Queue/Connectors/SqsConnector.php [hunk 2]
```diff
@@ -4,6 +4,7 @@
 
 use Aws\Sqs\SqsClient;
 use Illuminate\Queue\SqsQueue;
+use Illuminate\Support\Arr;
```
Comment (GrahamCampbell) [inline src/Illuminate/Queue/Connectors/SqsConnector.php]: same

File: src/Illuminate/Mail/TransportManager.php [hunk 3]
```diff
@@ -70,14 +71,13 @@ protected function createSesDriver()
 
         $config += [
             'version' => 'latest',
-            'service' => 'email',
-            'credentials' => [
-                'key'    => $config['key'],
-                'secret' => $config['secret'],
-            ],
+            'service' => 'email', // Fixes issue with SDK versions < 3.0.2
```
Comment (GrahamCampbell) [inline src/Illuminate/Mail/TransportManager.php]: Do we care about 3.0.0 and 3.0.1? I think we should just say we support `^3.0.2`?

Comment (GrahamCampbell) [inline src/Illuminate/Mail/TransportManager.php]: // cc @taylorotwell
