### PR TITLE
[7.x] Fix output of component attributes

### LINKED ISSUE #31939: Component attributes with boolean values are rendered differently when merge() is used
- Laravel Version: 7.0.8
- PHP Version: 7.2.26
- Database Driver & Version: n/a

### Description:

With a component that simply prints it's attributes:

```php
<input {{ $attributes }} />
```

If the component is used like this:

```php
<x-input :disabled="false" />
```

We would expect the rendered template to be:

```php
<input />
```

But the current implementation renders:

```php
<input disabled="" />
```

But if the component uses `merge()` like this:

```php
<input {{ $attributes->merge() }} />
```

The output is what one would expect:

```php
<input />
```

It's debatable how an attribute with a boolean value should be handled, but at least `$attribute` and `$attribute->merge()` should give identical output, right?

### PR DESCRIPTION
**Pull request by perifer**
Closes https://github.com/laravel/framework/issues/31939

This PR fixes multiple issues with how component attributes are rendered. `$attribute` and `$attributes->merge()` results in different rendered attributes for values that are `true` or casts to `false`. For example `min="0"` is currently removed when using merge() (see full example below).

Here is an attempt to summarise the changes. In short `$attribute` and `$attribute->merge()` now have identical output and are rendered the same way as Vue.

`<x-input :checked="false">`, `<x-input :checked="null">`, `<x-input :checked="">` → `<input>` 
Previously `<input checked="">`  and `<input>`

`<x-input :min="0">`, `<x-input :min="'0'">` → `<input min="0">` 
Previously `<input min="0">`  and `<input>`

`<x-input :checked="true">` → `<input checked="checked">` 
Previously `<input checked>`  and `<input checked="checked">`

This last example is handled a bit simpler than Vue. Vue differentiate boolean attributes (`checked`, `disabled`, `itemscope` etc) and normal attributes. This PR doesn't (but it could be added in another PR).

### An example where min="0" is removed when using merge()

A blade component with attributes:
```php
<input type="number" {{ $attributes }} />
```

For an input with type number it's reasonable to have min="0":
```php
<x-number min="0" max="10" class="p-4" />
```
This render as:
```html
<input type="number" min="0" max="10" class="p-4" />
```

But if you used `merge()`:
```php
<input type="number" {{ $attributes->merge(['class' => 'm-4']) }} />
```

The attribute with **value 0 is removed**:
```html
<input type="number" max="10" class="p-4 m-4" />
```

### Another example with an attribute with a value `false` that is rendered differently when using with or without merge()

With a component that simply prints it's attributes:

```php
<input {{ $attributes }} />
```

If the component is used like this:

```php
<x-input :disabled="false" />
```

We would expect the rendered template to be:

```php
<input />
```

But the current implementation renders:

```php
<input disabled="" />
```

But if the component uses `merge()` like this:

```php
<input {{ $attributes->merge() }} />
```

The output is what one would expect:

```php
<input />
```

### CODE REVIEW

File: tests/View/ViewComponentAttributeBagTest.php [hunk 1]
```diff
@@ -27,5 +27,18 @@ public function testAttributeRetrieval()
...
+            'test-null' => null,
+            'test-false' => false,
+            'test-true' => true,
+            'test-0' => 0,
+            'test-0-string' => '0',
+            'test-empty-string' => '',
+        ]);
+
+        $this->assertSame('test-string="ok" test-true="test-true" test-0="0" test-0-string="0" test-empty-string=""', (string) $bag);
+        $this->assertSame('test-string="ok" test-true="test-true" test-0="0" test-0-string="0" test-empty-string=""', (string) $bag);
```
Comment (taylorotwell) [inline tests/View/ViewComponentAttributeBagTest.php]: These two lines are exactly the same?

Comment (perifer) [reply tests/View/ViewComponentAttributeBagTest.php]: Good catch! Addes missing merge()
