### PR TITLE
[5.1] Add support for Validator::each() to be passed either array or string

### LINKED ISSUE #7145: Illuminate\Validation\Validator::each() doesn't support string rules (though documented)
https://github.com/laravel/framework/blob/4.2/src/Illuminate/Validation/Validator.php#L222

```php
	/**
	 * Define a set of rules that apply to each element in an array attribute.
	 *
	 * @param  string  $attribute
	 * @param  string|array  $rules
	 * @return void
	 *
	 * @throws \InvalidArgumentException
	 */
	public function each($attribute, $rules)
	{
		$data = array_get($this->data, $attribute);
		if ( ! is_array($data))
		{
			if ($this->hasRule($attribute, 'Array')) return;
			throw new \InvalidArgumentException('Attribute for each() must be an array.');
		}
		foreach ($data as $dataKey => $dataValue)
		{
			foreach ($rules as $ruleValue)
			{
				$this->mergeRules("$attribute.$dataKey", $ruleValue);
			}
		}
	}
```

Here ```$rules``` can be either string or an array. But if it is string, you must first run something like \Illuminate\Validation\Validator::explodeRules() on it.

### PR DESCRIPTION
**Pull request by FractalizeR**
`\Illuminate\Validation\Validator::each()` function documents `$rules` to be either array or string. But currently only array is supported. This PR fixes this behaviour. Fixes #7145.

```
    /**
     * Define a set of rules that apply to each element in an array attribute.
     *
     * @param  string  $attribute
     * @param  string|array  $rules
     * @return void
     *
     * @throws \InvalidArgumentException
     */
    public function each($attribute, $rules)
```

### CODE REVIEW

File: src/Illuminate/Validation/Validator.php [hunk 1]
```diff
@@ -268,6 +268,8 @@ public function each($attribute, $rules)
             throw new InvalidArgumentException('Attribute for each() must be an array.');
         }
 
+        $rules = is_array($rules) ? $rules : [$rules];
```
Comment (GrahamCampbell) [inline src/Illuminate/Validation/Validator.php]: Better just just put `(array) $rules` into the foreach and that's it.

**Comment by FractalizeR** [comment]
Done.

File: src/Illuminate/Validation/Validator.php [hunk 2]
```diff
@@ -269,7 +269,7 @@ public function each($attribute, $rules)
         }
 
         foreach ($data as $dataKey => $dataValue) {
-            foreach ($rules as $ruleKey => $ruleValue) {
+            foreach ((array)$rules as $ruleKey => $ruleValue) {
```
Comment (GrahamCampbell) [inline src/Illuminate/Validation/Validator.php]: Please put a space before the dollar like in my example.

**Comment by FractalizeR** [comment]
Done.

**Comment by lukasgeiter** [comment]
Please squash to one commit, thanks.
