### PR TITLE
[11.x] Fixes `Illuminate\Http\Response` to output empty string if `$content` is set to `null`

### LINKED ISSUE #972: sync_worker_exec_payload: TypeError: fwrite(): Argument #2 ($data) must be of type string, null given
### Octane Version

1.5.6

### Laravel Version

8.83.29

### PHP Version

8.1.3

### What server type are you using?

Roadrunner

### Server Version

2.12.3

### Database Driver & Version

_No response_

### Description

Just `response()->noContent()` I will get status 500, and worker stop.

`sync_worker_exec_payload: TypeError: fwrite(): Argument #2 ($data) must be of type string, null given in vendor/laminas/laminas-diactoros/src/Stream.php:234`

This is because the use of **`declare(strict_types=1);`** in `laminas/laminas-diactoros/src/Stream.php`

So `fwrite($stream, null)` throw error.

And In `symfony/http-foundation`

When the response status is 204, the content will be set to null..😭
```php

public function isEmpty(): bool
{
    // L1259
    return \in_array($this->statusCode, [204, 304]);
}


public function prepare(Request $request): static
{
    $headers = $this->headers;
  
    if ($this->isInformational() || $this->isEmpty()) {
        // L247
        $this->setContent(null);
   }
}
```

https://github.com/symfony/http-foundation/blob/7.2/Response.php#L1259

https://github.com/symfony/http-foundation/blob/7.2/Response.php#L247

### Steps To Reproduce

```php
class ExampleController extends Controller
{
    public function index()
    {
        return response()->noContent();
    }
}
```

### PR DESCRIPTION
**Pull request by crynobone**
1. Symfony set the content to `null` for `response()->noContent()` https://github.com/symfony/http-foundation/blob/e88a66c3997859532bc2ddd6dd8f35aba2711744/Response.php#L246-L249
2. This cause issue with PSR-7 HTTP Stream in Octane

fixed laravel/octane#972

### CODE REVIEW

File: src/Illuminate/Http/Response.php [hunk 1]
```diff
@@ -75,6 +75,15 @@ public function setContent(mixed $content): static
         return $this;
     }
 
+    /**
+     * Gets the current response content.
+     */
+    #[\Override]
+    public function getContent(): string|false
+    {
+        return transform(parent::getContent(), fn ($content) => $content, '');
```
Comment (rodrigopedra) [inline src/Illuminate/Http/Response.php:84]: Why not just?

```php
return parent::getContent() ?? '';
```

**Comment by rodrigopedra** [comment]
Also, for the same hash you linked the `$this->setContent(null);`, `setContent()` actually uses the null-coalescing operator to convert `null` to an empty string:

https://github.com/symfony/http-foundation/blob/e88a66c3997859532bc2ddd6dd8f35aba2711744/Response.php#L418-L423

Maybe the problem is something else?

**Comment by rodrigopedra** [comment]
Does octane calls `Illuminate\Http\ResponseTrait@getOriginalContent()`, the `Response::$original` property is stored unchanged, that might be the issue.

**Comment by crynobone** [comment]
I'm a little hesitant to follow Symfony style since their phpdoc indicate `string|null` while ours is `mixed`

Also with `mixed` we could potentially introduce breaking changes for application that expected that they can directly return null (maybe 🤔)

**Comment by rodrigopedra** [comment]
I agree, but our override at the end defers to theirs

From our current code `null` should end up being handled by `parent::setContent($content);` which already coalesces `null` to an empty string
