### PR TITLE
[5.5] Add precision to time

### LINKED ISSUE #21935: Blueprint Builder doesnt Support TIME(3) // Milliseconds
- Laravel Version: 5.5.*
- PHP Version:  7.1.9
- Database Driver & Version: ibmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: b396954eeb2d1d9ed7902b8bae237b287f21ad9e $ 

### Description:
The Laravel Blueprint table builder does not support `TIME(3)`. (More detailed version of time).

### Steps To Reproduce:
```php
        Schema::create('records', function (Blueprint $table) {
              $table->time('some_time', 3); // to include milliseconds
        });
```

I have to do:
```php
        DB::statement(
<<<'TAG'
ALTER TABLE records
MODIFY duration TIME(3);
TAG
        );
```

### PR DESCRIPTION
**Pull request by Dylan-DPC-zz**
fixes #21935

### CODE REVIEW

File: src/Illuminate/Database/Schema/Blueprint.php [hunk 1]
```diff
@@ -801,9 +801,9 @@ public function dateTimeTz($column, $precision = 0)
      * @param  string  $column
```
Comment (ntzm) [inline src/Illuminate/Database/Schema/Blueprint.php]: docblock needs updating

Comment (Dylan-DPC) [reply src/Illuminate/Database/Schema/Blueprint.php]: done

**Comment by taylorotwell** [comment]
Formatting on docblock isn't correct.
