### PR TITLE
[12.x] Fix Arr::first for ArrayObject and AsArrayObject values

### LINKED ISSUE #57959: Arr::first() helper not working with model property cast to AsArrayObject
### Laravel Version

12.39

### PHP Version

8.4

### Database Driver & Version

_No response_

### Description

After the recent changes in
https://github.com/laravel/framework/blame/a925110b0ad6aa4a7bf7a03ee27ab52931b3e8ab/src/Illuminate/Collections/Arr.php#L274

My code started breaking, as every place where I use `Arr::first()` on a model property cast to `AsArrayObject `stopped working. I now get the following error:

```
array_find_key(): Argument #1 ($array) must be of type array, Illuminate\Database\Eloquent\Casts\ArrayObject given

 ErrorException 

  array_find_key(): Argument #1 ($array) must be of type array, Illuminate\Database\Eloquent\Casts\ArrayObject given

  at vendor/laravel/framework/src/Illuminate/Collections/Arr.php:274
    270▕ 
    271▕             return value($default);
    272▕         }
    273▕ 
  ➜ 274▕         $key = array_find_key($array, $callback);
    275▕ 
    276▕         return $key !== null ? $array[$key] : value($default);
    277▕     }
    278▕


```

### Steps To Reproduce

Create a model with a property cast to AsArrayObject:

```
class Product extends Model
{
    protected $casts = [
        'prices' => AsArrayObject::class,
    ];
}

$product = Product::first();

Arr::first($product->prices, fn ($price) => $price === 0); // using callback
```

### PR DESCRIPTION
**Pull request by prince-noman**
This PR fixes a regression where `Arr::first()` fails when the input is an `ArrayObject` or an Eloquent cast using `AsArrayObject`.

### Summary

In Laravel 12.39, `Arr::first()` was updated to use PHP 8.4's new `array_find_key()` function.  
However, `array_find_key()` **only accepts native arrays**, not `ArrayObject` or other array-like values.

This causes a type error when calling `Arr::first()` on model attributes cast using `AsArrayObject`, e.g.:

```php
$product = Product::first();

Arr::first($product->prices, fn ($price) => $price === 0);
```

Error:

```
array_find_key(): Argument #1 ($array) must be of type array, Illuminate\Database\Eloquent\Casts\ArrayObject given
```

### Fix

This PR normalizes the input using `Arr::from()` before passing it to `array_find_key()`, restoring support for:

- `ArrayObject`
- `Illuminate\Database\Eloquent\Casts\ArrayObject` (Eloquent `AsArrayObject`)
- other Traversable / array-like values that worked before the regression

The behavior is fully backward-compatible.

### Related Issue

Fixes #57959

### CODE REVIEW

File: src/Illuminate/Collections/Arr.php [hunk 1]
```diff
@@ -271,6 +271,8 @@ public static function first($array, ?callable $callback = null, $default = null
             return value($default);
         }
 
+        $array = static::from($array);
```
Comment (crynobone) [inline src/Illuminate/Collections/Arr.php:274]: Should also update the docblock:

```diff
- * @param  array  $array
+ * @param  \ArrayObject|array  $array
```

Comment (prince-noman) [reply src/Illuminate/Collections/Arr.php:274]: @crynobone I’ve updated the docblock for `Arr::first()` and synced with the latest 12.x. It now uses the generic form `@param iterable<TKey, TValue> $array`, which already covers `ArrayObject` and other iterable types, so the signature stays consistent with the rest of the method.

Please let me know if you’d still like a further adjustment.
