### PR TITLE
[5.8] Added warning when not renaming the Redis facade

### LINKED ISSUE #29806: [5.8] Using phpredis returns an exception
- Laravel Version: v5.8.16
- PHP Version: 7.3
- Database Driver & Version: Redis PECL extension & Redis 5.0.5

### Description:

When using `phpredis` as the driver to connect to a Redis database, any call to the redis database will throw an exception.

For example, this is thrown when Telescope tries to get something from the database:

```
[2019-08-30 18:57:09] local.ERROR: Call to undefined method Illuminate\Support\Facades\Redis::connect() {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined method Illuminate\\Support\\Facades\\Redis::connect() at /app/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php:110)
[stacktrace]
#0 /app/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(67): Illuminate\\Redis\\Connectors\\PhpRedisConnector->establishConnection(Object(Illuminate\\Support\\Facades\\Redis), Array)
#1 /app/vendor/laravel/framework/src/Illuminate/Support/helpers.php(1124): Illuminate\\Redis\\Connectors\\PhpRedisConnector->Illuminate\\Redis\\Connectors\\{closure}(Object(Illuminate\\Support\\Facades\\Redis))
#2 /app/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(84): tap(Object(Illuminate\\Support\\Facades\\Redis), Object(Closure))
#3 /app/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(24): Illuminate\\Redis\\Connectors\\PhpRedisConnector->createClient(Array)
#4 /app/vendor/laravel/framework/src/Illuminate/Redis/RedisManager.php(107): Illuminate\\Redis\\Connectors\\PhpRedisConnector->connect(Array, Array)
#5 /app/vendor/laravel/framework/src/Illuminate/Redis/RedisManager.php(87): Illuminate\\Redis\\RedisManager->resolve('cache')
#6 /app/vendor/laravel/framework/src/Illuminate/Cache/RedisStore.php(242): Illuminate\\Redis\\RedisManager->connection('cache')
#7 /app/vendor/laravel/framework/src/Illuminate/Cache/RedisStore.php(54): Illuminate\\Cache\\RedisStore->connection()
#8 /app/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(97): Illuminate\\Cache\\RedisStore->get('telescope:dump-...')
#9 /app/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(357): Illuminate\\Cache\\Repository->get('telescope:dump-...')
#10 /app/vendor/laravel/telescope/src/Watchers/DumpWatcher.php(43): Illuminate\\Cache\\CacheManager->__call('get', Array)
#11 /app/vendor/laravel/telescope/src/RegistersWatchers.php(48): Laravel\\Telescope\\Watchers\\DumpWatcher->register(Object(Illuminate\\Foundation\\Application))
#12 /app/vendor/laravel/telescope/src/Telescope.php(131): Laravel\\Telescope\\Telescope::registerWatchers(Object(Illuminate\\Foundation\\Application))
#13 /app/vendor/laravel/telescope/src/TelescopeServiceProvider.php(27): Laravel\\Telescope\\Telescope::start(Object(Illuminate\\Foundation\\Application))
#14 [internal function]: Laravel\\Telescope\\TelescopeServiceProvider->boot()
#15 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#16 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#17 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#18 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(576): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#19 /app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(827): Illuminate\\Container\\Container->call(Array)
#20 /app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(810): Illuminate\\Foundation\\Application->bootProvider(Object(Laravel\\Telescope\\TelescopeServiceProvider))
#21 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(Laravel\\Telescope\\TelescopeServiceProvider), 16)
#22 /app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(811): array_walk(Array, Object(Closure))
#23 /app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#24 /app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(210): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#25 /app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(322): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#26 /app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#27 /app/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#28 {main}
"}
```

### Steps To Reproduce:

1. Install and enable the Redis PECL extension in your PHP (differs on platform).
2. Check is enabled using `php -m`.
3.  Set `phpredis` as the driver for Redis databases [as the documentation says](https://laravel.com/docs/5.8/redis#phpredis).
4. Run a Redis Server in your system.
5. Point your application to your Redis server using `REDIS_HOST`, `REDIS_PASSWORD` and `REDIS_PORT`. 
6. Set in your environment file `CACHE_DRIVER=redis`.

### Suggestion

It seems that `PhpRedisConnector` creates a Facade instance instead of the extension Redis class, because it imports the Redis facade instead of the Redis class of PHP.

```
<?php

namespace Illuminate\Redis\Connectors;

use Redis; // <-- THIS LINE ***********************
use RedisCluster;
use Illuminate\Support\Arr;
use Illuminate\Contracts\Redis\Connector;
use Illuminate\Redis\Connections\PhpRedisConnection;
use Illuminate\Redis\Connections\PhpRedisClusterConnection;

class PhpRedisConnector implements Connector
{
    // ...

    /**
     * Create the Redis client instance.
     *
     * @param  array  $config
     * @return \Redis
     */
    protected function createClient(array $config)
    {
        return tap(new Redis, function ($client) use ($config) { // <-- AND THIS LINE ***********************
            $this->establishConnection($client, $config);
            // ...
        }
    }
}
```

Is this is the case, the documentation must add something like the following to the PHPRedis configuration:

> Additionally, change the Redis Facade in your `app.php` for something else, like `RedisManager`, to avoid unwanted collisions with the Redis class registered by the PHP extension.

### PR DESCRIPTION
**Pull request by DarkGhostHunter**
When using `phpredis` as the driver, and the Redis Facade is aliased, the connector will create a new Facade instance instead of the expected Redis Client instance.

With this patch, if the Facade is detected, a more friendly exception will be thrown telling the developer to rename the Facade to avoid collisions with the expected class.

Doesn't fix #29806, but a workaround to avoid breaking changes.

### CODE REVIEW

File: src/Illuminate/Redis/Connectors/PhpRedisConnector.php [hunk 1]
```diff
@@ -64,6 +66,12 @@ protected function buildClusterConnectionString(array $server)
     protected function createClient(array $config)
```
Comment (lucasmichot) [inline src/Illuminate/Redis/Connectors/PhpRedisConnector.php]: `@throws \LogicException` docblock is missing
