### PR TITLE
[8.x] Fix LazyCollection#unique() double enumeration

### LINKED ISSUE #38817: After LazyCollection calls the unique method and then calls the isEmpty method, a piece of data will be lost.
- Laravel Version: 6.20.34
- PHP Version: 7.4.2
- Database Driver & Version:
mysql 5.7.34-log

### Description:
After LazyCollection calls the unique method and then calls the isEmpty method, a piece of data will be lost.

### Steps To Reproduce:

```php
// The offending code snippet:
$items = \Illuminate\Support\LazyCollection::make(fn () => yield from [['id' => '1'], ['id' => '2'], ['id' => '4']]);
dump($items->toArray()); // Output: [['id' => '1'], ['id' => '2'], ['id' => '4']]
$unique_items = $items->unique('id');
// If the output is here, there is no problem, but `LazyCollection::isEmpty()` will return true.
// dump($unique_items->toArray()); // Output: [['id' => '1'], ['id' => '2'], ['id' => '4']]
if (!$unique_items->isEmpty()) {
    // When I judge whether it is a null value, I lost a value.
    dump($unique_items->toArray()); // Output: [['id' => '2'], ['id' => '4']]
}

// Everything is normal for this part of the code.
$items = \Illuminate\Support\Collection::make([['id' => '1'], ['id' => '2'], ['id' => '4']]);
dump($items->toArray());
$items = $items->unique('id');
if (!$items ->isEmpty()) {
    dump($items ->toArray());
}
```

### PR DESCRIPTION
**Pull request by JosephSilber**
Fixes #38817

### CODE REVIEW

File: src/Illuminate/Collections/Collection.php [hunk 1]
```diff
@@ -1411,6 +1411,28 @@ public function transform(callable $callback)
...
+        $exists = [];
+
+        return $this->reject(function ($item, $key) use ($callback, $strict, &$exists) {
+            if (in_array($id = $callback($item, $key), $exists, $strict)) {
+                return true;
+            }
+
+            $exists[] = $id;
+        });
+    }
```
Comment (JosephSilber) [inline src/Illuminate/Collections/Collection.php:1434]: Just to explain why this didn't work:

The call to `$this->reject` returned a new `LazyCollection` instance. Every time the collection is enumerated, the callback (that was passed to `reject`) gets called again, but it's reusing the same `$exists` cache of found items, so anything that was previously enumerated is treated as a duplicate :frowning: 

The solution is to have a separate implementation of the `unique()` method for the `LazyCollection` class. In that implementation, we can move the `$exists` cache into the `Generator` function passed to the constructor, so that each enumeration has its own cache :+1:

File: src/Illuminate/Collections/Traits/EnumeratesValues.php [hunk 2]
```diff
@@ -773,28 +773,6 @@ public function reject($callback = true)
...
-
-        return $this->reject(function ($item, $key) use ($callback, $strict, &$exists) {
-            if (in_array($id = $callback($item, $key), $exists, $strict)) {
-                return true;
-            }
-
-            $exists[] = $id;
-        });
-    }
-
```
Comment (Jubeki) [inline src/Illuminate/Collections/Traits/EnumeratesValues.php:797]: I would consider this a breaking change.

Maybe you can only add the unique Method to the Lazy Collection and let the normal Collection stay the same with using the EnumeratesValues Trait.

**Review by Jubeki — CHANGES_REQUESTED** [review]

**Comment by driesvints** [comment]
@JosephSilber can you rebase with 8.x? I've re-enabled tests on 8.x after a small break from yesterday.

File: src/Illuminate/Collections/Traits/EnumeratesValues.php (hunk 2 above)
Comment (JosephSilber) [reply src/Illuminate/Collections/Traits/EnumeratesValues.php:797]: The `EnumeratesValues` trait was never meant to be consumed by the public. It's an internal trait that's only there to house the shared code between the two collection classes. I can't really believe anyone is using this trait in the wild.

I'll let Taylor decide whether he considers this a breaking change.
