### PR TITLE
[9.x] Bind a Vite Null Object to the Container instead of a Closure

### LINKED ISSUE #43039: TestCase::withoutVite breaks React app during testing
- Laravel Version: 9.19.0
- PHP Version: 8.1.7
- Database Driver & Version: PostgreSQL 14

### Description:

The `@viteReactRefresh` directive crashes the application when `withoutVite` is used during testing.

Error message: `Call to undefined method Closure::reactRefresh() (View: /Users/muhammedsari/Sites/redacted/resources/views/app.blade.php)`

### Steps To Reproduce:

Add the directive combo to your template

```blade
@viteReactRefresh
@vite('resources/js/platform.jsx')
```

Call `$this->withoutVite()` in your `TestCase::setUp()` method.

### PR DESCRIPTION
**Pull request by mabdullahsari**
Closes #43039

### CODE REVIEW

**Review by timacdonald — APPROVED** [review]

File: src/Illuminate/Foundation/Testing/Concerns/InteractsWithContainer.php [hunk 1]
```diff
@@ -109,8 +109,17 @@ protected function withoutVite()
...
+        {
+            public function __invoke()
+            {
+                return '';
+            }
+
+            public function reactRefresh()
+            {
+                return '';
+            }
```
Comment (jessarcher) [inline src/Illuminate/Foundation/Testing/Concerns/InteractsWithContainer.php:122]: What do you think of this?

```suggestion
            public function __call($name, $arguments)
            {
                return '';
            }
```

This will help if any new methods are added, as I can see people forgetting to add them here.

cc @timacdonald

**Comment by taylorotwell** [comment]
Tests are failing.

**Comment by jessarcher** [comment]
> Tests are failing.

Fixed. My bad - we still needed the `__invoke()` method as `__call()` alone doesn't make the class invokable.

**Comment by mabdullahsari** [comment]
> > Tests are failing.
> 
> Fixed. My bad - we still needed the `__invoke()` method as `__call()` alone doesn't make the class invokable.

`__call` is indeed better for future additions. Thank you!
