### PR TITLE
[13.x] Defer registering schedule registered using  `ApplicationBuilder::withScheduling()`

### LINKED ISSUE #51354: Schedule gets registered with every artisan call
### Laravel Version

11.7.0

### PHP Version

8.3.6

### Database Driver & Version

_No response_

### Description

When running any `artisan` command (just `php artisan` does the same), the code inside `console.php` route file and/or `->withSchedule()` bootstrap method gets executed. Usually this wouldn't be a big deal, because the code should only register cron events. However, sometimes dynamic scheduling might involve database queries which can inflict unwanted performance penalty or in worst case scenario fail in CI setup.

We noticed this in our CI while upgrading from Laravel 10 to Laravel 11 (with slimmed down app structure). Our scheduler needs to be dynamic and it makes a DB query for that reason. When CI is setting up the application it runs `composer install` which then runs `php artisan package:discover --ansi` as a composer `post-autoload-dump` script. This is standard in every Laravel project. Since `package:discover` is an artisan command it boots up the scheduler as well. At this stage in CI database is not yet available thus we get a `QueryException: SQLSTATE[HY000] [2002] Connection refused`.

I have checked and this wasn't the case with Laravel 10. I'm not sure if this is now intended or not, but I would expect scheduler code to only execute when calling `php artisan schedule:run` and `php artisan schedule:work`.

### Steps To Reproduce

* Set up new Laravel 11 project.
* Add `dd();` inside `console.php` route file or inside `->withSchedule()` app bootstrap method.
* Run `php artisan` and observe the command to fail.

### PR DESCRIPTION
**Pull request by crynobone**
fix #51354

This was previously PR #51364 but rejected due to possible breaking change. I believe it should be safe to target it for Laravel 13.

### CODE REVIEW

File: src/Illuminate/Foundation/Configuration/ApplicationBuilder.php [hunk 1]
```diff
@@ -355,7 +355,13 @@ protected function withCommandRouting(array $paths)
      */
     public function withSchedule(callable $callback)
     {
-        Artisan::starting(fn () => $callback($this->app->make(Schedule::class)));
+        Artisan::starting(function () use ($callback) {
+            $this->app->afterResolving(Schedule::class, fn ($schedule) => $callback($schedule));
+
+            if ($this->app->resolved(Schedule::class)) {
```
Comment (rodrigopedra) [inline src/Illuminate/Foundation/Configuration/ApplicationBuilder.php:361]: The `ServiceProvider@afterResolving()` method already has the same `if` to check if the target class is already resolved and so execute the callback immediately.

https://github.com/laravel/framework/blob/7ccd75c23e229a67d1fd5ea377fb756eda89b397/src/Illuminate/Support/ServiceProvider.php#L310-L317

Having this `if` clause both within the `ServiceProvider@afterResolving()` and here would trigger the callback twice for already resolved classes.

Comment (crynobone) [reply src/Illuminate/Foundation/Configuration/ApplicationBuilder.php:361]: Can you provide a test where  `ServiceProvider::callAfterResolving()` will affect `ApplicationBuilder`?

Comment (rodrigopedra) [reply src/Illuminate/Foundation/Configuration/ApplicationBuilder.php:361]: Never mind, I missed the point here. 

I thought it was within a service provider. Sorry.
