### PR TITLE
[11.x] Fix: Improve Request Port Extraction Handling in ServeCommand.php to Prevent Artisan Command Failures 

### LINKED ISSUE #53534: UrlGenerationException sends a log line to stderr that breaks artisan serve
### Laravel Version

11.32.0

### PHP Version

8.2.25

### Database Driver & Version

_No response_

### Description

When using a helper ```{{ route('anyroute') }}``` without the necessary route parameters (by accident), Laravel throws a ```UrlGenerationException```, sending a log line to stderr that breaks the server.

The issue is the datetime string at the beginning, which ```getRequestPortFromLine``` is not prepared to parse. In Laravel 10, the same line does not display that datetime.

The problem only occurs when using ```LOG_CHANNEL=stderr```. 

```bash
[2024-11-16 06:58:05] local.ERROR: Undefined array key 1 {"exception":"[object] (ErrorException(code: 0): Undefined array key 1 at /Users/.../laravel-11/vendor/laravel/framework/src/Illuminate/Foundation/Console/ServeCommand.php:383)

...

ErrorException 

Undefined array key 1

at vendor/laravel/framework/src/Illuminate/Foundation/Console/ServeCommand.php:383
  379▕     protected function getRequestPortFromLine($line)
  380▕     {
  381▕         preg_match('/:(\d+)\s(?:(?:\w+$)|(?:\[.*))/', $line, $matches);
  382▕ 
➜ 383▕         return (int) $matches[1];
  384▕     }
  385▕ 
  386▕     /**
  387▕      * Get the console command options.

    +26 vendor frames 

27  artisan:13
    Illuminate\Foundation\Application::handleCommand(Object(Symfony\Component\Console\Input\ArgvInput))
```

<table>
  <tr>
    <td>Browser</td>
    <td>After reload</td>
    <td>Terminal</td>
  </tr>
  <tr>
    <td></td>
    <td></td>
    <td></td>
  </tr>
</table>

#### Install Laravel 11

```bash
composer create-project --prefer-dist laravel/laravel laravel-11
cd laravel-11
```

#### Change LOG_CHANNEL to stderr

```bash
# .env

LOG_CHANNEL=stderr
```

#### Create routes with any parameter

```php
// routes/web.php

Route::view('/tenants/{tenant}', 'home')->name('home');
Route::View('/tenants/{tenant}/info', 'info')->name('info');
```

#### Create their views with routes missing required parameters

```php
// resources/views/home.blade.php

<html>
    <body>
        <a href="{{ route('info') }}">Info</a>
    </body>
</html>
```

```php
// resources/views/info.blade.php

<html>
    <body>
        <a href="{{ route('home') }}">Home</a>
    </body>
</html>
```

#### Run the server

```bash
php artisan serve
```

#### Access any route with parameter

```bash
open http://localhost:8000/tenants/tenant1
```

#### Server will throw an error, exit to the command line, and stop working

```bash
[2024-11-16 06:58:05] local.ERROR: Undefined array key 1 {"exception":"[object] (ErrorException(code: 0): Undefined array key 1 at /Users/.../laravel-11/vendor/laravel/framework/src/Illuminate/Foundation/Console/ServeCommand.php:383)

...

ErrorException 

Undefined array key 1

at vendor/laravel/framework/src/Illuminate/Foundation/Console/ServeCommand.php:383
  379▕     protected function getRequestPortFromLine($line)
  380▕     {
  381▕         preg_match('/:(\d+)\s(?:(?:\w+$)|(?:\[.*))/', $line, $matches);
  382▕ 
➜ 383▕         return (int) $matches[1];
  384▕     }
  385▕ 
  386▕     /**
  387▕      * Get the console command options.

    +26 vendor frames 

27  artisan:13
    Illuminate\Foundation\Application::handleCommand(Object(Symfony\Component\Console\Input\ArgvInput))
```

### PR DESCRIPTION
**Pull request by iz-ahmad**
[Updated] This PR fixes an issue ([#53534](https://github.com/laravel/framework/issues/53534)) in the `getRequestPortFromLine` method in `ServeCommand.php` where failing to extract the request port from the log line resulted in an `Undefined array key 1` error when using `LOG_CHANNEL=stderr`. This error would break the server when generating a URL with missing parameters, causing Artisan commands to fail.

## Changes:
* **Updated Regex:** The regular expression was updated to match log lines with an _optional_ datetime prefix, ensuring proper extraction of the request port, even when a timestamp is present.
* **Improved error handling:** If the port number cannot be extracted, the method will now throw a clear exception with the problematic log line, making debugging easier.

## How This Fix Solves the Issue:
This fix resolves the issue where the server breaks because the `getRequestPortFromLine` method fails to parse log lines with a datetime prefix. By updating the regex, we ensure that both types of log lines (**with and without datetime**) are handled correctly. Additionally, the exception handling ensures that if parsing fails, it is immediately clear which log line caused the failure, facilitating **quicker debugging** for devs.

---

This way, this PR enhances the stability of Laravel's `artisan serve` command by addressing the **log parsing issue** in a a manner which can ensure smoother development workflows. Thank you.

### CODE REVIEW

File: src/Illuminate/Foundation/Console/ServeCommand.php [hunk 1]
```diff
@@ -374,11 +374,22 @@ protected function getDateFromLine($line)
...
+         * Updated regex to match the log line with or without a datetime prefix.
+         * The regex checks for an optional datetime prefix (example: [Wed Nov 15 2024 10:12:45]) followed by a colon and the port number.
+         */
+        preg_match('/(\[\w+\s\w+\s\d+\s[\d:]+\s\d{4}\]\s)?:(\d+)\s(?:(?:\w+$)|(?:\[.*))/', $line, $matches);
+
+        /**
+         * If the port number could not be extracted (if no match for the port number found), an exception is thrown with a message containing the problematic line for easier debugging.
+         */
+        if (! isset($matches[2])) {
+            throw new \Exception("Failed to extract request port from line: $line");
```
Comment (crynobone) [inline src/Illuminate/Foundation/Console/ServeCommand.php:389]:
```suggestion
            throw new \Exception("Failed to extract request port from line: {$line}");
```

**Comment by taylorotwell** [comment]
Can we extract this function into a static function that we then put a lot of tests around?

**Comment by ahmad-cit22** [comment]
> Can we extract this function into a static function that we then put a lot of tests around?

Thanks a lot. 

Based on your suggestion, I moved the request port extracting logic into a static method in a new utility class. And then wrote unit tests to cover possible edge cases related to the function. Hope this will solve the issue in a better approach.
