### PR TITLE
[5.4] Set data key when testing file uploads in nested array

### LINKED ISSUE #18671: MakesHttpRequests has wrong function > extractFilesFromDataArray
- Laravel Version: 5.4.* 
- PHP Version: 7.1.1
- Database Driver & Version: MySQL 10.2.4-MariaDB

### Description:

> Illuminate\Foundation\Testing\Concerns\MakesHttpRequests.php
```
protected function extractFilesFromDataArray(&$data) {...}
```
This function works wrong.
You need to update **$data** variable:
> Before:
```
if (is_array($value)) {
   $files[$key] = $this->extractFilesFromDataArray($value);
}
```
> After:
```
if (is_array($value)) {
   $files[$key] = $this->extractFilesFromDataArray($value);
   $data[$key] = $value;
}
```

### Steps To Reproduce:
I used next array in my test class:
```
$response = $this->postJson(route('admin.postcards.store'), [
   'background' => [
      'image_file' => UploadedFile::fake()->image('image.png', 100)
   ],
   'image_file' => UploadedFile::fake()->image('image_file.png', 100),
   'title' => 'Postcard',
   'slug' => 'postcard',
   'music' => ['id' => 2]
])->getData();
```
Json function inside Illuminate\Foundation\Testing\Concerns\MakesHttpRequests.php make my data equal to false, because background.image_file is not deleted.

### PR DESCRIPTION
**Pull request by RDelorier**
Fix a bug that causes data keys to be overridden when testing a nested file upload array.

Example of bug in action:

*routes/web.php*
```php
Route::post('test', function () {
    Validator::make(request()->all(), [
        'foo' => 'required'
    ])->validate();
});
```

*tests/Feature/ExampleTest.php*
```php
<?php

namespace Tests\Feature;

use Tests\TestCase;
use Illuminate\Http\UploadedFile;

class ExampleTest extends TestCase
{
    public function testExample()
    {
        $this->postJson('test', [
            'foo' => 'bar',
            'images' => [UploadedFile::fake()->image('image.jpg')]
        ])->assertStatus(200);
    }
}
```

Test result:
```
Expected status code 200 but received 422.
Failed asserting that false is true.
```

This pr sets the value in the data which fixes the bug.

fixes #18671

### CODE REVIEW

**Comment by themsaid** [comment]
This is wrong, using `unset($data[$key])` will unset every single key with a value of type array, even if the field is not an array of files.

File: src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php [hunk 1]
```diff
@@ -307,6 +307,8 @@ protected function extractFilesFromDataArray(&$data)
 
             if (is_array($value)) {
                 $files[$key] = $this->extractFilesFromDataArray($value);
+
+                unset($data[$key]);
```
Comment (themsaid) [inline src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php]: Replace this with `$data[$key] = $value;`, I think it'll fix your issue.

**Comment by RDelorier** [comment]
Woops, good catch @themsaid
