### PR TITLE
[10.x] Fix `createOrFirst` on transactions

### LINKED ISSUE #48143: `Model::createOrFirst()` in Postgres transaction may trigger `SQLSTATE[25P02]: In failed sql transaction: 7 ERROR:  current transaction is aborted, commands ignored until end of transaction block`
### Laravel Version

10.20.0

### PHP Version

irrelevant

### Database Driver & Version

PostgreSQL (Version: irrelevant)

### Description

With the recent release of Laravel v10.20.0, due to #47973, there has been an overlap in functionality with my library: [mpyw/laravel-retry-on-duplicate-key](https://github.com/mpyw/laravel-retry-on-duplicate-key), which was originally designed to offer a feature now implemented by Laravel. Although this in itself is not an issue and I intend to update my library accordingly, I've identified a potential concern with how Laravel's new feature manages Postgres transactions.

Postgres has a distinctive behavior where, if an error occurs within a transaction, all subsequent queries fail unless the current transaction is rolled back or committed. However, this can be handled by setting a `SAVEPOINT`, which limits the rollback to that point. **In my library, for Postgres and when the transaction level is greater than 0, I've incorporated a mechanism using `DB::transaction()` to create a `SAVEPOINT`**. If Laravel's new feature doesn't adopt a similar approach to handle Postgres transactions, it could lead to errors: `SQLSTATE[25P02]: In failed sql transaction: 7 ERROR:  current transaction is aborted, commands ignored until end of transaction block`.

- https://github.com/mpyw/laravel-retry-on-duplicate-key/blob/7006a54100b28e0ef2d777122ccf416ebbc3a372/src/RetryOnDuplicateKey.php#L53-L74

```php
class RetryOnDuplicateKey
{
    protected ConnectionInterface $connection;

    public function __construct(ConnectionInterface $connection)
    {
        $this->connection = $connection;
    }

    /**
     * Retries once on duplicate key errors.
     *
     * @param mixed ...$args
     * @return mixed
     */
    public function __invoke(callable $callback, ...$args)
    {
        try {
            return $this->withSavepoint(fn () => $callback(...$args));
        } catch (PDOException $e) {
            if ((new UniqueViolationDetector($this->connection))->violated($e)) {
                $this->forceReferringPrimaryConnection();
                return $this->withSavepoint(fn () => $callback(...$args));
            }
            throw $e;
        }
    }

    /**
     * Make sure to fetch the latest data on the next try.
     */
    protected function forceReferringPrimaryConnection(): void
    {
        $connection = $this->connection;

        if ($connection instanceof Connection) {
            $connection->recordsHaveBeenModified();
        }
    }

    /**
     * @phpstan-template T
     * @phpstan-param callable(): T $callback
     * @phpstan-return T
     * @return mixed
     * @noinspection PhpDocMissingThrowsInspection
     * @noinspection PhpUnhandledExceptionInspection
     */
    protected function withSavepoint(callable $callback)
    {
        return $this->needsSavepoint()
            ? $this->connection->transaction(fn () => $callback())
            : $callback();
    }

    protected function needsSavepoint(): bool
    {
        // In Postgres, savepoints allow recovery from errors.
        // This ensures retrying should work also in transactions.
        return $this->connection instanceof PostgresConnection
            && $this->connection->transactionLevel() > 0;
    }
}
```

### Steps To Reproduce

```php
User::create(['email' => 'example@example.com'], ['name' => 'example']);

DB::transaction(function () {
    User::createOrFirst(['email' => 'example@example.com'], ['name' => 'example']);
})
```

### PR DESCRIPTION
**Pull request by tonysm**
### Added

- Adds a new `withSavepointIfNeeded(fn)` method to the Eloquent query Builder that wraps the given scope in a transaction if there's a transaction going on

### Changed

- Wraps the `create` or `attach` parts of the `createOrFirst` within a save point transaction using the `withSavePointIfNeeded` method

---

Fixes https://github.com/laravel/framework/issues/48143

Looks like we need to wrap the insert part of a the `createOrFirst` within a save point transaction for PostgreSQL, because otherwise the find part will fail.

### CODE REVIEW

File: src/Illuminate/Database/Eloquent/Builder.php [hunk 1]
```diff
@@ -2029,4 +2031,19 @@ public function __clone()
...
+
+    /**
+     * Wraps the given Closure with a transaction savepoint if needed.
+     *
+     * @template TModelValue
+     *
+     * @param  \Closure(): TModelValue  $scope
+     * @return TModelValue
+     */
+    public function withSavepointIfNeeded(Closure $scope): mixed
```
Comment (tonysm) [inline src/Illuminate/Database/Eloquent/Builder.php:2043]: Not sure about this. I thought about just wrapping the insert part in a `DB::transaction(fn)`, which not sure what y'all would think of that. I initially had it as `protected`, but I needed the same logic in the relationship part of the feature.

Let me know what y'all think.

File: src/Illuminate/Database/Eloquent/Builder.php [hunk 2]
```diff
@@ -580,7 +580,9 @@ public function firstOrCreate(array $attributes = [], array $values = [])
     public function createOrFirst(array $attributes = [], array $values = [])
     {
         try {
-            return $this->create(array_merge($attributes, $values));
+            return $this->withSavepointIfNeeded(function () use ($attributes, $values) {
```
Comment (tonysm) [inline src/Illuminate/Database/Eloquent/Builder.php:583]: I really liked how it read before: `createOrFirst` was essentially calling `create()` then `first()`, now it has more noise. I thought about pushing the savepoint to the `create()` method, which would keep this part as it was, but than it would be a bigger change.

**Comment by crynobone** [comment]
Marking this as draft as there some failing tests need to be updated.

File: src/Illuminate/Database/Eloquent/Builder.php (hunk 1 above)
Comment (mpyw) [reply src/Illuminate/Database/Eloquent/Builder.php:2043]: For MySQL, this is not necessary; Postgres just needs it. However, it is not known what SQLServer and SQLite do.

Comment (tonysm) [reply src/Illuminate/Database/Eloquent/Builder.php:2043]: Yeah, I figured it wouldn't be a problem to wrap in savepoint transactions for the other drivers as well. It doesn't seem to hurt.

**Comment by tonysm** [comment]
@crynobone fixed the tests. Not sure why the SQLServer suite is failing, but seems to be failing on other PRs too, btw. Should I mark this PR as ready for review?

**Comment by mpyw** [comment]
We may need this: https://github.com/mpyw/laravel-unique-violation-detector/pull/3/commits/00492815ac66a08035e951ff359ee4f30a9419c4

**Comment by mpyw** [comment]
While this feature is highly beneficial, it seems to have a considerable impact. Personally, I feel it might have been better suited for Laravel 11. Even though it's already been incorporated into 10.20.0, might we consider reverting it and then reintroducing it as a target for version 11?

**Comment by mpyw** [comment]
@taylorotwell Can I have your opinion?

**Comment by tonysm** [comment]
> We may need this: https://github.com/mpyw/laravel-unique-violation-detector/pull/3/commits/00492815ac66a08035e951ff359ee4f30a9419c4

Yeah, I think I had to comment out this line [here](https://github.com/laravel/framework/blob/7f287ed2ee8aa0067b66c002b582f8ff7eedc00c/src/Illuminate/Database/Connectors/SqlServerConnector.php#L19) to run the SQLServer tests (I'm not on my computer right now to check), but the suite was passing in the original PR. 🤔

**Comment by taylorotwell** [comment]
@tonysm any ideas on what to do about the SQL Server tests?

**Comment by tonysm** [comment]
@taylorotwell I just tested out over here. If I uncomment [this line](https://github.com/laravel/framework/blob/7f287ed2ee8aa0067b66c002b582f8ff7eedc00c/src/Illuminate/Database/Connectors/SqlServerConnector.php#L19), the SQLServer tests pass locally. With that in, it looks like all of them are broken.

I found [this reference from Drupal](https://www.drupal.org/project/sqlsrv/issues/3379887) where they are using a `try/catch` when setting the PDO attributes. It looks like something changed in the SQL Server extension in some 8.x minor release of PHP. Some other references from [php-src](https://github.com/php/php-src/issues/11587) and a [Laravel issue from 3 weeks ago](https://github.com/laravel/framework/issues/47937). Looks like a PR was merged already in the [mssql extension](https://github.com/microsoft/msphpsql/pull/1468), but I still see the issue.

Either way, it seems unrelated to the changes in the `createOrFirst`.

**Comment by tonysm** [comment]
Looks like there are some flaky tests also unrelated to `createOrFirst` and the changes here. Might have some time later to fix them, but it might be better to handle that in a separate PR. I cannot re-run the action myself, but that should "fix" it for now if anyone with the permission to do that can do it.
