### PR TITLE
[12.x] Fix calling `toArray()` on `AnonymousResourceCollection` returns an array of resources

### LINKED ISSUE #13442: Taxonomy term listing broken with Laravel 12.45.0+ ("Call to a member function mapWithKeys() on null")
### Bug description

After updating to Laravel 12.45.0, listing taxonomy terms in the Control Panel throws an error:

`Call to a member function mapWithKeys() on null at vendor/statamic/cms/src/Http/Resources/CP/Taxonomies/ListedTerm.php:54`

**Cause**
Laravel 12.45.0 introduced JSON:API Resource support ([PR #57571](https://github.com/laravel/framework/pull/57571)) which changed how `ResourceCollection` resolves resources. The new `JsonResource::resolveResourceData()` method now calls `toAttributes()` instead of `toArray()`. For `ResourceCollection`, the new `toAttributes()` method directly calls `$this->collection->map->resolve($request)` - bypassing `toArray()` entirely. Statamic's `Terms::toArray()` method calls `setColumns()` which must run before individual `ListedTerm` resources are resolved. Since `toArray()` is no longer called, `$this->columns` remains null, causing the error in `ListedTerm::values()`.

### How to reproduce

1. Install Statamic with Laravel 12.45.0 or 12.45.1
2. Create a taxonomy with at least one term
3. Navigate to the taxonomy in the Control Panel
4. Error occurs when listing terms

### Logs

```shell
[2026-01-07 08:05:25] local.ERROR: Call to a member function mapWithKeys() on null {"userId":"a3158147-94a5-4ea7-aa3e-9aea93b5f4bb","exception":"[object] (Error(code: 0): Call to a member function mapWithKeys() on null at /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/statamic/cms/src/Http/Resources/CP/Taxonomies/ListedTerm.php:54)
[stacktrace]
#0 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/statamic/cms/src/Http/Resources/CP/Taxonomies/ListedTerm.php(38): Statamic\\Http\\Resources\\CP\\Taxonomies\\ListedTerm->values(Array)
#1 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/JsonResource.php(139): Statamic\\Http\\Resources\\CP\\Taxonomies\\ListedTerm->toArray(Object(Illuminate\\Http\\Request))
#2 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/JsonResource.php(150): Illuminate\\Http\\Resources\\Json\\JsonResource->toAttributes(Object(Illuminate\\Http\\Request))
#3 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/JsonResource.php(114): Illuminate\\Http\\Resources\\Json\\JsonResource->resolveResourceData(Object(Illuminate\\Http\\Request))
#4 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Collections/HigherOrderCollectionProxy.php(66): Illuminate\\Http\\Resources\\Json\\JsonResource->resolve(Object(Illuminate\\Http\\Request))
#5 [internal function]: Illuminate\\Support\\HigherOrderCollectionProxy->Illuminate\\Support\\{closure}(Object(Statamic\\Http\\Resources\\CP\\Taxonomies\\ListedTerm), 0)
#6 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(786): array_map(Object(Closure), Array, Array)
#7 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(819): Illuminate\\Support\\Arr::map(Array, Object(Closure))
#8 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Collections/HigherOrderCollectionProxy.php(63): Illuminate\\Support\\Collection->map(Object(Closure))
#9 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/ResourceCollection.php(101): Illuminate\\Support\\HigherOrderCollectionProxy->__call('resolve', Array)
#10 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/JsonResource.php(150): Illuminate\\Http\\Resources\\Json\\ResourceCollection->toAttributes(Object(Illuminate\\Http\\Request))
#11 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/JsonResource.php(114): Illuminate\\Http\\Resources\\Json\\JsonResource->resolveResourceData(Object(Illuminate\\Http\\Request))
#12 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/PaginatedResourceResponse.php(19): Illuminate\\Http\\Resources\\Json\\JsonResource->resolve(Object(Illuminate\\Http\\Request))
#13 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/ResourceCollection.php(133): Illuminate\\Http\\Resources\\Json\\PaginatedResourceResponse->toResponse(Object(Illuminate\\Http\\Request))
#14 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/ResourceCollection.php(113): Illuminate\\Http\\Resources\\Json\\ResourceCollection->preparePaginatedResponse(Object(Illuminate\\Http\\Request))
#15 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Routing/Router.php(921): Illuminate\\Http\\Resources\\Json\\ResourceCollection->toResponse(Object(Illuminate\\Http\\Request))
#16 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Routing/Router.php(906): Illuminate\\Routing\\Router::toResponse(Object(Illuminate\\Http\\Request), Object(Statamic\\Http\\Resources\\CP\\Taxonomies\\Terms))
#17 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Routing/Router.php(821): Illuminate\\Routing\\Router->prepareResponse(Object(Illuminate\\Http\\Request), Object(Statamic\\Http\\Resources\\CP\\Taxonomies\\Terms))
#18 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#19 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/statamic/cms/src/Http/Middleware/DeleteTemporaryFileUploads.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Statamic\\Http\\Middleware\\DeleteTemporaryFileUploads->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/statamic/cms/src/Http/Middleware/CP/AddVaryHeaderToResponse.php(11): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Statamic\\Http\\Middleware\\CP\\AddVaryHeaderToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/statamic/cms/src/Http/Middleware/CP/CountUsers.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Statamic\\Http\\Middleware\\CP\\CountUsers->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/statamic/cms/src/Http/Middleware/CP/BootUtilities.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Statamic\\Http\\Middleware\\CP\\BootUtilities->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/statamic/cms/src/Http/Middleware/CP/BootPreferences.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Statamic\\Http\\Middleware\\CP\\BootPreferences->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/statamic/cms/src/Http/Middleware/CP/BootPermissions.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Statamic\\Http\\Middleware\\CP\\BootPermissions->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/statamic/cms/src/Http/Middleware/CP/SelectedSite.php(17): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Statamic\\Http\\Middleware\\CP\\SelectedSite->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/statamic/cms/src/Http/Middleware/CP/Localize.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Statamic\\Http\\Middleware\\CP\\Localize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/statamic/cms/src/Http/Middleware/CP/Authorize.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Statamic\\Http\\Middleware\\CP\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/statamic/cms/src/Http/Middleware/CP/AddToasts.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Statamic\\Http\\Middleware\\CP\\AddToasts->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/statamic/cms/src/Http/Middleware/CP/AuthGuard.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Statamic\\Http\\Middleware\\CP\\AuthGuard->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/statamic/cms/src/Http/Middleware/CP/ContactOutpost.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Statamic\\Http\\Middleware\\CP\\ContactOutpost->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(69): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Illuminate\\Session\\Middleware\\AuthenticateSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(87): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(120): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#55 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#56 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#57 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#58 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(74): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#59 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#60 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/statamic/cms/src/Http/Middleware/SwapExceptionHandler.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#61 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Statamic\\Http\\Middleware\\SwapExceptionHandler->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#62 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#63 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Routing/Router.php(821): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#64 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Routing/Router.php(800): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#65 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Routing/Router.php(764): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#66 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Routing/Router.php(753): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#67 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#68 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#69 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/statamic/cms/src/Http/Middleware/StopImpersonating.php(12): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#70 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Statamic\\Http\\Middleware\\StopImpersonating->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#71 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(17): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#72 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Statamic\\Http\\Middleware\\DisableFloc->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#73 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(15): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#74 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Statamic\\Http\\Middleware\\CheckMultisite->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#75 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#76 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#77 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#78 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Statamic\\Http\\Middleware\\PoweredByHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#79 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#80 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#81 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#82 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#83 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#84 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(47): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#85 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#86 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#87 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Illuminate\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#88 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(109): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#89 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#90 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#91 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Illuminate\\Http\\Middleware\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#92 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#93 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#94 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/InvokeDeferredCallbacks.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#95 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Illuminate\\Foundation\\Http\\Middleware\\InvokeDeferredCallbacks->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#96 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Http/Middleware/ValidatePathEncoding.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#97 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(219): Illuminate\\Http\\Middleware\\ValidatePathEncoding->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#98 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#99 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#100 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#101 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1220): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#102 /Users/espengrimsgaard/Sites/sjekkpunkt-medlemssider/public/index.php(20): Illuminate\\Foundation\\Application->handleRequest(Object(Illuminate\\Http\\Request))
#103 /Users/espengrimsgaard/.composer/vendor/laravel/valet/server.php(110): require('/Users/espengri...')
#104 {main}
"}
```

### Environment

```yaml
(This is after the downgrade to solve the problem)

Environment
Application Name: Sjekkpunkt Medlemssider
Laravel Version: 12.44.0
PHP Version: 8.3.24
Composer Version: 2.8.10
Environment: local
Debug Mode: ENABLED
URL: sjekkpunkt-medlemssider.test
Maintenance Mode: OFF
Timezone: UTC
Locale: nb

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: log
Queue: sync
Session: file

Storage
public/storage: NOT LINKED

Statamic
Addons: 1
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.70.0 PRO

Statamic Addons
jacksleight/statamic-bard-texstyle: 3.6.0
```

### Installation

Fresh statamic/statamic site via CLI

### Additional details

_No response_

### LINKED ISSUE #58297: ResourceCollection throws "Call to a member function resolve() on array" error after upgrade to Laravel 12.45
### Laravel Version

12.45.0

### PHP Version

8.4.16

### Database Driver & Version

_No response_

### Description

After upgrading from Laravel 12.44 to 12.45, `ResourceCollection` throws an error when initialized with a plain array. This was working correctly in version 12.44.

### Steps To Reproduce

1. Create a ResourceCollection class:

```
namespace App\Http\Resources;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\ResourceCollection;

class TestResourceCollection extends ResourceCollection
{
    public function toArray(Request $request): array
    {
        return $this->resource->toArray();
    }
}
```

2. Use it in a controller with a plain array:
```
namespace App\Http\Controllers;

use App\Http\Resources\TestResourceCollection;
use App\Models\TestModel;

class TestResourceController extends Controller
{
    public function index()
    {
        $model = TestModel::find(1);

        $resource = [
            'list' => [$model],
            'total' => 1,
        ];

        return new TestResourceCollection($resource);
    }
}
```
3. Call the controller endpoint
4. Error occurs
```
Call to a member function resolve() on array
Error in /var/www/app/vendor/laravel/framework/src/Illuminate/Collections/HigherOrderCollectionProxy.php on line 66
```

Additional Context
This appears to be a breaking change introduced in Laravel 12.45 that breaks existing code that was working in 12.44.

### LINKED ISSUE #58307: `JsonResource::collection()` with LengthAwarePaginator now returns a collection in a collection when the collection is empty when setting a custom wrapping name
### Laravel Version

11.45.1

### PHP Version

8.4

### Database Driver & Version

_No response_

### Description

This was no problem in 11.44. We use in our applications custom wrapper for results (results instead of data). This behavior is now broken and returns the paginated resource inside 'results' instead.

Looking at https://github.com/laravel/framework/pull/57571 it now in some cases assumes that the wrapper is ALWAYS 'data' which is not always the case. I think that might be related as changing the static $wrap in my application to 'data' fixes this.

### Steps To Reproduce

Changing to Laravel 12.44 makes the test pass. 12.45+ fails.

https://github.com/rikvdh/laravel-resource-bug

### PR DESCRIPTION
**Pull request by crynobone**
fixes #58300
fixes #58297 
fixes #58307

### CODE REVIEW

File: tests/Integration/Http/ResourceTest.php [hunk 1]
```diff
@@ -50,6 +52,49 @@
...
+            $this->assertSame(PostResource::class, $userAsArray['posts']->collects);
+
+            tap($userAsArray['posts']->toArray($request), function ($postsAsArray) {
+                $this->assertIsArray($postsAsArray);
+                $this->assertCount(2, $postsAsArray);
+                $this->assertSame(['id' => 5, 'title' => 'Test Title', 'custom' => true], $postsAsArray[0]);
+                $this->assertSame(['id' => 10, 'title' => 'Another Test Title', 'custom' => true], $postsAsArray[1]);
+            });
+        });
+    }
```
Comment (crynobone) [inline tests/Integration/Http/ResourceTest.php:97]: @cosmastech this should cover your current use case.

File: src/Illuminate/Http/Resources/Json/ResourceCollection.php [hunk 2]
```diff
@@ -96,13 +96,14 @@ public function count(): int
...
-    public function toAttributes(Request $request)
+    #[\Override]
+    public function toArray(Request $request)
     {
         if ($this->collection->first() instanceof JsonResource) {
             return $this->collection->map->resolve($request)->all();
         }
 
-        return $this->toArray($request);
+        return $this->collection->map->toArray($request)->all();
```
[the remark this answers is not in the document]
Comment (jasonencode) [reply src/Illuminate/Http/Resources/Json/ResourceCollection.php]:
```
class OrderCollection extends BaseCollection
{
    public function toAttributes(Request $request): array
    {
        return [
            'page' => $this->pagination(),
            'list' => $this->collection->map(function($item) {
                return [
                    'id' => $item->id,
                ];
            }),
        ];
    }
}
```
use this way?  replace `toAttributes` function?

**Comment by duncanmcclean** [comment]
Thanks for the speedy fix! This PR seems to address [some of the issues](https://github.com/statamic/cms/issues/13442) we're running into as well. 🙂

File: tests/Integration/Http/ResourceTest.php (hunk 1 above)
Comment (cosmastech) [reply tests/Integration/Http/ResourceTest.php:97]: Tested against our codebase and appears to be working. Thanks!

Comment (zoispag) [reply tests/Integration/Http/ResourceTest.php:97]: It also fixes issues in our codebase. Thanks @crynobone
