### PR TITLE
[10.x] Use model cast when builder created updated at value

### LINKED ISSUE #47769: Cast on Updated At column not applied for rapid saves (i.e. unit tests)
### Laravel Version

10.13.2

### PHP Version

8.2.7

### Database Driver & Version

_No response_

### Description

_apologies for duplicating an unanswered discussion #47506 but I believe this is a bug requiring attention_

We are making use of a legacy database written for an ancient framework in Laravel. One "feature" of this framework is that integer unix timestamps are used for the updated_at column instead of datetime strings.

We can deal with this by setting `protected $dateFormat = 'U';` on the model classes however ideally we would like to use datetimes for application-specific time-related columns going forward so don't want to force the format on all new columns.

We wrote a cast to juggle the value from an instance of Carbon to `$carbon->timestamp` and all seemed well until we went to write unit tests for the functionality.

The tests failed because data was being truncated for the updated_at column as it was receiving a datetime string instead of the timestamp from the cast.

```
Warning: 1265 Data truncated for column 'updated_at' at row 1 (Connection: mysql, SQL: update `customers` set `name` = redacted, `customers`.`updated_at` = 2023-07-18 10:49:06 where `id` = 138)
```

I believe this is occurring here as it does not seem to check for casts before appending an updated_at value

https://github.com/laravel/framework/blob/31b3d29cea6974674da5296a30442f4d803f28e2/src/Illuminate/Database/Eloquent/Builder.php#L1140

I think that updated_at is not marked as dirty because the value has not changed because the change has been within the same second as the creation or another update.

A quick resolution to this problem within tests is to include `$this->travelTo(now()->addMinute());` before every change made to a particular model so that the casted value is picked up with the dirty attributes

https://github.com/laravel/framework/blob/31b3d29cea6974674da5296a30442f4d803f28e2/src/Illuminate/Database/Eloquent/Model.php#L1212

Obviously this is not possible within the main application so this problem may occur there if there are saves within the same second from different parts of the code.

_if you create an entity in the database and then update the entity via a queued job then you encounter this error and must delay the job being dispatched_

I am unsure as to whether the resolution is for the builder to cast the value before appending it or for any dirty attributes check to always include the updated_at value if any other changed values are present.

### Steps To Reproduce

Have the following database schema and code

```sql
CREATE TABLE `customers` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `customer_name` varchar(100) DEFAULT NULL,
  `created_at` int(11) DEFAULT NULL,
  `updated_at` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```
```php
<?php

namespace App\Models;

use App\Casts\UnixTimeStampToCarbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    use HasFactory;

    protected $casts = [
        'created_at' => UnixTimeStampToCarbon::class,
        'updated_at' => UnixTimeStampToCarbon::class,
    ];
}
```

```php
<?php

namespace App\Casts;

use Carbon\Carbon;
use Illuminate\Contracts\Database\Eloquent\CastsAttributes;

/**
 * @implements CastsAttributes<Carbon|null, Carbon>
 */
class UnixTimeStampToCarbon implements CastsAttributes
{
    /**
     * Cast the given value.
     *
     * @param  \Illuminate\Database\Eloquent\Model  $model
     * @param  mixed  $value
     * @param  array<mixed>  $attributes
     * @return Carbon|null
     */
    public function get($model, string $key, $value, array $attributes)
    {
        return $value ? Carbon::createFromTimestampUTC($value) : null;
    }

    /**
     * Prepare the given value for storage.
     *
     * @param  \Illuminate\Database\Eloquent\Model  $model
     * @param  mixed $value
     * @param  array<mixed>  $attributes
     * @return int|float|string|null
     */
    public function set($model, string $key, $value, array $attributes)
    {
        if (is_string($value) || is_numeric($value) || ($value instanceof \DateTime && ! $value instanceof Carbon)) {
            $value = Carbon::parse($value);
        }

        return $value ? $value->timestamp : null;
    }
}
```
```php
<?php

namespace Tests\Feature\Http\Controllers;

use App\Models\Customer;
use App\Models\User;
use Illuminate\Contracts\Auth\Authenticatable;
use Tests\TestCase;

class CustomerControllerTest extends TestCase
{
    public function testUpdate(): void
    {
        /** @var Authenticatable|User $user */
        $user = User::factory()
            ->create();

        $customer = Customer::factory()->create([
            'customer_name' => 'Test Customer',
        ]);

        // this is required because the customer has just been created
        $this->travelTo(now()->addMinute());
        $response = $this
            ->actingAs($user)
            ->put(
                route('customers.update', $customer),
                [
                    'customer_name' => 'Updated Customer',
                ]
            );
        $response->assertSessionHasNoErrors();
        $response->assertRedirect(route('customers.index'));

        $customer->refresh();
        $this->assertSame('Updated Customer', $customer->customer_name);
    }
}
```

### PR DESCRIPTION
**Pull request by timacdonald**
fixes #47769

If a model is using a cast on the `updated_at` column, it is not respected when the **eloquent builder** creates the `updated_at` value.

```php
<?php

namespace App\Models;

use App\Casts\UnixTimeStampToCarbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    use HasFactory;

    protected $casts = [
        'created_at' => UnixTimeStampToCarbon::class,
        'updated_at' => UnixTimeStampToCarbon::class,
    ];
}
```

When updating a model, in most cases the `updated_at` value is created in the **eloquent model**, where the cast is respected as expected.

When the model creates the value the builder receives the `updated_at` value in the array it is asked to put into the database. When this happens, everything is good.

When the value of `updated_at` has not changed, i.e. the time is the same as last time it was updated - which you might find happens in a unit test - the `updated_at` is not marked as "dirty" and the model does not pass the `updated_at` column through to the builder.

In this case, the builder manually creates and adds the `updated_at` value to the array it is putting into the database.

When the builder creates the `updated_at` value it does not use any casts that are in place on the model for the `updated_at` column.

For timestamp only values, if you are storing the `updated_at` as an integer, as per #47769, and not other dates, the value attempted to be insert into the database will be `2020-01-01 00:00:00` formatted and MySQL will throw an exception as it is expecting an integer.

## Performance implications

I ran some benchmarks using 10,000 iterations.

## Updated at set by the builder, i.e. time has not progressed

If you do not have a cast in place for the `updated_at` column: there is no change ☑️

If you do have a cast in place for the `updated_at` column: `0.006ms` > `0.02ms` ⬇️

## Updated at set by the model, i.e. time has progressed

`0.006ms` > `0.0ms` (micro optimisation) ⬆️

So the implications are only for the cases where you have a cast in place and time has not progressed, which I would guess is 99.999999999999% of the time in a unit test and not going to impact an actual user.

### CODE REVIEW

File: src/Illuminate/Database/Eloquent/Builder.php [hunk 1]
```diff
@@ -1139,10 +1139,15 @@ protected function addUpdatedAtColumn(array $values)
...
-        );
+        if (! array_key_exists($column, $values)) {
+            $timestamp = $this->model->freshTimestampString();
+
+            if ($this->model->hasCast($column)) {
+                $timestamp = $this->model->newInstance([$column => $timestamp])->getAttributes()[$column];
+            }
+
+            $values = array_merge([$column => $timestamp], $values);
+        }
```
Comment (timacdonald) [inline src/Illuminate/Database/Eloquent/Builder.php:1150]: The outer `array_key_exists` check is a micro optimisation here, as per the performance section of the description. It can be safely removed if we don't want it.

**Comment by willpower232** [comment]
Makes sense to me and has @driesvints vote too https://github.com/laravel/framework/issues/47769#issuecomment-1651656631

Do you need me to patch my code and confirm its all hunky dory?

**Comment by timacdonald** [comment]
@willpower232 that would be super. The test I added replicates the exception and scenario you were hitting, so either way I think this PR makes sense.

However, I would absolutely love for you to actually test this. Let's mark as draft until you can confirm.

File: src/Illuminate/Database/Eloquent/Builder.php [hunk 2]
```diff
@@ -1139,10 +1139,19 @@ protected function addUpdatedAtColumn(array $values)
...
+            if (
+                $this->model->hasSetMutator($column)
+                || $this->model->hasAttributeSetMutator($column)
+                || $this->model->hasCast($column)
+            ) {
+                $timestamp = $this->model->newInstance([$column => $timestamp])->getAttributes()[$column];
+            }
+
+            $values = array_merge([$column => $timestamp], $values);
+        }
```
Comment (timacdonald) [inline src/Illuminate/Database/Eloquent/Builder.php:1154]: The outer `array_key_exists` check is a micro optimisation here, as per the performance section of the description. It can be safely removed if we don't want it.

**Comment by timacdonald** [comment]
Updated to fix for mutators / attributes

**Comment by willpower232** [comment]
I swapped your repo and branch in for the framework folder in a testing copy and got the following error from running tests

<details>
<summary>
Undefined array key "updated_at" (expand for stack trace)
</summary>

```
Undefined array key "updated_at"

/var/www/vendor/laravel/framework/src/Illuminate/Testing/TestResponse.php:148
/var/www/tests/Feature/Http/Controllers/CustomerControllerTest.php:164
/var/www/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestCase.php:174

3) Tests\Feature\Http\Controllers\UserControllerTest::testUpdateUserRoles
Expected response status code [201, 301, 302, 303, 307, 308] but received 500.
Failed asserting that false is true.

The following exception occurred during the last request:

ErrorException: Undefined array key "updated_at" in /var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:1150
Stack trace:
#0 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(254): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Undefined array...', '/var/www/vendor...', 1150)
#1 /var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1150): Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(2, 'Undefined array...', '/var/www/vendor...', 1150)
#2 /var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1042): Illuminate\Database\Eloquent\Builder->addUpdatedAtColumn(Array)
#3 /var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1213): Illuminate\Database\Eloquent\Builder->update(Array)
#4 /var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1130): Illuminate\Database\Eloquent\Model->performUpdate(Object(Illuminate\Database\Eloquent\Builder))
#5 /var/www/app/Http/Controllers/UserController.php(45): Illuminate\Database\Eloquent\Model->save()
<further lines removed for brevity>
```
</details>

```php
$timestamp = $this->model->newInstance([$column => $timestamp])->getAttributes()[$column];
```

I presume this means that the attribute isn't returned by getAttributes for some reason? Am I missing a change to the cast class we have?

**Comment by timacdonald** [comment]
@willpower232 give it another shot, if you don't mind. Didn't account for attribute guarding.

**Comment by willpower232** [comment]
Aha that seems to be correct, its passing all my tests now :tada: 

image

**Comment by timacdonald** [comment]
Thanks for testing this, @willpower232

**Comment by willpower232** [comment]
No problemo, thanks for figuring it all out!

**Comment by maxxscho** [comment]
@timacdonald  I have a mutator on the `updated_at` column which prevents setting `updated_at` on creating a model. If I update a model I get the following error:

```
ErrorException: Undefined array key "updated_at"
../vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:254
../vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:1167
../vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:1057
../vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1213
../vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1130
```

Creating a models works as expected. Do you have any idea?

**Comment by timacdonald** [comment]
I’m very sorry, I didn’t see a notification for your message @maxxscho 

As @willpower232 asked, if we could please see the mutator we can take a look. It might be good to open an issue and provide the mutator so I can take a look. 

Mention me in the issue and I will jump in.

**Comment by maxxscho** [comment]
@willpower232 sure.

```php
public function setUpdatedAtAttribute($value): void
{
    if (! $this->id) {
        return;
    }

    $this->updated_at = $value;
}
```

Basically only if the model has an ID (it has been persisted in the DB) the `updated_at` attribute should get a value (this peace of the software is very old so it might look a little bit odd 😄 )

**Comment by willpower232** [comment]
Your idea makes sense but shouldn't it be 

```php
$this->attributes['updated_at'] = $value;
```

**Comment by timacdonald** [comment]
We can likely resolve the issue with 

```php
$timestamp = $this->model->newInstance()
    ->forceFill([$column => $timestamp])
    ->getAttributes()[$column] ?? $timestamp;
```

Funnily enough I actually had this in the original version but removed it cause I couldn’t think of when it would happen - but now I know!

We need to add a test to validate the fix and ensure it doesn’t break again in the future.

I’m on my phone and not in till tomorrow.

will ping @jbrooksuk @driesvints to see if they have time to PR a test with the above fix for the Tuesday release 🙏

**Comment by maxxscho** [comment]
@timacdonald I quickly tried this fix and my tests are green again.

**Comment by driesvints** [comment]
@maxxscho I'm having a hard time reproducing this in a test. Can you share your full model please?

**Comment by maxxscho** [comment]
@driesvints of course.

```php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Builder;

class UserRunStreak extends BaseModel
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'user_id',
        'current',
        'record',
        'updated_at',
    ];

    protected $casts = [
        'current' => 'integer',
        'record' => 'integer',
    ];

    /**
     * Set updated_at attribute only on updates, not create.
     */
    public function setUpdatedAtAttribute($value): void
    {
        if (! $this->id) {
            return;
        }

        $this->updated_at = $value;
    }

    /**
     * Increase current.
     */
    public function increaseCurrent(): void
    {
        $this->current += 1;
        $this->save();
    }

    /**
     * Increase record.
     */
    public function increaseRecord(): void
    {
        $this->record += 1;
        $this->save();
    }

    /**
     * Reset current.
     */
    public function resetCurrent(): void
    {
        $this->current = 0;
        $this->save();
    }

    /**
     * Scope query to filter active results.
     */
    public function scopeNotUpdatedFor24hours(Builder $query): Builder
    {
        return $query->where('updated_at', '<', Carbon::now()->subDay()->toDateTimeString());
    }
}
```

**Comment by driesvints** [comment]
@maxxscho do you somehow manually set the updated_at when creating a model?

**Comment by maxxscho** [comment]
@driesvints no, it's not set manually on creating. The reason for the mutator is to keep `updated_at` `null` on creating.

**Comment by driesvints** [comment]
I just have too few info to reproduce this sorry. Can you create a repo for me with an app that reproduces this?

```bash
laravel new bug-report --github="--public"
```

**Comment by driesvints** [comment]
Nvm, got it: https://github.com/laravel/framework/pull/48230. Thanks
