### PR TITLE
[12.x] Fix the `getCurrentlyAttachedPivots` wrong `morphClass` for morph to many relationships

### LINKED ISSUE #55698: morphClass property not set on custom MorphPivot classes
### Laravel Version

12.10.0+ from quick testing

### PHP Version

8.4

### Database Driver & Version

irrelevant

### Description

As part of the recent changes to relations, it seems there's a regression in handling polymorphic pivots.

We're seeing `$this->morphClass` being set to null on a class extending `MorphPivot` (being used for the relation).

Stack trace:
```
  1   src/ResourceSyncing/TriggerSyncingEvents.php:88
  2   src/ResourceSyncing/TriggerSyncingEvents.php:101
  3   src/ResourceSyncing/TriggerSyncingEvents.php:65
  4   src/ResourceSyncing/TriggerSyncingEvents.php:49
  5   vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:461
  6   vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:288
  7   vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:268
  8   vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:234
  9   vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php:224
  10  vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1473
  11  vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Concerns/AsPivot.php:133
  12  vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/MorphPivot.php:59
  13  vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php:476
  14  vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php:433
```
This seems to be specifically when **detaching**.

Haven't had a chance to look into this in depth, but it seems to be caused by https://github.com/laravel/framework/pull/55490, reverting [`InteractsWithPivotTable`](https://github.com/laravel/framework/blob/12.x/src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php) to the previous commit (99e1ceb6044db988b904f2940d9510299cbe9d1d) fixes this.

### Steps To Reproduce

Don't have a confirmed minimal repro, this is part of more complex logic, however using a custom `MorphPivot` (`using()` on a relation), inside that doing:
```php
public static function booted()
{
    static::deleting(function (self $pivot) {
        dd($pivot->morphClass);
    });
}
```
should produce null on the latest commit but a class string on 99e1ceb6044db988b904f2940d9510299cbe9d1d.

### PR DESCRIPTION
**Pull request by amir9480**
Fixes #55698

### CODE REVIEW

File: src/Illuminate/Database/Eloquent/Relations/MorphToMany.php [hunk 1]
```diff
@@ -121,13 +121,14 @@ public function getRelationExistenceQuery(Builder $query, Builder $parentQuery,
     }
 
     /**
-     * Get the pivot models that are currently attached.
+     * Get the pivot models that are currently attached, filtered by related model keys.
      *
-     * @return \Illuminate\Support\Collection<int, TPivotModel>
+     * @param  mixed  $ids
+     * @return \Illuminate\Support\Collection
```
Comment (shaedrich) [inline src/Illuminate/Database/Eloquent/Relations/MorphToMany.php:127]: Shouldn't this stay
```suggestion
     * @return \Illuminate\Support\Collection<int, TPivotModel>
```
? If there is trouble with static analysis, the [PHPDoc comment in `InteractsWithPivotTable`](https://github.com/laravel/framework/blob/12.x/src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php#L496) should be adjusted accordingly

**Comment by amir9480** [comment]
@shaedrich Thanks, I'm not sure how to document generic type in the `InteractsWithPivotTable.php`, feel free to send as a new PR
