### PR TITLE
[6.x] Vendor publish improvement

### LINKED ISSUE #23169: Vendor:publish needs to be more informative
- Laravel Version: 5.5.32 (does not really matter)
- PHP Version: any

### Description:

When running `php artisan vendor:publish` for a specific vendor to publish its config I got nice green successful message:

"Publishing complete".

But nothing was actually published. After debugging I found out that the system failed to determine publishing paths and there was nothing to publish actually. 

Therefore simple successful message is not enough for such case. It would be nice to tell, that nothing was published and probably the reason why.

### Steps To Reproduce:

Run `vendor:publish` for a vendor with errors in `publishes` declaration or with some invalid options (vendor without namespace or something like that). You just need to make sure that the system won't actually publish anything.

### PR DESCRIPTION
**Pull request by yakryder**
Fixes #23169

### CODE REVIEW

File: src/Illuminate/Foundation/Console/VendorPublishCommand.php [hunk 1]
```diff
@@ -33,6 +33,14 @@ class VendorPublishCommand extends Command
      */
     protected $tags = [];
 
+    /**
+     * Boolean describing the status of files. Initially set to false, it changes
+     * to true if any file is successfully published.
+     *
+     * @var bool
+     */
+    protected $published;
```
Comment (netpok) [inline src/Illuminate/Foundation/Console/VendorPublishCommand.php]: Couldn't this be just a local variable where it's used?

File: src/Illuminate/Foundation/Console/VendorPublishCommand.php [hunk 2]
```diff
@@ -159,6 +169,13 @@ protected function publishTag($tag)
     {
         foreach ($this->pathsToPublish($tag) as $from => $to) {
             $this->publishItem($from, $to);
+
+            $this->published = true;
+        }
+        if ($this->published) {
```
Comment (netpok) [inline src/Illuminate/Foundation/Console/VendorPublishCommand.php]: A newline could be here to improve readability.
