### PR TITLE
[11.x] Fix incorrect bindings in DB::update when using a collection as a value

### LINKED ISSUE #53226: Incorrect bindings in DB::update when using a collection as a value
### Laravel Version

11.26.0

### PHP Version

8.3.12

### Database Driver & Version

MySQL

### Description

When using a collection as a column value in DB::update, the wrong bindings are applied.
Before Laravel 11, the collection would be turned into a string (which still is the case if you use an array) but now all the values of the collection is spread and added to the bindings array.

The change seems to have come from this pull request with the added `Arr::flatten`: https://github.com/laravel/framework/pull/50030

Example:

- `DB::table('foo')->update(['bar' => collect(['a', 'b'])]);`
- gives the error ```SQLSTATE[HY093]: Invalid parameter number (Connection: mysql, SQL: update `foo` set `bar` = a)```
- Expected is that the collection should become a (json)string `'["a","b"]'` and be saved in the database.

With an array it still works (and this is how it was in version < 11 with collections)
- `DB::table('foo')->update(['bar' => ['a', 'b']]);`
- correctly updates with: ```update `foo` set `bar` = ["a","b"]```

### Steps To Reproduce

- Use Laravel 11.x
- Create (example) table:
```<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void
    {
        Schema::create('foo', function (Blueprint $table) {
            $table->id();
            $table->string('bar');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('foo');
    }
};
```
- `php artisan tinker`
- `DB::table('foo')->update(['bar' => collect(['a', 'b'])]);`

### PR DESCRIPTION
**Pull request by crynobone**
fixes #53226

### CODE REVIEW

File: src/Illuminate/Database/Query/Builder.php [hunk 1]
```diff
@@ -3848,7 +3848,11 @@ public function update(array $values)
 
         $values = collect($values)->map(function ($value) {
             if (! $value instanceof Builder) {
-                return ['value' => $value, 'bindings' => $value];
+                return ['value' => $value, 'bindings' => match (true) {
+                    $value instanceof Collection => $value->toArray(),
```
Comment (rodrigopedra) [inline src/Illuminate/Database/Query/Builder.php:3852]: Why not use `$value->all()` and skip the implicit `array_map` call inside to `Collection@toArray()`?

Comment (rodrigopedra) [reply src/Illuminate/Database/Query/Builder.php:3852]: Also, I'd change the check to `$value instanceof Enumerable`, so `$value->all()` also covers `LazyCollection` instances

Comment (crynobone) [reply src/Illuminate/Database/Query/Builder.php:3852]: It might not be even worth it to pursue these changes. Using Collection as value is not in the docs (unless someone can share the URL) and Postgres/SQLServer would require different syntax to store JSON

Comment (rodrigopedra) [reply src/Illuminate/Database/Query/Builder.php:3852]: You're right. And it is easy enough for someone to just add `collect(...)->all()` on the call-site

Comment (Sopamo) [reply src/Illuminate/Database/Query/Builder.php:3852]: I think it's problematic though that the behaviour is somewhat undefined when passing in a collection (or at least very unexpected), especially as I think many devs don't actively differentiate between arrays and collections in Laravel as much Laravel functionality behaves the same no matter what you pass in.
