### PR TITLE
[10.x] Fix postgreSQL reserved word column names w/ guarded attributes broken in native column attributes implementation

### LINKED ISSUE #48870: PostgreSQL reserved word column names w/ guarded attributes broken in native column attributes implementation
### Laravel Version

10.30.0

### PHP Version

8.2.11

### Database Driver & Version

PostgreSQL 15.1

### Description

The native column attributes implementation introduced in https://github.com/laravel/framework/pull/48357 has broken inserts using Postgres models with guarded attributes and column names matching PostgreSQL reserved words in my application.

The [`compileColumns()`](https://github.com/laravel/framework/commit/85a514632e410ae8f90c2b32c79a2788ba9d1076#diff-653f90bd1ee0a1c7c7970912484e98c8bbd30c8e9a3d2f544d53834d54e7ce7cR104) query in the Postgres schema grammar makes use of PostgreSQL's `quote_ident()` function which quotes reserves words. 

`SELECT quote_ident('foo') as value;` -> `foo`
`SELECT quote_ident('end') as value;` -> `"end"`

This is causing the [`GuardsAttributes`](https://github.com/laravel/framework/blob/10.x/src/Illuminate/Database/Eloquent/Concerns/GuardsAttributes.php#L218) trait to improperly detect fillable columns. 

Changing `select quote_ident(a.attname) as name` to `select a.attname as name` in the Postgres Grammar resolves the issue, but I'm not sure if there are other downstream consequences to that. 

Ex:

Given a table like the following:

```php
Schema::create('my_table', function (Blueprint $table) {
   $table->id();
   $table->string('label');
   $table->timestamp('start');
   $table->timestamp('end');
   $table->boolean('analyze');
});
```

The output of `Schema::getColumns('my_table');` is the following.

```php
array:5 [
  0 => array:8 [
    "name" => "id"
    "type_name" => "int8"
    "type" => "bigint"
    "collation" => null
    "nullable" => false
    "default" => null
    "auto_increment" => true
    "comment" => null
  ]
  1 => array:8 [
    "name" => "label"
    "type_name" => "varchar"
    "type" => "character varying(255)"
    "collation" => null
    "nullable" => false
    "default" => null
    "auto_increment" => false
    "comment" => null
  ]
  2 => array:8 [
    "name" => "start"
    "type_name" => "timestamp"
    "type" => "timestamp(0) without time zone"
    "collation" => null
    "nullable" => false
    "default" => null
    "auto_increment" => false
    "comment" => null
  ]
  3 => array:8 [
    "name" => ""end""
    "type_name" => "timestamp"
    "type" => "timestamp(0) without time zone"
    "collation" => null
    "nullable" => false
    "default" => null
    "auto_increment" => false
    "comment" => null
  ]
  4 => array:8 [
    "name" => ""analyze""
    "type_name" => "bool"
    "type" => "boolean"
    "collation" => null
    "nullable" => false
    "default" => null
    "auto_increment" => false
    "comment" => null
  ]
]
```

### Steps To Reproduce

```php
class LaravelTest extends TestCase
{
    public function testInsertRecordWithReservedWordFieldName()
    {
        Schema::create('my_table', function (Blueprint $table) {
            $table->id();
            $table->string('label');
            $table->timestamp('start');
            $table->timestamp('end');
            $table->boolean('analyze');
        });

        $model = new class extends \Illuminate\Database\Eloquent\Model {
            protected $table = 'my_table';
            protected $guarded = ['id'];
            public $timestamps = false;
        };
        
        $result = $model::query()->create([
            'label' => 'test',
            'start' => '2023-01-01 00:00:00',
            'end' => '2024-01-01 00:00:00',
            'analyze' => true,
        ]);

        $this->assertTrue($result->exists);
    }
}
```

Fails with error...

```
SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "end" of relation "my_table" violates not-null constraint
DETAIL:  Failing row contains (1, test, 2023-01-01 00:00:00, null, null). (Connection: pgsql, SQL: insert into "my_table" ("label", "start") values (test, 2023-01-01 00:00:00) returning "id")
```

Passes under Laravel 10.29.0.

### PR DESCRIPTION
**Pull request by hafezdivandari**
Fixes #48870

The solution was to unquote quoted reserved names on PostgreSQL processor, [the same approach is used on Doctrine DBAL](https://github.com/doctrine/dbal/blob/45941c67dd0505dab2fb970786d93055b7cbd2b6/src/Schema/AbstractAsset.php#L154-L169).

Thanks @crynobone and @damiantw for reporting the issue.

### CODE REVIEW

File: tests/Integration/Database/EloquentModelTest.php [hunk 1]
```diff
@@ -94,6 +94,35 @@ public function testDiscardChanges()
...
     }
+
+    public function testInsertRecordWithReservedWordFieldName()
+    {
+        Schema::create('actions', function (Blueprint $table) {
+            $table->id();
+            $table->string('label');
+            $table->timestamp('start');
+            $table->boolean('analyze');
+        });
```
Comment (crynobone) [inline tests/Integration/Database/EloquentModelTest.php:105]: isn't the issue was with `end` column?

**Review by crynobone — CHANGES_REQUESTED** [review]

File: tests/Integration/Database/EloquentModelTest.php (hunk 1 above)
Comment (hafezdivandari) [reply tests/Integration/Database/EloquentModelTest.php:106]: I brought 'end' back in a commit but The `analyze` is also a keyword on PostgreSQL: https://www.postgresql.org/docs/current/sql-keywords-appendix.html
I removed 'end' because of unrelated MySQL 5.7 test failure when creating a table with 2 not null timestamp columns.

**Review by crynobone — COMMENTED** [review]
Looks good

**Review by crynobone — APPROVED** [review]
