### PR TITLE
[10.x] Fixes retrying failed jobs causes PHP memory exhaustion errors when dealing with thousands of failed jobs

### LINKED ISSUE #49185: Retrying failed jobs causes PHP memory exhaustion errors when dealing with thousands of failed jobs
### Laravel Version

10.34.2

### PHP Version

8.1.26

### Database Driver & Version

_No response_

### Description

A project I'm working on has 300k failed jobs. When I try to run `artisan queue:retry` it results in an error...

```PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted```

After looking into how the `RetryCommand` works, I realized that rather than querying just the IDs from the failed jobs table, it loads the entire table and then plucks the ID column. No matter how high I set the memory limit, the server won't be able to handle loading all 300k failed jobs into memory.

This is a very inefficient way to load the failed job IDs. Any thoughts on how this could be improved without breaking anything?

### Steps To Reproduce

* Populate the `failed_jobs` table with 300k failed jobs
* Run `php artisan queue:retry`

### PR DESCRIPTION
**Pull request by crynobone**
fixes laravel/framework#49185

### CODE REVIEW

**Review by driesvints — APPROVED** [review]

File: src/Illuminate/Queue/Failed/DatabaseUuidFailedJobProvider.php [hunk 1]
```diff
@@ -67,6 +67,21 @@ public function log($connection, $queue, $payload, $exception)
...
+    /**
+     * Get the IDs of all of the failed jobs.
+     *
+     * @param  string|null  $queue
+     * @return array
+     */
+    public function ids($queue = null)
+    {
+        return $this->getTable()
+            ->when(! is_null($queue), fn ($query) => $query->where('queue', $queue))
```
Comment (dammy001) [inline src/Illuminate/Queue/Failed/DatabaseUuidFailedJobProvider.php:79]: I think it's necessary this queue column is indexed @crynobone @taylorotwell

**Comment by mrwilbroad** [comment]
Problem fixed ✅
