### PR TITLE
[12.x] Fix `illuminate/database` usage as standalone package

### LINKED ISSUE #55272: Class Illuminate\Database\Eloquent\Model use a missing dependency
### Laravel Version

12.7.2

### PHP Version

8.4

### Database Driver & Version

_No response_

### Description

Hello,

On different projects, we are using eloquent as standalone package.
Everything was working well since the release v12.6.0.

Since the version  v12.7.x, the class Model is using a new trait coming from the package illuminate/http.

However this package is no part of the package required by database package.

Could you please add illuminate/http as required package into composer file ?

### Steps To Reproduce

Just check the composer file & the line 20 of class Illuminate\Database\Eloquent\Model

### PR DESCRIPTION
**Pull request by crynobone**
Avoid regression issue introduced in https://github.com/laravel/framework/pull/55107

fixes https://github.com/laravel/framework/issues/55272

### CODE REVIEW

File: src/Illuminate/Collections/Traits/TransformsToResourceCollection.php [hunk 1]
```diff
@@ -3,7 +3,6 @@
 namespace Illuminate\Support\Traits;
 
 use Illuminate\Database\Eloquent\Model;
-use Illuminate\Http\Resources\Json\JsonResource;
 use Illuminate\Http\Resources\Json\ResourceCollection;
```
Comment (AndrewMast) [inline src/Illuminate/Collections/Traits/TransformsToResourceCollection.php:6]: Shouldn't `ResourceCollection` also be removed?

Comment (crynobone) [reply src/Illuminate/Collections/Traits/TransformsToResourceCollection.php:6]: CleanShot 2025-04-07 at 15 43 27

There's wouldn't be an issue unless you are explicitly calling `toResource()` method, and if you do you definitely need to require `illuminate/http`
