### PR TITLE
[11.x] Move Defer classes to Support component and add `Illuminate\Support\defer` function

### LINKED ISSUE #52800: Conflict with Swoole's `defer()` function in Laravel
### Laravel Version

11.23.5

### PHP Version

8.3.11

### Database Driver & Version

_No response_

### Description

I am currently using the Swoole 5.1.1 extension, which has implemented the `defer()` function since version 4.2.9. This function accepts a Closure as its first argument, leading to a conflict with Laravel's newly introduced `defer()` helper.

The current implementation of Laravel's `defer()` involves using two classes, which can be a bit cumbersome to call directly. It would be helpful to consider providing a more convenient alternative, such as a dedicated Facade or another abstraction, to avoid conflicts with Swoole's existing functionality and simplify usage.

Please note the following classes:

- `Illuminate\Concurrency\ForkDriver`
- `Illuminate\Concurrency\ProcessDriver`
- `Illuminate\Concurrency\SyncDriver`

These classes internally call the `defer()` function, which will cause conflicts when using the Swoole extension.

### Steps To Reproduce

Enable the Swoole extension and attempt to use the `defer()` helper function

### PR DESCRIPTION
**Pull request by crynobone**
Also avoid using global `defer()` function when it can be defined in environment such as Swoole

### CODE REVIEW

File: src/Illuminate/Contracts/Concurrency/Driver.php [hunk 1]
```diff
@@ -3,7 +3,7 @@
 namespace Illuminate\Contracts\Concurrency;
 
 use Closure;
-use Illuminate\Foundation\Defer\DeferredCallback;
+use Illuminate\Concurrency\Defer\DeferredCallback;
```
Comment (crynobone) [inline src/Illuminate/Contracts/Concurrency/Driver.php:6]: @taylorotwell This might be a breaking change but as Concurrency is still in beta we might allow it.

File: src/Illuminate/Concurrency/composer.json [hunk 2]
```diff
@@ -21,7 +21,10 @@
     "autoload": {
         "psr-4": {
             "Illuminate\\Support\\": ""
```
Comment (rodrigopedra) [inline src/Illuminate/Concurrency/composer.json:23]: It seems the autoload is wrong. Shouldn't it be: 

```json
"psr-4": {
    "Illuminate\\Concurrency\\": ""
}
```

**Comment by rodrigopedra** [comment]
Doesn't the `require` section on `composer.json` missing some components? 

For example, `illuminate/support`?

**Comment by taylorotwell** [comment]
@crynobone personally I would maybe put this in Support instead of Concurrency.

**Comment by crynobone** [comment]
@taylorotwell moved to Support
