### PR TITLE
[5.1] Fix for tagged cache events

### LINKED ISSUE #10423: Tagged caches don't fire cache events.
Laravel v5.1

Tagged caches don't fire the cache events listed here: http://laravel.com/docs/5.1/cache#cache-events

Non-tagged caches use the Repository class: https://github.com/laravel/framework/blob/5.1/src/Illuminate/Cache/Repository.php#L95-L108
```
    public function get($key, $default = null)
    {
        $value = $this->store->get($key);
        if (is_null($value)) {
            $this->fireCacheEvent('missed', [$key]);
            $value = value($default);
        } else {
            $this->fireCacheEvent('hit', [$key, $value]);
        }
        return $value;
    }
```

Tagged caches extend from the TaggedCache class: https://github.com/laravel/framework/blob/5.1/src/Illuminate/Cache/TaggedCache.php#L57-L62
```
    public function get($key, $default = null)
    {
        $value = $this->store->get($this->taggedItemKey($key));
        return ! is_null($value) ? $value : value($default);
    }
```

I can have a go at adding it in and create a PR with these changes, if you'd like me to. I haven't yet as I saw https://github.com/laravel/framework/issues/9967 and figured that if it was being fixed then it this one can possibly be fixed at the same time. :-)

### PR DESCRIPTION
**Pull request by willrowe**
This is a possible way to fix #10423. The problem lies in the `TaggedCache` class which calls the stores directly, bypassing the `Repository` class entirely, which contains all the code for triggering events.

The approach I took in fixing this was to have the `TaggedCache` class extend the `Repository` class and then call the corresponding methods in the parent using the generated cache key for the tags used. This way the code for firing the events is not duplicated.

When an event is fired from a tagged cache an array of the tag names is also passed in the payload now. 

This PR is meant to demonstrate what the issue is and a possible solution. This also has a set of new tests which determine whether the expected events are fired for both tagged and non-tagged caches.

### CODE REVIEW

File: src/Illuminate/Cache/TaggedCache.php [hunk 1]
```diff
@@ -32,69 +22,50 @@ class TaggedCache implements Store
...
-     *
-     * @param  string  $key
-     * @return bool
+     * {@inheritdoc}
      */
-    public function has($key)
+    protected function fireCacheEvent($event, $payload)
     {
-        return ! is_null($this->get($key));
+        if (preg_match('/^'.sha1($this->tags->getNamespace()).':(.*)$/', $payload[0], $matches) === 1) {
```
Comment (ArjanSchouten) [inline src/Illuminate/Cache/TaggedCache.php]: So ```$matches[1]``` may be empty?

Comment (willrowe) [inline src/Illuminate/Cache/TaggedCache.php]: It appears that it is possible to use an empty string as a key.

**Comment by willrowe** [comment]
I have also come up with a slight variation where a method called `itemKey` is added to the `Repository` class and is called on the key in the methods which interact with the cache stores. This means that the `itemKey` method can be overridden by the `TaggedCache` class. This variation would seem to be a more elegant solution and avoid the hackiness that is in the `fireCacheEvent` method of the `TaggedCache` class.

**Comment by willrowe** [comment]
I just added a commit with the other variation.

File: src/Illuminate/Cache/Repository.php [hunk 2]
```diff
@@ -349,6 +387,17 @@ protected function getMinutes($duration)
     }
 
     /**
+     * Get the key to be used with the store.
+     *
+     * @param  string $key
```
Comment (GrahamCampbell) [inline src/Illuminate/Cache/Repository.php]: cs

**Comment by GrahamCampbell** [comment]
@taylorotwell I still wonder if this is best targetted at 5.2.

**Comment by willrowe** [comment]
Just let me know if I need to retarget this at 5.2.

**Comment by GrahamCampbell** [comment]
Bit late for that now. Will either be 5.1, or 5.3 now.

**Comment by taylorotwell** [comment]
If it's a true bug fix it could go on 5.2?

**Comment by GrahamCampbell** [comment]
Good luck with the branch merge. :trollface:

**Comment by taylorotwell** [comment]
I got it merged. @willrowe one thing I'm kind of curious about is you have no idea from the event if the given "key" was a tagged key or not... is that OK and expected?

**Comment by willrowe** [comment]
@taylorotwell a list of the tags that were used is appended to the event payload [here](https://github.com/laravel/framework/commit/679da7059801fb350f6a1443ad1e919355b06e3f#diff-f7407eeeb7ec42d3f5f6d341a44e3c03L38). In 5.1 this works fine and will automatically pass the list of tags to the event listener. In 5.2 an additional parameter will need to be added to the event classes and passed to them [here](https://github.com/laravel/framework/commit/679da7059801fb350f6a1443ad1e919355b06e3f#diff-f7407eeeb7ec42d3f5f6d341a44e3c03L38).

**Comment by taylorotwell** [comment]
​So can you show me how I would access the tags from the event in some
sample code?​

**Comment by willrowe** [comment]
A listener class could look something like this:
```php
namespace App\Listeners;

use Illuminate\Cache\Events\CacheHit;

class LogUserCacheHit
{
    /**
     * Create the event listener.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Handle the event.
     *
     * @param  Illuminate\Cache\Events\CacheHit  $event
     * @return void
     */
    public function handle(CacheHit $event)
    {
        if (in_array('user', $event->tags)) {
            Log::info('User ' . $event->key . ' was retrieved from the cache.');
        }
    }
}
```

**Comment by taylorotwell** [comment]
OK can you make a PR to actually add that parameter to the events and such?

**Comment by willrowe** [comment]
Sure, I'll submit one over the weekend..
