### PR TITLE
[9.x] Include full stack trace in deprecation

### LINKED ISSUE #42189: Deprecations log missing the trace
- Laravel Version: 9.10.0
- PHP Version: 8.1.5

### Description:
Deprecation logs look like this, making it impossible to debug in some cases:
```log
pipeline.WARNING: mb_substr(): Passing null to parameter #1 ($string) of type string is deprecated in /app/vendor/laravel/framework/src/Illuminate/Support/Str.php on line 944  
pipeline.WARNING: mb_substr(): Passing null to parameter #1 ($string) of type string is deprecated in /app/vendor/laravel/framework/src/Illuminate/Support/Str.php on line 944  
pipeline.WARNING: mb_strtoupper(): Passing null to parameter #1 ($string) of type string is deprecated in /app/vendor/laravel/framework/src/Illuminate/Support/Str.php on line 787 
```

It's missing the stack trace, dissimilar to the rest of the exceptions & PHP errors.

### Steps To Reproduce:

1. Clean install Laravel
2. Configure the deprecations logs [as per documentation](https://laravel.com/docs/9.x/logging#logging-deprecation-warnings) by setting an .env variable: `LOG_DEPRECATIONS_CHANNEL=stack`
3. Trigger any PHP deprecation: `str_replace(null, '', '')`
4. See a deprecation log without any stack trace in the log, besides the specific file/line where it occurred: `pipeline.WARNING: str_replace(): Passing null to parameter #1 ($search) of type array|string is deprecated in /app/some/file.php on line 123`

### PR DESCRIPTION
**Pull request by oprypkhantc**
Closes #42189

Adds full stack trace into deprecations log, similar to other PHP errors.

### CODE REVIEW

File: src/Illuminate/Foundation/Bootstrap/HandleExceptions.php [hunk 1]
```diff
@@ -79,12 +79,13 @@ public function handleError($level, $message, $file = '', $line = 0, $context =
...
      * Reports a deprecation to the "deprecations" logger.
      *
+     * @param  int  $level
      * @param  string  $message
      * @param  string  $file
      * @param  int  $line
      * @return void
      */
-    public function handleDeprecation($message, $file, $line)
+    public function handleDeprecation($level, $message, $file, $line)
```
Comment (GrahamCampbell) [inline src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:88]: This is a major breaking change. I think we have to wait until Laravel 10 to do this.

**Review by GrahamCampbell — CHANGES_REQUESTED** [review]

File: src/Illuminate/Foundation/Bootstrap/HandleExceptions.php (hunk 1 above)
Comment (oprypkhantc) [reply src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:88]: If otherwise the implementation looks fine to you, I'll change the signature back and just hardcode a `E_DEPRECATED` in `new ErrorException()`. I don't think it's used by ErrorException anyway.

**Comment by taylorotwell** [comment]
No plans to merge this right now. The stack trace is littered with exception handling noise.

**Comment by driesvints** [comment]
I've sent in a follow up to this to make it opt-in rather than enabled by default. We were concerned this could potentially bloat an app's log file by a lot.

https://github.com/laravel/framework/pull/42235
