### PR TITLE
[12.x] fix: one of many subquery constraints

### LINKED ISSUE #55155: Removed constraint causes all rows to be loaded
### Laravel Version

12.3.0

### PHP Version

8.4

### Database Driver & Version

MySQL

### Description

The removal of the constraints in this [PR](https://github.com/laravel/framework/pull/54759) causes all rows to be loaded into memory when giving a custom closure to the ofMany method.

### Steps To Reproduce

```php
public function report(?ReportType $reportType = ReportType::SOME_REPORT): HasOne
{
    return $this->hasOne(Report::class)->ofMany([], function (Builder $builder) use ($reportType) {
        $builder->where('report_type', $reportType);
    });
}
```

This will results in all reports with report_type x being loaded into memory as in framework version 12.1.0 it was just the rows that with the constraint.

12.1.0

Explain: Image

```sql
SELECT
	`reports`.*
FROM
	`reports`
	INNER JOIN (
		SELECT
			MAX(`reports`.`id`) AS `id_aggregate`,
			`reports`.`user_id`
		FROM
			`reports`
		WHERE
			`report_type` = ?
			AND `reports`.`user_id` = ?
			AND `reports`.`user_id` IS NOT NULL
			AND `reports`.`deleted_at` IS NULL
		GROUP BY
			`reports`.`user_id`
	) AS `reports` ON `reports`.`id_aggregate` = `reports`.`id`
	AND `reports`.`user_id` = `reports`.`user_id`
WHERE
	`reports`.`user_id` = ?
	AND `reports`.`user_id` IS NOT NULL
	AND `reports`.`deleted_at` IS NULL
LIMIT
	1

```

12.2.0
Explain: Image

```sql
SELECT
	`reports`.*
FROM
	`reports`
	INNER JOIN (
		SELECT
			MAX(`reports`.`id`) AS `id_aggregate`,
			`reports`.`user_id`
		FROM
			`reports`
		WHERE
			`report_type` = ?
			AND `reports`.`deleted_at` IS NULL
		GROUP BY
			`reports`.`user_id`
	) AS `reports` ON `reports`.`id_aggregate` = `reports`.`id`
	AND `reports`.`user_id` = `reports`.`user_id`
WHERE
	`reports`.`user_id` = ?
	AND `reports`.`user_id` IS NOT NULL
	AND `reports`.`deleted_at` IS NULL
LIMIT
	1
```

### PR DESCRIPTION
**Pull request by calebdw**
Hello!

This fixes the constraints on the OneOfMany subqueries.

### Regression

The regression occurred because the `addConstraints` call was removed from `CanBeOneOfMany::ofMany` as it was adding duplicate join/where clauses to the HasOneThroughOfMany relations. Upon further inspection, this was because the `HasOneOrMany::addConstraints` was using the query from `getRelationQuery()` whereas `HasOneOrManyThrough::addConstraints` was using the base `$this->query`.

### Additional Considerations
Edit: I decided to forgo the signature BC, perhaps that could be looked at in a future upgrade.

<details>

The `CanBeOneOfMany::ofMany` calls `addConstraints` to add the constraints to the subquery, however, this only added the constraints to the **first** subquery (the innermost query assigned to `$this->oneOfManySubQuery`. This means that queries with more than one aggregate will not have the constraints added to the other subqueries.

The fix for this is to move the `addConstraints` call and pass in the subquery so that the constraints are added to every subquery.

This can be seen in the following SQL (taken from the `testGlobalScopeIsNotAppliedWhenRelationIsDefinedWithoutGlobalScopeWithComplexQuery` test in  `DatabaseEloquentHasOneOfManyTest`):

```diff
SELECT "prices".*
FROM "prices"
INNER JOIN
  (SELECT max("prices"."id") AS "id_aggregate",
          min("prices"."published_at") AS "published_at_aggregate",
          "prices"."user_id"
   FROM "prices"
   INNER JOIN
     (SELECT max("prices"."published_at") AS "published_at_aggregate",
             "prices"."user_id"
      FROM "prices"
-      WHERE "published_at" < ?
-        AND "prices"."user_id" = ?
-        AND "prices"."user_id" IS NOT NULL
+      WHERE "prices"."user_id" = ?
+        AND "prices"."user_id" IS NOT NULL
+        AND "published_at" < ?
      GROUP BY "prices"."user_id") AS "price_without_global_scope" ON "price_without_global_scope"."published_at_aggregate" = "prices"."published_at"
   AND "price_without_global_scope"."user_id" = "prices"."user_id"
-   WHERE "published_at" < ?
+   WHERE "prices"."user_id" = ?
+     AND "prices"."user_id" IS NOT NULL
+     AND "published_at" < ?
   GROUP BY "prices"."user_id") AS "price_without_global_scope" ON "price_without_global_scope"."id_aggregate" = "prices"."id"
AND "price_without_global_scope"."published_at_aggregate" = "prices"."published_at"
AND "price_without_global_scope"."user_id" = "prices"."user_id"
WHERE "prices"."user_id" = ?
  AND "prices"."user_id" IS NOT NULL
```

> [!WARNING]
> This does change the `Relation::addConstraints` signature to accept a nullable query parameter. This will have no affect at call sites, but could be considered a BC if others have overridden this method.
> If this is not acceptable then let me know and I can explore an alternate solution.

> [!NOTE]
> While the additional constraints on the middle query might not strictly be necessary (given that the constraints are on the innermost query and we're using an `INNER JOIN`), it does simplify the HasOneThrough relation which needs the intermediate table joined on every subquery.
>
> Without these changes, there would need to be conditional checks to conditionally join based on the query level which could be considered messier.

</details>

Closes #55155

CC: @BertvanHoekelen

Thanks!

### CODE REVIEW

**Comment by BertvanHoekelen** [comment]
Thanks! I just tested your branch on our project and query looks correct and I'm not running into db performance issues.

File: src/Illuminate/Database/Eloquent/Relations/HasOneOrManyThrough.php [hunk 1]
```diff
@@ -97,12 +97,16 @@ public function __construct(Builder $query, Model $farParent, Model $throughPare
...
     public function addConstraints()
     {
+        $query = $this->getRelationQuery();
         $localValue = $this->farParent[$this->localKey];
 
-        $this->performJoin();
+        // Join is performed in HasOneThrough::addOneOfManySubQueryConstraints
+        if (! method_exists($this, 'isOneOfMany') || ! $this->isOneOfMany()) {
+            $this->performJoin($query);
+        }
```
Comment (calebdw) [inline src/Illuminate/Database/Eloquent/Relations/HasOneOrManyThrough.php:106]: This is admittedly not very pretty, but is necessary unless the `Relation::addConstraints` signature is changed to allow passing the query instance in (see Additional Considerations section in PR description).

The root problem is that **all** subqueries need the join applied, but this method is only called for the base query and the innermost subquery.

File: src/Illuminate/Database/Eloquent/Relations/HasOneThrough.php [hunk 2]
```diff
@@ -78,7 +78,11 @@ public function addOneOfManySubQueryConstraints(Builder $query, $column = null,
     {
         $query->addSelect([$this->getQualifiedFirstKeyName()]);
 
-        $this->performJoin($query);
+        // We need to join subqueries that are not the innermost subquery
+        // which is joined in the CanBeOneOfMany::ofMany method.
+        if ($this->getOneOfManySubQuery() !== null) {
+            $this->performJoin($query);
+        }
```
Comment (calebdw) [inline src/Illuminate/Database/Eloquent/Relations/HasOneThrough.php:85]: This is admittedly not very pretty, but is necessary unless the `Relation::addConstraints` signature is changed to allow passing the query instance in (see Additional Considerations section in PR description, and the first commit diff https://github.com/laravel/framework/pull/55168/commits/818ebee35ed2422bddfa80ba7ebc9e6fb716c38a for an example).

The root problem is that **all** subqueries need the join applied, but the innermost query is already being joined in the `CanBeOneOfMany::ofMany` method (the `addConstraints` call).
