### PR TITLE
[5.8] Migration Events

### LINKED ISSUE #854: Fire events on migrations
Can we have events fired in Migrations?

I'm thinking:

- `migrations.before`
- `migrations.after`
- `migrations:refresh.before`
- `migrations:refresh.middle`
- `migrations:refresh.after`

etc.

This would allow for things like clearing of the cache when the migrations are being fired.

A use case i've come across is some of our migrations have data populated for User groups and their roles (using spatie laravel permissions).

When trying to run a `migrate:refresh` it will fail on the `migrate` half of it, because of how the caching is setup by default in spatie laravel permissions.

Even though the data is all deleted, it throws exceptions on create attempts because the cache still exists.

I'd like to be able to catch the "after truncate" bit, and clear the cache so that populate works.

There are also use cases for this in production too, such as sending a notification to a monitoring service whenever a migration has been ran, to help track performance metrics before / after migrations etc.

### PR DESCRIPTION
**Pull request by alexbowers**
This PR adds events to migrations.

Events added:

```
migrations.beforeAll:up
migrations.afterAll:up
migrations.beforeAll:down
migrations.afterAll:down
migrations.before:up
migrations.after:up
migrations.before:down
migrations.after:down
```

The benefit of having these methods is it will allow users to clear cache on migrations, perform maintainence if necessary.

The `before:up`, `before:down`, `after:up` and `after:down` methods all receive the migration that was ran as a parameter, so that you can check which migration you are running to see if you need to perform any specific action.

Fixes https://github.com/laravel/ideas/issues/854

### CODE REVIEW

File: src/Illuminate/Database/MigrationServiceProvider.php [hunk 1]
```diff
@@ -51,7 +51,11 @@ protected function registerMigrator()
         $this->app->singleton('migrator', function ($app) {
             $repository = $app['migration.repository'];
 
-            return new Migrator($repository, $app['db'], $app['files']);
+            $migrator = new Migrator($repository, $app['db'], $app['files']);
+
+            $migrator->setEventDispatcher($app['events']);
```
Comment (sisve) [inline src/Illuminate/Database/MigrationServiceProvider.php]: It seems like you expect setEventDispatcher to be an instance method ...

File: src/Illuminate/Database/Migrations/Migrator.php [hunk 2]
```diff
@@ -591,4 +615,31 @@ protected function note($message)
...
         }
     }
+
+    /**
+     * Set the event dispatcher instance.
+     *
+     * @param  \Illuminate\Contracts\Events\Dispatcher  $dispatcher
+     * @return void
+     */
+    public static function setEventDispatcher(Dispatcher $dispatcher)
```
Comment (sisve) [inline src/Illuminate/Database/Migrations/Migrator.php]: ... but you've declared it as a static function.

Comment (alexbowers) [reply src/Illuminate/Database/Migrations/Migrator.php]: Good spot. My mistake. I'll fix that. Interesting that it raised no issues for me locally. Guess PHP is forgiving.

Comment (alexbowers) [reply src/Illuminate/Database/Migrations/Migrator.php]: Fixed.

File: src/Illuminate/Database/Migrations/Migrator.php [hunk 3]
```diff
@@ -4,13 +4,21 @@
...
 use Illuminate\Database\ConnectionResolverInterface as Resolver;
 
 class Migrator
 {
+    /**
+     * The event dispatcher instance.
+     *
+     * @var \Illuminate\Contracts\Events\Dispatcher
+     */
+    protected static $dispatcher;
```
Comment (driesvints) [inline src/Illuminate/Database/Migrations/Migrator.php]: The static keyword isn't needed here. Also, renaming this to `$events` will make it clearer what it is.
```suggestion
    protected $events;
```

File: src/Illuminate/Database/Migrations/Migrator.php [hunk 4]
```diff
@@ -591,4 +615,33 @@ protected function note($message)
...
+
+        return $this;
+    }
+
+    /**
+     * Fire the given event for the model.
+     *
+     * @param  string  $event
+     * @param  array  $params
+     * @return mixed
```
Comment (driesvints) [inline src/Illuminate/Database/Migrations/Migrator.php]: Make this method void.
```suggestion
     * @return void
```

File: src/Illuminate/Database/Migrations/Migrator.php [hunk 5]
```diff
@@ -591,4 +615,33 @@ protected function note($message)
...
+     */
+    public function fireMigrationEvent($name, $params = [])
+    {
+        if (! isset(static::$dispatcher)) {
+            return true;
+        }
+
+        return static::$dispatcher->dispatch("migrations.{$name}", $params);
+    }
```
Comment (driesvints) [inline src/Illuminate/Database/Migrations/Migrator.php]: Instead of returning something which isn't needed, make this method void and try this:

```php
	    public function fireMigrationEvent($name, $params = [])
	    {
	        if ($this->events) {
	            $this->events->dispatch("migrations.{$name}", $params);
	        }
	    }
```

File: src/Illuminate/Database/Migrations/Migrator.php [hunk 6]
```diff
@@ -591,4 +615,33 @@ protected function note($message)
...
+
+    /**
+     * Set the event dispatcher instance.
+     *
+     * @param  \Illuminate\Contracts\Events\Dispatcher  $dispatcher
+     * @return void
+     */
+    public function setEventDispatcher(Dispatcher $dispatcher)
+    {
+        static::$dispatcher = $dispatcher;
```
Comment (driesvints) [inline src/Illuminate/Database/Migrations/Migrator.php]:
```suggestion
        $this->dispatcher = $dispatcher;
```

File: src/Illuminate/Database/Migrations/Migrator.php [hunk 7]
```diff
@@ -591,4 +615,33 @@ protected function note($message)
...
+
+        return $this;
```
Comment (driesvints) [inline src/Illuminate/Database/Migrations/Migrator.php]: Your method is void but you're returning something here. Remove this return because it's not needed.

File: src/Illuminate/Database/Migrations/Migrator.php [hunk 8]
```diff
@@ -591,4 +615,33 @@ protected function note($message)
...
+    }
```
Comment (driesvints) [inline src/Illuminate/Database/Migrations/Migrator.php]: Instead of using a setter, consider using an extra nullable constructor argument which isn't breaking:

```php
    public function __construct(MigrationRepositoryInterface $repository,
                                Resolver $resolver,
                                Filesystem $files,
                                Dispatcher $events = null)
    {
        $this->files = $files;
        $this->events = $events;
        $this->resolver = $resolver;
        $this->repository = $repository;
    }
```

**Review by driesvints — CHANGES_REQUESTED** [review]
You're on the right track but I believe we can do better. First of all: there's no need for the static keyword anywhere. Check my comments.

I also believe it might be better if we used dedicated classes instead of the string based ones. There's an `Illuminate\Database\Events` where you can add these.

Based on your list above these could be: 

- `UpMigrationsStarted`
- `UpMigrationsEnded`
- `DownMigrationsStarted`
- `DownMigrationsEnded`
- `UpMigrationStarted`
- `UpMigrationEnded`
- `DownMigrationStarted`
- `DownMigrationEnded`

And might I suggest adding:

- `MigrationsStarted`
- `MigrationsEnded`
- `MigrationStarted`
- `MigrationEnded`

Maybe we only need the last four above? Do we really need to know if a migration is a down migration or not?

Nice job so far 👍

File: src/Illuminate/Database/Migrations/Migrator.php (hunk 6 above)
Comment (alexbowers) [reply src/Illuminate/Database/Migrations/Migrator.php]: Should this be completely removed now, since it should be handled by the IoC resolver?

File: src/Illuminate/Database/Migrations/Migrator.php (hunk 8 above)
Comment (alexbowers) [reply src/Illuminate/Database/Migrations/Migrator.php]: Done

File: src/Illuminate/Database/Migrations/Migrator.php (hunk 7 above)
Comment (alexbowers) [reply src/Illuminate/Database/Migrations/Migrator.php]: Done

File: src/Illuminate/Database/Migrations/Migrator.php (hunk 6 above)
Comment (alexbowers) [reply src/Illuminate/Database/Migrations/Migrator.php]: Done

File: src/Illuminate/Database/Migrations/Migrator.php (hunk 5 above)
Comment (alexbowers) [reply src/Illuminate/Database/Migrations/Migrator.php]: Done

File: src/Illuminate/Database/Migrations/Migrator.php (hunk 4 above)
Comment (alexbowers) [reply src/Illuminate/Database/Migrations/Migrator.php]: Done

File: src/Illuminate/Database/Migrations/Migrator.php (hunk 3 above)
Comment (alexbowers) [reply src/Illuminate/Database/Migrations/Migrator.php]: Done

**Comment by alexbowers** [comment]
@driesvints I have made those changes. Couple of things to note.

For the events, in the old system there was wildcard support, which is why I have put a Contract in there, since that allows the same thing:

```php
Events::listen(\Illuminate\Contracts\Database\MigrationEvent::class, ...);
```

I have also changed how data is passed around, the events now instead store the migration and the direction, instead of it being a separate parameter.

File: src/Illuminate/Database/Events/MigrationEvent.php [hunk 9]
```diff
@@ -0,0 +1,36 @@
...
+     * 
+     * @var string
+     */
+    public $direction;
+
+    /**
+     * Create a new event instance.
+     *
+     * @param  \Illuminate\Database\Migrations\Migration  $migration
+     * @param string $direction
```
Comment (driesvints) [inline src/Illuminate/Database/Events/MigrationEvent.php]:
```suggestion
     * @param  string  $direction
```

File: src/Illuminate/Database/Migrations/Migrator.php [hunk 10]
```diff
@@ -591,4 +617,17 @@ protected function note($message)
             $this->output->writeln($message);
         }
     }
+
+    /**
+     * Fire the given event for the migration.
+     *
+     * @param  object $event
```
Comment (driesvints) [inline src/Illuminate/Database/Migrations/Migrator.php]: You can type-hint this and in the method signature that it conforms to your contract.

File: src/Illuminate/Database/Migrations/Migrator.php [hunk 11]
```diff
@@ -259,6 +279,8 @@ protected function rollbackMigrations(array $migrations, $paths, array $options)
             );
         }
 
+        $this->fireMigrationEvent('afterAll:down');
```
Comment (driesvints) [inline src/Illuminate/Database/Migrations/Migrator.php]: Think you forgot this one?

File: src/Illuminate/Database/Migrations/Migrator.php [hunk 12]
```diff
@@ -239,6 +257,8 @@ protected function rollbackMigrations(array $migrations, $paths, array $options)
 
         $this->requireFiles($files = $this->getMigrationFiles($paths));
 
+        $this->fireMigrationEvent('beforeAll:down');
```
Comment (driesvints) [inline src/Illuminate/Database/Migrations/Migrator.php]: Think you forgot this one?

**Review by driesvints — CHANGES_REQUESTED** [review]
Nice job man. Just a few small things and the StyleCI failures.

File: src/Illuminate/Database/Migrations/Migrator.php (hunk 10 above)
Comment (alexbowers) [reply src/Illuminate/Database/Migrations/Migrator.php]: Heh. i even did the contract partially so that I could use it here. Guess I forgot.

File: src/Illuminate/Database/Migrations/Migrator.php (hunk 11 above)
Comment (alexbowers) [reply src/Illuminate/Database/Migrations/Migrator.php]: Damnit. Its on my imac at home, so i'll be able to fix it this evening.

File: src/Illuminate/Database/Migrations/Migrator.php (hunk 12 above)
Comment (alexbowers) [reply src/Illuminate/Database/Migrations/Migrator.php]: Damnit. Its on my imac at home, so i'll be able to fix it this evening.

File: src/Illuminate/Contracts/Database/MigrationEvent.php [hunk 13]
```diff
@@ -0,0 +1,8 @@
+<?php
+
+namespace Illuminate\Contracts\Database;
```
Comment (driesvints) [inline src/Illuminate/Contracts/Database/MigrationEvent.php]: Put this under the `Illuminate\Contracts\Database\Events` namespace. Also move the file to the correct directory.

File: src/Illuminate/Database/Migrations/Migrator.php [hunk 14]
```diff
@@ -63,11 +75,13 @@ class Migrator
...
     public function __construct(MigrationRepositoryInterface $repository,
                                 Resolver $resolver,
-                                Filesystem $files)
+                                Filesystem $files,
+                                Dispatcher $dispatcher = null)
     {
         $this->files = $files;
         $this->resolver = $resolver;
         $this->repository = $repository;
+        $this->events = $dispatcher;
```
Comment (driesvints) [inline src/Illuminate/Database/Migrations/Migrator.php]: We like to arrange the dependencies based on length so please move this right above the repository.

```php

	        $this->files = $files;
	        $this->resolver = $resolver;
	        $this->events = $dispatcher;
	        $this->repository = $repository;
```

**Review by driesvints — CHANGES_REQUESTED** [review]
A few more things. Also: this PR could also use some tests.

File: src/Illuminate/Database/Migrations/Migrator.php (hunk 14 above)
Comment (deleugpn) [reply src/Illuminate/Database/Migrations/Migrator.php]: While at it, maybe make it 

```
	        $this->files = $files;
	        $this->resolver = $resolver;
	        $this->repository = $repository;
	        $this->dispatcher = $dispatcher;
```

Comment (driesvints) [reply src/Illuminate/Database/Migrations/Migrator.php]: No we specifically chose the phrasing "events" because it's the most used in the framework. Other usages should be renamed imo.

**Comment by deleugpn** [comment]
I would like this as well. I have some migrations that change information inside the database and I wanted to write tests to make sure the migration was doing the expected process, I ended up doing this: 


```
    private function afterMigration(string $migrationName, callable $callback)
    {
        DB::listen(function (QueryExecuted $query) use ($migrationName, $callback) {
            if (isset($query->bindings[0]) && $query->bindings[0] === $migrationName) {
                $callback();
            }
        });
    }


    private function migrate(): void
    {
        $this->afterMigration('2018_11_14_154917_some_migration', function () {
            // Add some seed data at this point before changing the database format
        });

        Artisan::call('migrate');
    }

```

File: src/Illuminate/Database/Migrations/Migrator.php (hunk 14 above)
Comment (deleugpn) [reply src/Illuminate/Database/Migrations/Migrator.php]: As someone that type-hints A LOT the `Illuminate\Contracts\Bus\Dispatcher`, it sounds really weird to have a `$event->dispatch()` instead of $dispatcher->dispatch($event)`, but what do I know?

Comment (alexbowers) [reply src/Illuminate/Database/Migrations/Migrator.php]: > We like to arrange the dependencies based on length so please move this right above the repository.
> 
> ```
> 
> 	        $this->files = $files;
> 	        $this->resolver = $resolver;
> 	        $this->events = $dispatcher;
> 	        $this->repository = $repository;
> ```

Do you mean only for the assignment in the body, not the actual dependencies in the params?

The latter would be breaking.

Comment (alexbowers) [reply src/Illuminate/Database/Migrations/Migrator.php]: If its based on length, shouldn't it also be above `resolver`?

Comment (driesvints) [reply src/Illuminate/Database/Migrations/Migrator.php]: Yeah you're right.

File: src/Illuminate/Contracts/Database/MigrationEvent.php (hunk 13 above)
Comment (alexbowers) [reply src/Illuminate/Contracts/Database/MigrationEvent.php]: Done

File: src/Illuminate/Database/Migrations/Migrator.php (hunk 14 above)
Comment (alexbowers) [reply src/Illuminate/Database/Migrations/Migrator.php]: Done

**Comment by alexbowers** [comment]
@driesvints I have done the above, but I was having some trouble with the tests. Not sure why, but Event:assertDispatched was not working for me.

Any advice? As it stands, it basically is fine if it has assertions.

Not ideal, but it does test it.

File: tests/Integration/Database/MigrateWithRealpathTest.php [hunk 15]
```diff
@@ -3,6 +3,12 @@
 namespace Illuminate\Tests\Integration\Database;
 
 use Illuminate\Support\Facades\Schema;
+use Illuminate\Support\Facades\Event;
+use Illuminate\Database\Events\MigrationStarted;
+use Illuminate\Database\Events\MigrationsStarted;
+use Illuminate\Database\Events\MigrationsEnded;
+use Illuminate\Database\Events\MigrationEnded;
+use Illuminate\Database\Migrations\Migrator;
```
Comment (driesvints) [inline tests/Integration/Database/MigrateWithRealpathTest.php]: Please arrange these imports based on length.

File: src/Illuminate/Database/Migrations/Migrator.php (hunk 10 above)
Comment (driesvints) [reply src/Illuminate/Database/Migrations/Migrator.php]: You still need to do this.

**Review by driesvints — CHANGES_REQUESTED** [review]
> Any advice? As it stands, it basically is fine if it has assertions.

Current assertions are fine 👍 

I see you've added a merge commit. Can you try to purge this commit and use rebase instead? Because this adds unnecessary extra commits to the PR.

File: src/Illuminate/Database/Migrations/Migrator.php [hunk 16]
```diff
@@ -4,13 +4,25 @@
...
 use Illuminate\Support\Str;
+use Illuminate\Events\Dispatcher;
 use Illuminate\Support\Collection;
 use Illuminate\Console\OutputStyle;
 use Illuminate\Filesystem\Filesystem;
 use Illuminate\Database\ConnectionResolverInterface as Resolver;
+use Illuminate\Database\Events\MigrationsStarted;
+use Illuminate\Database\Events\MigrationsEnded;
+use Illuminate\Database\Events\MigrationStarted;
+use Illuminate\Database\Events\MigrationEnded;
```
Comment (driesvints) [inline src/Illuminate/Database/Migrations/Migrator.php]: Arrange these by length (see StyleCI).

**Review by driesvints — CHANGES_REQUESTED** [review]

**Comment by alexbowers** [comment]
@driesvints I can try to collapse the commits down. Do you want me to just squash them all?

File: tests/Integration/Database/MigrateWithRealpathTest.php (hunk 15 above)
Comment (alexbowers) [reply tests/Integration/Database/MigrateWithRealpathTest.php]: Done

File: src/Illuminate/Database/Migrations/Migrator.php (hunk 16 above)
Comment (alexbowers) [reply src/Illuminate/Database/Migrations/Migrator.php]: Done

**Comment by alexbowers** [comment]
@driesvints I haven't been able to get the merge commit fixed. Any chance when this is merged it just gets squashed instead? Or can you help me with fixing the merge commit? Either or is fine by me :D

File: src/Illuminate/Database/Migrations/Migrator.php [hunk 17]
```diff
@@ -4,13 +4,25 @@
 
 use Illuminate\Support\Arr;
 use Illuminate\Support\Str;
+use Illuminate\Events\Dispatcher;
```
Comment (X-Coder264) [inline src/Illuminate/Database/Migrations/Migrator.php]: This import should be from the `Contracts` namespace as you put it in the docblock.

Comment (alexbowers) [reply src/Illuminate/Database/Migrations/Migrator.php]: Good point. Changed.

File: src/Illuminate/Database/Migrations/Migrator.php [hunk 18]
```diff
@@ -59,13 +71,16 @@ class Migrator
      * @param  \Illuminate\Database\Migrations\MigrationRepositoryInterface  $repository
      * @param  \Illuminate\Database\ConnectionResolverInterface  $resolver
      * @param  \Illuminate\Filesystem\Filesystem  $files
+     * @param \Illuminate\Contracts\Events\Dispatcher $dispatcher
```
Comment (driesvints) [inline src/Illuminate/Database/Migrations/Migrator.php]:
```suggestion
     * @param  \Illuminate\Contracts\Events\Dispatcher  $dispatcher
```

**Review by driesvints — CHANGES_REQUESTED** [review]
Almost there.

**Comment by driesvints** [comment]
@alexbowers squashing can't be done anymore because you're used merged commits. If you want to fix this you'll need to start a new branch from 5.8 and cherry pick your commits on top. You've used multiple merge commits atm.

**Comment by alexbowers** [comment]
Ok i'll figure it out this evening. Might have to be a new PR or a force push or something.

**Comment by driesvints** [comment]
@alexbowers should be able to do it with a force push. Don't need to open up a new pr. Don't forget to backup your branch first to prevent losing stuff.

**Comment by alexbowers** [comment]
Ok @driesvints I think thats worked.

**Review by driesvints — APPROVED** [review]
Nice job 👍

**Comment by alexbowers** [comment]
Any more changes, or are you good with this?

**Comment by driesvints** [comment]
@alexbowers see the approval above :)

**Comment by driesvints** [comment]
You could perhaps squash your commits.

**Comment by alexbowers** [comment]
Ah missed that. It should be able to be squashed by the merger, since if I was to squash now that'd be another force push. I'd rather avoid that just incase I bin it :D

File: src/Illuminate/Contracts/Database/Events/Migration.php [hunk 19]
```diff
@@ -0,0 +1,8 @@
+<?php
+
+namespace Illuminate\Contracts\Database\Events;
+
+interface Migration
```
Comment (driesvints) [inline src/Illuminate/Contracts/Database/Events/Migration.php]: This should be called `MigrationEvent` btw since it's not a migration but an event.

**Review by driesvints — CHANGES_REQUESTED** [review]

**Comment by devcircus** [comment]
Just a thought, but in Illuminate/Auth/Events the namespace delineates the classes within as events. The classes themselves are "Login",  "Logout". etc. So Illuminate/Contracts/Database/Events/Migration makes sense in that context.

**Review by driesvints — APPROVED** [review]

**Comment by driesvints** [comment]
@devcircus right. Let's just leave it at this.

**Comment by ttomdewit** [comment]
Thanks for everyone's hard work this past week, hopefully it'll be considered and merged. :+1:

**Comment by jasonmccreary** [comment]
Were these added to the docs anywhere? Glad to do it. Just didn't want to duplicate work.

**Comment by driesvints** [comment]
@jasonmccreary I don't think they were.

**Comment by wouter2203** [comment]
Was it intended that no events will be executed if there are no migrations available? (See: https://github.com/laravel/framework/blob/5.8/src/Illuminate/Database/Migrations/Migrator.php#L141)

A use case for where it would be useful to always send the events:

We have our own migrator which will run a migration multiply times with different variables given to the migration. We run this migrator on the `MigrationsEnded` event. When we have no default migrations but only custom migrations the event is never executed. Therefor our custom migrations are never ran.

**Comment by ttomdewit** [comment]
@wouter2203 Personally I’ve never thought about that particular requirement.

**Comment by wouter2203** [comment]
We were just calling another command after `php artisan migrate` that would run our own migrations. Then we read somewhere (laravel-news I think) that migration events were available, so we deleted that command and used the events. Only to notice that our custom migrations were not always running..

Would be cool if we get some extra events, something in the lines of `Starting`, `Running`, `Finished`. Where `Running` would just never be fired when no migrations are available.

**Comment by driesvints** [comment]
@wouter2203 you're always free to send in a follow-up pr. Make sure to thoroughly describe your use-case.

**Comment by ArlonAntonius** [comment]
I don't know @wouter2203's exact use case, but I actually need something among the same lines and was wondering if you guys would be open to the following:
- Fire a Starting event before the requiring of pending migrations (https://github.com/laravel/framework/blob/5.8/src/Illuminate/Database/Migrations/Migrator.php#L97) which gives at least the paths and options variable as references so we're able to change those.
- Fire an Ended event containing the migrations that ran

Would love to hear your feedback on this as well @wouter2203 would it help with your use case or would you also need the Running Event?

**Comment by driesvints** [comment]
@ArlonAntonius that sounds reasonable. Let's wait to see what @wouter2203 thinks.

**Comment by wouter2203** [comment]
@ArlonAntonius If the Ended event is also fired when no migrations are ran it'll work for my use case. The normal migrations should run before the custom migrations, so we need to listen for Ended. And in that case the Ended migration would just contain an empty array.

To elaborate on (one of) my use case(s):

Let's say we have a multilingual cms system where users can manage the mailings that are send by that system. When a new mailing is added we'll make a custom migration that'll run the following:

```php
    public function up($locale)
    {
        Mailing::create([
            'locale' => $locale,
            'template' => 'A new mailing',
        ]);
    }
```

To have the above work we need the normal migrations to be ran first, otherwise the `mailings` table would not exist.

Now if we have configured `['en', 'nl', 'de']` as locales for that cms the above is executed 3 times, each time with a different `$locale`.

Ofcourse the mailing would be added with an English template for all 3 locales, but now the user can edit the template for nl and de in the cms.

I can create a pull request in which the `Starting` and `Ended` events are implemented, If you agree with both the `Starting` and `Ended` events always firing.

**Comment by ArlonAntonius** [comment]
@wouter2203 Sounds good to me should be enough to fix my actual use case, please mention me @ the PR so I can double-check.

**Comment by ttomdewit** [comment]
Thanks for taking this to the next level.

**Comment by M45678** [comment]
Laravel Migration event listeners don't work in my case.
`
use App\Listeners\DeleteUnitsAwsImages;
use Illuminate\Database\Events\MigrationsStarted;
class EventServiceProvider extends ServiceProvider
{
    /**
     * The event listener mappings for the application.
     *
     * @var array
     */
    protected $listen = [
        MigrationsStarted::class => [
            DeleteUnitsAwsImages::class,
        ]
    ];
....
`

**Comment by alexbowers** [comment]
Please can you open an issue if you think this is a bug

**Comment by M45678** [comment]
> Please can you open an issue if you think this is a bug
I opened the discussion, as I need something like support or additional info related to doc 
Please see here https://github.com/laravel/framework/discussions/32778#event-1300
