### PR TITLE
[6.x] Fixed Schedule runInBackground not fired on Windows

### LINKED ISSUE #27541: Schedule runInBackground not fired
- Laravel Version: 5.7.26
- PHP Version: 7.3.2
- Database Driver & Version:

### Description:
I`m on Windows 10 x64 System and trying to run a schedule, from cli, to run in background.
Running scheduled command is displayed but it does not fired.
If i copying it and running manualy it work like it should.
Any ideea what could be?!

### Steps To Reproduce:
```$schedule->command('my-command')->everyMinute()->runInBackground();```

```Running scheduled command: ("C:\php-7\php.exe" "artisan" my-command > "NUL" 2>&1 & "C:\php-7\php.exe" "artisan" schedule:finish "framework\schedule-47987621c9ff2fa8a91fa554f7471894a3325831") > "NUL" 2>&1 &```

### PR DESCRIPTION
**Pull request by WorldSeso7**
Closes #27541. (thanks for the solution to @islandblaze)

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Please remove the changelog entry. We'll add that ourselves and determine which release it goes into. :)

File: src/Illuminate/Console/Scheduling/CommandBuilder.php [hunk 1]
```diff
@@ -51,6 +51,10 @@ protected function buildBackgroundCommand(Event $event)
 
         $finished = Application::formatCommandString('schedule:finish').' "'.$event->mutexName().'"';
 
+        if (windows_os()) {
+            return 'start /b cmd /c "('.$event->command.' & '.$finished.')'.$redirect.$output.' 2>&1"';
+        }
+
         return $this->ensureCorrectUser($event,
             '('.$event->command.$redirect.$output.' 2>&1 '.(windows_os() ? '&' : ';').' '.$finished.') > '
```
Comment (skyosev) [inline src/Illuminate/Console/Scheduling/CommandBuilder.php]: It seems the windows_os() check is redundant here ?

Comment (WorldSeso7) [reply src/Illuminate/Console/Scheduling/CommandBuilder.php]: Yes! I removed it
