### PR TITLE
[11.x] Fix parsing `PHP_CLI_SERVER_WORKERS` as `string` instead of `int`

### LINKED ISSUE #54723: PHP_CLI_SERVER_WORKERS has no effect even with --no-reload option
### Laravel Version

11.43.2

### PHP Version

8.4.3

### Database Driver & Version

_No response_

### Description

As the title says it seems like `PHP_CLI_SERVER_WORKERS` has no effect even when i start the server with the following command `php artisan serve --no-reload --host=0.0.0.0`

### Steps To Reproduce

1. Set `PHP_CLI_SERVER_WORKERS=5` env var
2. Start the development server with `php artisan serve --no-reload --host=0.0.0.0`
3. For e.g make a call to own internal api like this:

```php
public function index(Request $request){
    $appUrl = env('APP_URL');
    // or with token what ever...
    $con =  Http::withHeaders([
        'Accept' => 'application/json',
        'Referer' => $appUrl,
        'Cookie' => request()->header('Cookie'),
        'X-CSRF-TOKEN' => csrf_token(),
    ])->baseUrl("$appUrl/api");
    $response = $con->get('/users/', []);
 
    // curl hangs with 30 sec timeout, as the api request cannot be processed in parallel

    return view('users.index', ['data'=>$response->object()]);
}
```

Image

### PR DESCRIPTION
**Pull request by crynobone**
fixes #54723

### CODE REVIEW

File: src/Illuminate/Foundation/Console/ServeCommand.php [hunk 1]
```diff
@@ -96,7 +96,7 @@ class ServeCommand extends Command
     #[\Override]
     protected function initialize(InputInterface $input, OutputInterface $output)
     {
-        $this->phpServerWorkers = transform(env('PHP_CLI_SERVER_WORKERS', 1), function ($workers) {
+        $this->phpServerWorkers = transform((int) env('PHP_CLI_SERVER_WORKERS', 1), function (int $workers) {
             if (! is_int($workers) || $workers < 2) {
```
Comment (Jubeki) [inline src/Illuminate/Foundation/Console/ServeCommand.php:100]:
```suggestion
            if ($workers < 2) {
```

You are now requiring that `$workers` is an int, therefor the `is_int` check can be removed.
