### PR TITLE
[10.x] fix handle `shift()` on an empty collection

### LINKED ISSUE #51840: [10.x] collection shift can not handle an empty collection
### Laravel Version

10.48.13

### PHP Version

8.3.8

### Database Driver & Version

_No response_

### Description

A [recent addition](https://github.com/laravel/framework/pull/51686) to `Collection::shift()` causes it to throw an exception when running on a empty collection.

Will provide a PR to fix this issue.

### Steps To Reproduce

1. create a collection with two objects
2. call `shift()` three times on it and assign it to variables
3. dump a property of the object for every variable
4. it will throw an exception saying it can not call the property on a collection

### PR DESCRIPTION
**Pull request by Treggats**
fixes #51840

This PR fixes how the `Collection::shift()` method handles an empty collection.
Currently it will return the collection when trying to call `shift()` on an empty collection. Before it would return null.

## steps to reproduce

This is also covered in the added test.

1. create a collection with two objects
2. call shift() three times on it and assign it to variables
3. dump a property of the object for every variable
4. it will throw an exception saying it can not call the property on a collection

### CODE REVIEW

File: src/Illuminate/Collections/Collection.php [hunk 1]
```diff
@@ -1134,7 +1134,11 @@ public function shift($count = 1)
             throw new InvalidArgumentException('Number of shifted items may not be less than zero.');
         }
 
-        if ($count === 0 || $this->isEmpty()) {
+        if ($this->isEmpty()) {
```
Comment (Treggats) [inline src/Illuminate/Collections/Collection.php:1137]: I think this is the correct placement for the `isEmpty()` check. We want to make sure that there are items to use before we continue to handle the rest.

Also this maintains the behaviour as it was prior to the mentioned PR.

File: tests/Support/SupportCollectionTest.php [hunk 2]
```diff
@@ -404,6 +404,24 @@ public function testShiftReturnsAndRemovesFirstXItemsInCollection()
...
+
+        $translations = collect([$english, $dutch]);
+
+        $englishTranslation = $translations->shift();
+        $dutchTranslation = $translations->shift();
+        $danish = $translations->shift();
+
+        $englishTranslation?->text;
+        $dutchTranslation?->text;
+        $this->assertNull($danish);
```
Comment (tanerkay) [inline tests/Support/SupportCollectionTest.php:422]: could this be simplified to:?
```suggestion
        $this->assertNull((new Collection())->shift());
```

Comment (Treggats) [reply tests/Support/SupportCollectionTest.php:422]: While it could, I feel that the current test is more expressive. As in, it conveys more what it actually tests.
I could reduce the collection to one item, but I feel that's a bit nitpicky

**Comment by nvahalik** [comment]
Yikes. This has broken at least one 3rd party package that depending on `shift()` returning `null` rather than an empty collection! https://github.com/laravel-json-api/laravel/issues/287

**Comment by Treggats** [comment]
> Yikes. This has broken at least one 3rd party package that depending on `shift()` returning `null` rather than an empty collection! [laravel-json-api/laravel#287](https://github.com/laravel-json-api/laravel/issues/287)

Same, our tests started failing. So hence this PR. Just waiting on the release. In the mean time we updated our codebase to use the native `array_shift(..)`

**Comment by driesvints** [comment]
I just cut a new release that includes this one.
