### PR TITLE
[12.x] Resolve infinite loop when using deferred queue

### LINKED ISSUE #58351: Specifying connection `deferred` on a Job causes an infinite loop starting from v12.45.0 and till current
### Laravel Version

12.46.0

### PHP Version

8.4

### Database Driver & Version

_No response_

### Description

PR #58228 introduced `JobAttempted` for sync jobs. However, yesterday we updated the composer from v12.44.0 to v12.46.0 and noticed an infinite loop in one of the commands.
I downgraded and confirmed that the issue was happening only on upgrade. I tried v12.45.0 and the same issues was replicated.
Below a trace from v12.44.0
```
#0 ███████/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\███████\\Jobs\\███████Job->handle()
#1 ███████/laravel/vendor/laravel/framework/src/Illuminate/Container/Util.php(43): Illuminate\\Container\\BoundMethod::{closure:Illuminate\\Container\\BoundMethod::call():35}()
#2 ███████/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(96): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#3 ███████/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#4 ███████/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(799): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#5 ███████/laravel/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(129): Illuminate\\Container\\Container->call(Array)
#6 ███████/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Bus\\Dispatcher->{closure:Illuminate\\Bus\\Dispatcher::dispatchNow():126}(Object(App\\███████\\Jobs\\███████Job))
#7 ███████/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\\Pipeline\\Pipeline->{closure:Illuminate\\Pipeline\\Pipeline::prepareDestination():178}(Object(App\\███████\\Jobs\\███████Job))
#8 ███████/laravel/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(133): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#9 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(134): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(App\\███████\\Jobs\\███████Job), false)
#10 ███████/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Queue\\CallQueuedHandler->{closure:Illuminate\\Queue\\CallQueuedHandler::dispatchThroughMiddleware():127}(Object(App\\███████\\Jobs\\███████Job))
#11 ███████/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\\Pipeline\\Pipeline->{closure:Illuminate\\Pipeline\\Pipeline::prepareDestination():178}(Object(App\\███████\\Jobs\\███████Job))
#12 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(127): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#13 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(68): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\\Queue\\Jobs\\SyncJob), Object(App\\███████\\Jobs\\███████Job))
#14 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(102): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\SyncJob), Array)
#15 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(130): Illuminate\\Queue\\Jobs\\Job->fire()
#16 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(106): Illuminate\\Queue\\SyncQueue->executeJob(Object(App\\███████\\Jobs\\███████Job), '', NULL)
#17 ███████/laravel/vendor/laravel/framework/src/Illuminate/Database/DatabaseTransactionsManager.php(211): Illuminate\\Queue\\SyncQueue->{closure:Illuminate\\Queue\\SyncQueue::push():106}()
#18 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(105): Illuminate\\Database\\DatabaseTransactionsManager->addCallback(Object(Closure))
#19 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/DeferredQueue.php(19): Illuminate\\Queue\\SyncQueue->push(Object(App\\███████\\Jobs\\███████Job), '', NULL)
#20 [internal function]: Illuminate\\Queue\\DeferredQueue->{closure:Illuminate\\Queue\\DeferredQueue::push():19}()
#21 ███████/laravel/vendor/laravel/framework/src/Illuminate/Support/Defer/DeferredCallback.php(52): call_user_func(Object(Closure))
#22 ███████/laravel/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(803): Illuminate\\Support\\Defer\\DeferredCallback->__invoke()
#23 ███████/laravel/vendor/laravel/framework/src/Illuminate/Support/Defer/DeferredCallbackCollection.php(53): rescue(Object(Illuminate\\Support\\Defer\\DeferredCallback))
#24 ███████/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Providers/FoundationServiceProvider.php(214): Illuminate\\Support\\Defer\\DeferredCallbackCollection->invokeWhen(Object(Closure))
#25 ███████/laravel/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(488): Illuminate\\Foundation\\Providers\\FoundationServiceProvider->{closure:Illuminate\\Foundation\\Providers\\FoundationServiceProvider::registerDeferHandler():213}(Object(Illuminate\\Console\\Events\\CommandFinished))
#26 ███████/laravel/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(315): Illuminate\\Events\\Dispatcher->{closure:Illuminate\\Events\\Dispatcher::makeListener():483}('Illuminate\\\\Cons...', Array)
#27 ███████/laravel/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(295): Illuminate\\Events\\Dispatcher->invokeListeners('Illuminate\\\\Cons...', Array, false)
#28 ███████/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(171): Illuminate\\Events\\Dispatcher->dispatch(Object(Illuminate\\Console\\Events\\CommandFinished))
#29 ███████/laravel/vendor/symfony/event-dispatcher/EventDispatcher.php(206): Illuminate\\Foundation\\Console\\Kernel->{closure:Illuminate\\Foundation\\Console\\Kernel::rerouteSymfonyCommandEvents():170}(Object(Symfony\\Component\\Console\\Event\\ConsoleTerminateEvent), 'console.termina...', Object(Symfony\\Component\\EventDispatcher\\EventDispatcher))
#30 ███████/laravel/vendor/symfony/event-dispatcher/EventDispatcher.php(56): Symfony\\Component\\EventDispatcher\\EventDispatcher->callListeners(Array, 'console.termina...', Object(Symfony\\Component\\Console\\Event\\ConsoleTerminateEvent))
#31 ███████/laravel/vendor/symfony/console/Application.php(1121): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch(Object(Symfony\\Component\\Console\\Event\\ConsoleTerminateEvent), 'console.termina...')
#32 ███████/laravel/vendor/symfony/console/Application.php(356): Symfony\\Component\\Console\\Application->doRunCommand(Object(App\\███████\\Console\\Commands\\███████), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#33 ███████/laravel/vendor/symfony/console/Application.php(195): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#34 ███████/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(198): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#35 ███████/laravel/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#36 {main}
```
Below a trace from v12.45.0 showing the problem, had to throw and exit after 10 attempts to show the issue
```
[stacktrace]
#0 ███████/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\███████\\Jobs\\███████Job->handle()
#1 ███████/laravel/vendor/laravel/framework/src/Illuminate/Container/Util.php(43): Illuminate\\Container\\BoundMethod::{closure:Illuminate\\Container\\BoundMethod::call():35}()
#2 ███████/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(96): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#3 ███████/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#4 ███████/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(799): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#5 ███████/laravel/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(129): Illuminate\\Container\\Container->call(Array)
#6 ███████/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Bus\\Dispatcher->{closure:Illuminate\\Bus\\Dispatcher::dispatchNow():126}(Object(App\\███████\\Jobs\\███████Job))
#7 ███████/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\\Pipeline\\Pipeline->{closure:Illuminate\\Pipeline\\Pipeline::prepareDestination():178}(Object(App\\███████\\Jobs\\███████Job))
#8 ███████/laravel/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(133): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#9 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(134): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(App\\███████\\Jobs\\███████Job), false)
#10 ███████/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Queue\\CallQueuedHandler->{closure:Illuminate\\Queue\\CallQueuedHandler::dispatchThroughMiddleware():127}(Object(App\\███████\\Jobs\\███████Job))
#11 ███████/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\\Pipeline\\Pipeline->{closure:Illuminate\\Pipeline\\Pipeline::prepareDestination():178}(Object(App\\███████\\Jobs\\███████Job))
#12 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(127): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#13 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(68): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\\Queue\\Jobs\\SyncJob), Object(App\\███████\\Jobs\\███████Job))
#14 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(102): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\SyncJob), Array)
#15 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(131): Illuminate\\Queue\\Jobs\\Job->fire()
#16 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(107): Illuminate\\Queue\\SyncQueue->executeJob(Object(App\\███████\\Jobs\\███████Job), '', NULL)
#17 ███████/laravel/vendor/laravel/framework/src/Illuminate/Database/DatabaseTransactionsManager.php(211): Illuminate\\Queue\\SyncQueue->{closure:Illuminate\\Queue\\SyncQueue::push():107}()
#18 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(106): Illuminate\\Database\\DatabaseTransactionsManager->addCallback(Object(Closure))
#19 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/DeferredQueue.php(19): Illuminate\\Queue\\SyncQueue->push(Object(App\\███████\\Jobs\\███████Job), '', NULL)
#20 [internal function]: Illuminate\\Queue\\DeferredQueue->{closure:Illuminate\\Queue\\DeferredQueue::push():19}()
#21 ███████/laravel/vendor/laravel/framework/src/Illuminate/Support/Defer/DeferredCallback.php(52): call_user_func(Object(Closure))
#22 ███████/laravel/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(803): Illuminate\\Support\\Defer\\DeferredCallback->__invoke()
#23 ███████/laravel/vendor/laravel/framework/src/Illuminate/Support/Defer/DeferredCallbackCollection.php(53): rescue(Object(Illuminate\\Support\\Defer\\DeferredCallback))
#24 ███████/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Providers/FoundationServiceProvider.php(218): Illuminate\\Support\\Defer\\DeferredCallbackCollection->invokeWhen(Object(Closure))
#25 ███████/laravel/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(488): Illuminate\\Foundation\\Providers\\FoundationServiceProvider->{closure:Illuminate\\Foundation\\Providers\\FoundationServiceProvider::registerDeferHandler():217}(Object(Illuminate\\Queue\\Events\\JobAttempted))
#26 ███████/laravel/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(315): Illuminate\\Events\\Dispatcher->{closure:Illuminate\\Events\\Dispatcher::makeListener():483}('Illuminate\\\\Queu...', Array)
#27 ███████/laravel/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(295): Illuminate\\Events\\Dispatcher->invokeListeners('Illuminate\\\\Queu...', Array, false)
#28 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(193): Illuminate\\Events\\Dispatcher->dispatch(Object(Illuminate\\Queue\\Events\\JobAttempted))
#29 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(139): Illuminate\\Queue\\SyncQueue->raiseJobAttemptedEvent(Object(Illuminate\\Queue\\Jobs\\SyncJob), false)
#30 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(107): Illuminate\\Queue\\SyncQueue->executeJob(Object(App\\███████\\Jobs\\███████Job), '', NULL)
#31 ███████/laravel/vendor/laravel/framework/src/Illuminate/Database/DatabaseTransactionsManager.php(211): Illuminate\\Queue\\SyncQueue->{closure:Illuminate\\Queue\\SyncQueue::push():107}()
#32 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(106): Illuminate\\Database\\DatabaseTransactionsManager->addCallback(Object(Closure))
#33 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/DeferredQueue.php(19): Illuminate\\Queue\\SyncQueue->push(Object(App\\███████\\Jobs\\███████Job), '', NULL)
#34 [internal function]: Illuminate\\Queue\\DeferredQueue->{closure:Illuminate\\Queue\\DeferredQueue::push():19}()
#35 ███████/laravel/vendor/laravel/framework/src/Illuminate/Support/Defer/DeferredCallback.php(52): call_user_func(Object(Closure))
#36 ███████/laravel/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(803): Illuminate\\Support\\Defer\\DeferredCallback->__invoke()
#37 ███████/laravel/vendor/laravel/framework/src/Illuminate/Support/Defer/DeferredCallbackCollection.php(53): rescue(Object(Illuminate\\Support\\Defer\\DeferredCallback))
#38 ███████/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Providers/FoundationServiceProvider.php(218): Illuminate\\Support\\Defer\\DeferredCallbackCollection->invokeWhen(Object(Closure))
#39 ███████/laravel/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(488): Illuminate\\Foundation\\Providers\\FoundationServiceProvider->{closure:Illuminate\\Foundation\\Providers\\FoundationServiceProvider::registerDeferHandler():217}(Object(Illuminate\\Queue\\Events\\JobAttempted))
#40 ███████/laravel/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(315): Illuminate\\Events\\Dispatcher->{closure:Illuminate\\Events\\Dispatcher::makeListener():483}('Illuminate\\\\Queu...', Array)
#41 ███████/laravel/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(295): Illuminate\\Events\\Dispatcher->invokeListeners('Illuminate\\\\Queu...', Array, false)
#42 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(193): Illuminate\\Events\\Dispatcher->dispatch(Object(Illuminate\\Queue\\Events\\JobAttempted))
#43 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(139): Illuminate\\Queue\\SyncQueue->raiseJobAttemptedEvent(Object(Illuminate\\Queue\\Jobs\\SyncJob), false)
#44 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(107): Illuminate\\Queue\\SyncQueue->executeJob(Object(App\\███████\\Jobs\\███████Job), '', NULL)
#45 ███████/laravel/vendor/laravel/framework/src/Illuminate/Database/DatabaseTransactionsManager.php(211): Illuminate\\Queue\\SyncQueue->{closure:Illuminate\\Queue\\SyncQueue::push():107}()
#46 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(106): Illuminate\\Database\\DatabaseTransactionsManager->addCallback(Object(Closure))
#47 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/DeferredQueue.php(19): Illuminate\\Queue\\SyncQueue->push(Object(App\\███████\\Jobs\\███████Job), '', NULL)
#48 [internal function]: Illuminate\\Queue\\DeferredQueue->{closure:Illuminate\\Queue\\DeferredQueue::push():19}()
#49 ███████/laravel/vendor/laravel/framework/src/Illuminate/Support/Defer/DeferredCallback.php(52): call_user_func(Object(Closure))
#50 ███████/laravel/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(803): Illuminate\\Support\\Defer\\DeferredCallback->__invoke()
#51 ███████/laravel/vendor/laravel/framework/src/Illuminate/Support/Defer/DeferredCallbackCollection.php(53): rescue(Object(Illuminate\\Support\\Defer\\DeferredCallback))
#52 ███████/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Providers/FoundationServiceProvider.php(218): Illuminate\\Support\\Defer\\DeferredCallbackCollection->invokeWhen(Object(Closure))
#53 ███████/laravel/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(488): Illuminate\\Foundation\\Providers\\FoundationServiceProvider->{closure:Illuminate\\Foundation\\Providers\\FoundationServiceProvider::registerDeferHandler():217}(Object(Illuminate\\Queue\\Events\\JobAttempted))
#54 ███████/laravel/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(315): Illuminate\\Events\\Dispatcher->{closure:Illuminate\\Events\\Dispatcher::makeListener():483}('Illuminate\\\\Queu...', Array)
#55 ███████/laravel/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(295): Illuminate\\Events\\Dispatcher->invokeListeners('Illuminate\\\\Queu...', Array, false)
#56 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(193): Illuminate\\Events\\Dispatcher->dispatch(Object(Illuminate\\Queue\\Events\\JobAttempted))
#57 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(139): Illuminate\\Queue\\SyncQueue->raiseJobAttemptedEvent(Object(Illuminate\\Queue\\Jobs\\SyncJob), false)
#58 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(107): Illuminate\\Queue\\SyncQueue->executeJob(Object(App\\███████\\Jobs\\███████Job), '', NULL)
#59 ███████/laravel/vendor/laravel/framework/src/Illuminate/Database/DatabaseTransactionsManager.php(211): Illuminate\\Queue\\SyncQueue->{closure:Illuminate\\Queue\\SyncQueue::push():107}()
#60 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(106): Illuminate\\Database\\DatabaseTransactionsManager->addCallback(Object(Closure))
#61 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/DeferredQueue.php(19): Illuminate\\Queue\\SyncQueue->push(Object(App\\███████\\Jobs\\███████Job), '', NULL)
#62 [internal function]: Illuminate\\Queue\\DeferredQueue->{closure:Illuminate\\Queue\\DeferredQueue::push():19}()
#63 ███████/laravel/vendor/laravel/framework/src/Illuminate/Support/Defer/DeferredCallback.php(52): call_user_func(Object(Closure))
#64 ███████/laravel/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(803): Illuminate\\Support\\Defer\\DeferredCallback->__invoke()
#65 ███████/laravel/vendor/laravel/framework/src/Illuminate/Support/Defer/DeferredCallbackCollection.php(53): rescue(Object(Illuminate\\Support\\Defer\\DeferredCallback))
#66 ███████/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Providers/FoundationServiceProvider.php(218): Illuminate\\Support\\Defer\\DeferredCallbackCollection->invokeWhen(Object(Closure))
#67 ███████/laravel/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(488): Illuminate\\Foundation\\Providers\\FoundationServiceProvider->{closure:Illuminate\\Foundation\\Providers\\FoundationServiceProvider::registerDeferHandler():217}(Object(Illuminate\\Queue\\Events\\JobAttempted))
#68 ███████/laravel/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(315): Illuminate\\Events\\Dispatcher->{closure:Illuminate\\Events\\Dispatcher::makeListener():483}('Illuminate\\\\Queu...', Array)
#69 ███████/laravel/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(295): Illuminate\\Events\\Dispatcher->invokeListeners('Illuminate\\\\Queu...', Array, false)
#70 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(193): Illuminate\\Events\\Dispatcher->dispatch(Object(Illuminate\\Queue\\Events\\JobAttempted))
#71 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(139): Illuminate\\Queue\\SyncQueue->raiseJobAttemptedEvent(Object(Illuminate\\Queue\\Jobs\\SyncJob), false)
#72 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(107): Illuminate\\Queue\\SyncQueue->executeJob(Object(App\\███████\\Jobs\\███████Job), '', NULL)
#73 ███████/laravel/vendor/laravel/framework/src/Illuminate/Database/DatabaseTransactionsManager.php(211): Illuminate\\Queue\\SyncQueue->{closure:Illuminate\\Queue\\SyncQueue::push():107}()
#74 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(106): Illuminate\\Database\\DatabaseTransactionsManager->addCallback(Object(Closure))
#75 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/DeferredQueue.php(19): Illuminate\\Queue\\SyncQueue->push(Object(App\\███████\\Jobs\\███████Job), '', NULL)
#76 [internal function]: Illuminate\\Queue\\DeferredQueue->{closure:Illuminate\\Queue\\DeferredQueue::push():19}()
#77 ███████/laravel/vendor/laravel/framework/src/Illuminate/Support/Defer/DeferredCallback.php(52): call_user_func(Object(Closure))
#78 ███████/laravel/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(803): Illuminate\\Support\\Defer\\DeferredCallback->__invoke()
#79 ███████/laravel/vendor/laravel/framework/src/Illuminate/Support/Defer/DeferredCallbackCollection.php(53): rescue(Object(Illuminate\\Support\\Defer\\DeferredCallback))
#80 ███████/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Providers/FoundationServiceProvider.php(218): Illuminate\\Support\\Defer\\DeferredCallbackCollection->invokeWhen(Object(Closure))
#81 ███████/laravel/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(488): Illuminate\\Foundation\\Providers\\FoundationServiceProvider->{closure:Illuminate\\Foundation\\Providers\\FoundationServiceProvider::registerDeferHandler():217}(Object(Illuminate\\Queue\\Events\\JobAttempted))
#82 ███████/laravel/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(315): Illuminate\\Events\\Dispatcher->{closure:Illuminate\\Events\\Dispatcher::makeListener():483}('Illuminate\\\\Queu...', Array)
#83 ███████/laravel/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(295): Illuminate\\Events\\Dispatcher->invokeListeners('Illuminate\\\\Queu...', Array, false)
#84 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(193): Illuminate\\Events\\Dispatcher->dispatch(Object(Illuminate\\Queue\\Events\\JobAttempted))
#85 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(139): Illuminate\\Queue\\SyncQueue->raiseJobAttemptedEvent(Object(Illuminate\\Queue\\Jobs\\SyncJob), false)
#86 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(107): Illuminate\\Queue\\SyncQueue->executeJob(Object(App\\███████\\Jobs\\███████Job), '', NULL)
#87 ███████/laravel/vendor/laravel/framework/src/Illuminate/Database/DatabaseTransactionsManager.php(211): Illuminate\\Queue\\SyncQueue->{closure:Illuminate\\Queue\\SyncQueue::push():107}()
#88 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(106): Illuminate\\Database\\DatabaseTransactionsManager->addCallback(Object(Closure))
#89 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/DeferredQueue.php(19): Illuminate\\Queue\\SyncQueue->push(Object(App\\███████\\Jobs\\███████Job), '', NULL)
#90 [internal function]: Illuminate\\Queue\\DeferredQueue->{closure:Illuminate\\Queue\\DeferredQueue::push():19}()
#91 ███████/laravel/vendor/laravel/framework/src/Illuminate/Support/Defer/DeferredCallback.php(52): call_user_func(Object(Closure))
#92 ███████/laravel/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(803): Illuminate\\Support\\Defer\\DeferredCallback->__invoke()
#93 ███████/laravel/vendor/laravel/framework/src/Illuminate/Support/Defer/DeferredCallbackCollection.php(53): rescue(Object(Illuminate\\Support\\Defer\\DeferredCallback))
#94 ███████/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Providers/FoundationServiceProvider.php(218): Illuminate\\Support\\Defer\\DeferredCallbackCollection->invokeWhen(Object(Closure))
#95 ███████/laravel/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(488): Illuminate\\Foundation\\Providers\\FoundationServiceProvider->{closure:Illuminate\\Foundation\\Providers\\FoundationServiceProvider::registerDeferHandler():217}(Object(Illuminate\\Queue\\Events\\JobAttempted))
#96 ███████/laravel/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(315): Illuminate\\Events\\Dispatcher->{closure:Illuminate\\Events\\Dispatcher::makeListener():483}('Illuminate\\\\Queu...', Array)
#97 ███████/laravel/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(295): Illuminate\\Events\\Dispatcher->invokeListeners('Illuminate\\\\Queu...', Array, false)
#98 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(193): Illuminate\\Events\\Dispatcher->dispatch(Object(Illuminate\\Queue\\Events\\JobAttempted))
#99 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(139): Illuminate\\Queue\\SyncQueue->raiseJobAttemptedEvent(Object(Illuminate\\Queue\\Jobs\\SyncJob), false)
#100 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(107): Illuminate\\Queue\\SyncQueue->executeJob(Object(App\\███████\\Jobs\\███████Job), '', NULL)
#101 ███████/laravel/vendor/laravel/framework/src/Illuminate/Database/DatabaseTransactionsManager.php(211): Illuminate\\Queue\\SyncQueue->{closure:Illuminate\\Queue\\SyncQueue::push():107}()
#102 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(106): Illuminate\\Database\\DatabaseTransactionsManager->addCallback(Object(Closure))
#103 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/DeferredQueue.php(19): Illuminate\\Queue\\SyncQueue->push(Object(App\\███████\\Jobs\\███████Job), '', NULL)
#104 [internal function]: Illuminate\\Queue\\DeferredQueue->{closure:Illuminate\\Queue\\DeferredQueue::push():19}()
#105 ███████/laravel/vendor/laravel/framework/src/Illuminate/Support/Defer/DeferredCallback.php(52): call_user_func(Object(Closure))
#106 ███████/laravel/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(803): Illuminate\\Support\\Defer\\DeferredCallback->__invoke()
#107 ███████/laravel/vendor/laravel/framework/src/Illuminate/Support/Defer/DeferredCallbackCollection.php(53): rescue(Object(Illuminate\\Support\\Defer\\DeferredCallback))
#108 ███████/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Providers/FoundationServiceProvider.php(218): Illuminate\\Support\\Defer\\DeferredCallbackCollection->invokeWhen(Object(Closure))
#109 ███████/laravel/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(488): Illuminate\\Foundation\\Providers\\FoundationServiceProvider->{closure:Illuminate\\Foundation\\Providers\\FoundationServiceProvider::registerDeferHandler():217}(Object(Illuminate\\Queue\\Events\\JobAttempted))
#110 ███████/laravel/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(315): Illuminate\\Events\\Dispatcher->{closure:Illuminate\\Events\\Dispatcher::makeListener():483}('Illuminate\\\\Queu...', Array)
#111 ███████/laravel/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(295): Illuminate\\Events\\Dispatcher->invokeListeners('Illuminate\\\\Queu...', Array, false)
#112 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(193): Illuminate\\Events\\Dispatcher->dispatch(Object(Illuminate\\Queue\\Events\\JobAttempted))
#113 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(139): Illuminate\\Queue\\SyncQueue->raiseJobAttemptedEvent(Object(Illuminate\\Queue\\Jobs\\SyncJob), false)
#114 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(107): Illuminate\\Queue\\SyncQueue->executeJob(Object(App\\███████\\Jobs\\███████Job), '', NULL)
#115 ███████/laravel/vendor/laravel/framework/src/Illuminate/Database/DatabaseTransactionsManager.php(211): Illuminate\\Queue\\SyncQueue->{closure:Illuminate\\Queue\\SyncQueue::push():107}()
#116 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(106): Illuminate\\Database\\DatabaseTransactionsManager->addCallback(Object(Closure))
#117 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/DeferredQueue.php(19): Illuminate\\Queue\\SyncQueue->push(Object(App\\███████\\Jobs\\███████Job), '', NULL)
#118 [internal function]: Illuminate\\Queue\\DeferredQueue->{closure:Illuminate\\Queue\\DeferredQueue::push():19}()
#119 ███████/laravel/vendor/laravel/framework/src/Illuminate/Support/Defer/DeferredCallback.php(52): call_user_func(Object(Closure))
#120 ███████/laravel/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(803): Illuminate\\Support\\Defer\\DeferredCallback->__invoke()
#121 ███████/laravel/vendor/laravel/framework/src/Illuminate/Support/Defer/DeferredCallbackCollection.php(53): rescue(Object(Illuminate\\Support\\Defer\\DeferredCallback))
#122 ███████/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Providers/FoundationServiceProvider.php(218): Illuminate\\Support\\Defer\\DeferredCallbackCollection->invokeWhen(Object(Closure))
#123 ███████/laravel/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(488): Illuminate\\Foundation\\Providers\\FoundationServiceProvider->{closure:Illuminate\\Foundation\\Providers\\FoundationServiceProvider::registerDeferHandler():217}(Object(Illuminate\\Queue\\Events\\JobAttempted))
#124 ███████/laravel/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(315): Illuminate\\Events\\Dispatcher->{closure:Illuminate\\Events\\Dispatcher::makeListener():483}('Illuminate\\\\Queu...', Array)
#125 ███████/laravel/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(295): Illuminate\\Events\\Dispatcher->invokeListeners('Illuminate\\\\Queu...', Array, false)
#126 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(193): Illuminate\\Events\\Dispatcher->dispatch(Object(Illuminate\\Queue\\Events\\JobAttempted))
#127 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(139): Illuminate\\Queue\\SyncQueue->raiseJobAttemptedEvent(Object(Illuminate\\Queue\\Jobs\\SyncJob), false)
#128 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(107): Illuminate\\Queue\\SyncQueue->executeJob(Object(App\\███████\\Jobs\\███████Job), '', NULL)
#129 ███████/laravel/vendor/laravel/framework/src/Illuminate/Database/DatabaseTransactionsManager.php(211): Illuminate\\Queue\\SyncQueue->{closure:Illuminate\\Queue\\SyncQueue::push():107}()
#130 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(106): Illuminate\\Database\\DatabaseTransactionsManager->addCallback(Object(Closure))
#131 ███████/laravel/vendor/laravel/framework/src/Illuminate/Queue/DeferredQueue.php(19): Illuminate\\Queue\\SyncQueue->push(Object(App\\███████\\Jobs\\███████Job), '', NULL)
#132 [internal function]: Illuminate\\Queue\\DeferredQueue->{closure:Illuminate\\Queue\\DeferredQueue::push():19}()
#133 ███████/laravel/vendor/laravel/framework/src/Illuminate/Support/Defer/DeferredCallback.php(52): call_user_func(Object(Closure))
#134 ███████/laravel/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(803): Illuminate\\Support\\Defer\\DeferredCallback->__invoke()
#135 ███████/laravel/vendor/laravel/framework/src/Illuminate/Support/Defer/DeferredCallbackCollection.php(53): rescue(Object(Illuminate\\Support\\Defer\\DeferredCallback))
#136 ███████/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Providers/FoundationServiceProvider.php(214): Illuminate\\Support\\Defer\\DeferredCallbackCollection->invokeWhen(Object(Closure))
#137 ███████/laravel/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(488): Illuminate\\Foundation\\Providers\\FoundationServiceProvider->{closure:Illuminate\\Foundation\\Providers\\FoundationServiceProvider::registerDeferHandler():213}(Object(Illuminate\\Console\\Events\\CommandFinished))
#138 ███████/laravel/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(315): Illuminate\\Events\\Dispatcher->{closure:Illuminate\\Events\\Dispatcher::makeListener():483}('Illuminate\\\\Cons...', Array)
#139 ███████/laravel/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(295): Illuminate\\Events\\Dispatcher->invokeListeners('Illuminate\\\\Cons...', Array, false)
#140 ███████/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(171): Illuminate\\Events\\Dispatcher->dispatch(Object(Illuminate\\Console\\Events\\CommandFinished))
#141 ███████/laravel/vendor/symfony/event-dispatcher/EventDispatcher.php(206): Illuminate\\Foundation\\Console\\Kernel->{closure:Illuminate\\Foundation\\Console\\Kernel::rerouteSymfonyCommandEvents():170}(Object(Symfony\\Component\\Console\\Event\\ConsoleTerminateEvent), 'console.termina...', Object(Symfony\\Component\\EventDispatcher\\EventDispatcher))
#142 ███████/laravel/vendor/symfony/event-dispatcher/EventDispatcher.php(56): Symfony\\Component\\EventDispatcher\\EventDispatcher->callListeners(Array, 'console.termina...', Object(Symfony\\Component\\Console\\Event\\ConsoleTerminateEvent))
#143 ███████/laravel/vendor/symfony/console/Application.php(1121): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch(Object(Symfony\\Component\\Console\\Event\\ConsoleTerminateEvent), 'console.termina...')
#144 ███████/laravel/vendor/symfony/console/Application.php(356): Symfony\\Component\\Console\\Application->doRunCommand(Object(App\\███████\\Console\\Commands\\███████), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#145 ███████/laravel/vendor/symfony/console/Application.php(195): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#146 ███████/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(198): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#147 ███████/laravel/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#148 {main}
```

So looking into the repeated pattern, we reach the function `function invokeListeners` which loops on the listeners `$this->getListeners($event)`
In `FoundationServiceProvider.php` we notice 
```
$this->app['events']->listen(function (JobAttempted $event) {
            app(DeferredCallbackCollection::class)->invokeWhen(fn ($callback) => $event->connectionName !== 'sync' && ($event->successful() || $callback->always));
        });
```
`$event->connectionName` in our case was not `sync` but rather `deferred` so after the deferred job was executed, `DeferredCallbackCollection` was invoked again. The job was retried rather than evicted.

The proposed fix is to ignore `deferred` as well as it is a derivative of `sync`. If it is deferred, we shouldn't be trying to execute the callbacks as we are already in the callbacks loop.

### Steps To Reproduce

Install Laravel >= v12.45.0
Create a job and in constructor add `$this->onConnection('deferred');` or set it while disbatching.
Dispatch the job from a command. (Should still work from web but command is easier to trace)
// The job itself in tinker won't have the issue, but the command running the job will, since it would have an end event that would trigger deferred.

Expected behavior:
Code executes and command finishes successfully.

Actual behavior:
Infinite loop till all resources are consumed.

Note:
The job in our project had a DB upsert, and `$this->afterCommit()` but I don't think think will have any effect.
I didn't provide a sample repo at the moment, but if it is necessary I can add it later.

### PR DESCRIPTION
**Pull request by cosmastech**
To close https://github.com/laravel/framework/issues/58351

Tested this locally. As described in the issue, this spawns an infinite loop. After this change, the job is executed and no infinite loop.

### CODE REVIEW

File: src/Illuminate/Foundation/Providers/FoundationServiceProvider.php [hunk 1]
```diff
@@ -215,7 +215,7 @@ protected function registerDeferHandler()
         });
 
         $this->app['events']->listen(function (JobAttempted $event) {
-            app(DeferredCallbackCollection::class)->invokeWhen(fn ($callback) => $event->connectionName !== 'sync' && ($event->successful() || $callback->always));
+            app(DeferredCallbackCollection::class)->invokeWhen(static fn ($callback) => ! in_array($event->connectionName, ['sync', 'deferred']) && ($event->successful() || $callback->always));
```
Comment (abkarino) [inline src/Illuminate/Foundation/Providers/FoundationServiceProvider.php:218]: Shouldn't the comparison be strict i.e. passing true? 
I don't know the code practices in here, but I believe for two values, two checks is faster than in_array. Though the difference would be minimal but the two conditions will support short circuiting.
