### PR TITLE
[11.x] Allows `enum_value()` to be use in standalone `illuminate/collections`

### LINKED ISSUE #53867: Cannot use standalone "illuminate/collections" package after upgrading to 11.35
### Laravel Version

11.35

### PHP Version

8.3.13

### Database Driver & Version

_No response_

### Description

I use the `illuminate/collections` as a standalone package a lot. (Thank you for that!) 

During the release of the 11.35, a new `functions.php` file was added with the `enum_value` function in it. That function depends on the `transform` function in `illuminate/support` which isn't a dependency of `illuminate/collections`. This leads to this error:

```
PHP Fatal error:  Uncaught Error: Call to undefined function Illuminate\Support\transform() in /home/runner/.composer/vendor/illuminate/collections/functions.php:20
```

I'm not sure what the fix is here because `illuminate/support` has a dependency on `illuminate/collections` which would make it a cyclical dependency if we add `illuminate/support` as a dependency. It might be wroth trying to implement `enum_value` without using `transform`.

### Steps To Reproduce

You can view the issue if you do a standalone install of `illuminate/collections` and navigate to `functions.php` in your IDE. You can see there's no definition for `transform`.

### PR DESCRIPTION
**Pull request by crynobone**
fixes #53867

### CODE REVIEW

File: src/Illuminate/Collections/functions.php [hunk 1]
```diff
@@ -17,11 +17,20 @@
...
+
+                default => $value,
+            }, $default ?? $value);
+        }
+
+        return match (true) {
             $value instanceof \BackedEnum => $value->value,
             $value instanceof \UnitEnum => $value->name,
 
             default => $value,
```
Comment (rodrigopedra) [inline src/Illuminate/Collections/functions.php:33]: Shouldn't the `default` arm be:

```php
    default => $value ?? $default,
```

Otherwise, the `$default` value is never used, when `transform()` isn't available

Comment (crynobone) [reply src/Illuminate/Collections/functions.php:33]: I probably going to remove `$default` options completely. It only used once in `ModelInspector` class.

Comment (crynobone) [reply src/Illuminate/Collections/functions.php]: on second thought, you suggest works fine but instead use `value($default)`. `value()` function available from `helpers.php` file in `illuminate/collections`
