### PR TITLE
[12.x] Render newlines in query tooltip

### LINKED ISSUE #57246: New lines in querys in exception page breaks frontend and built-in syntax on the page
### Laravel Version

12.32.5

### PHP Version

8.4.13

### Database Driver & Version

12.0.2-MariaDB-ubu2404 (Docker)

### Description

Hi,

There is a frontend issue, where in the layout and syntax highlighter breaks on the query component, this also causes text to overlay on other components on the page.

The problem happens here:
https://github.com/laravel/framework/blob/e821bfd3fc4013c11b3558fe6b33c8e6e26c7097/src/Illuminate/Foundation/resources/exceptions/renderer/components/query.blade.php#L113

It shows like this:
Image

### Steps To Reproduce

Make sure to create a model you can create a item to the database. in this example i've used the model `Audit`. 

Make the changes to `bootstrap/app.php` look like this:
```PHP
<?php

use Illuminate\Foundation\Application;
use Illuminate\Foundation\Configuration\Exceptions;
use Illuminate\Foundation\Configuration\Middleware;

return Application::configure(basePath: dirname(__DIR__))
    ->withRouting(
        web: __DIR__.'/../routes/web.php',
        commands: __DIR__.'/../routes/console.php',
        health: '/up',
    )
    ->withMiddleware(function (Middleware $middleware) {
        //
    })
    ->withExceptions(function (Exceptions $exceptions) {
        \App\Models\Audit::create([
            'log' => "A long text \n Look i'm on a new line! \n Another new line! \n Wheeee! \n We also break syntax! select from\n a new line! \n a new line! \n a new line! \n a new line!\n a new line! \n a new line! \n a new line! \n a new line\n a new line! \n a new line! \n a new line! \n a new line\n a new line! \n a new line! \n a new line! \n a new line!!!"
        ]);
    })->create();
```

### PR DESCRIPTION
**Pull request by faisuc**
This fixes frontend breakage on the exception renderer by escaping tooltip content and converting newlines to `<br>`. It applies to queries, formatted source, request headers, and routing values, preventing layout overlap and syntax highlighter glitches when tooltip content contains newlines. Fixes [#57246](https://github.com/laravel/framework/issues/57246).

No breaking changes. This affects only the debug exception renderer UI and does not change any APIs.

### CODE REVIEW

File: tests/Foundation/Exceptions/Renderer/RenderBladeFilesTest.php [hunk 1]
```diff
@@ -0,0 +1,78 @@
...
+    {
+        $frame = new class
+        {
+            public function class() { return null; }
+            public function previous() { return null; }
+            public function source() { return "Foo::bar(1)\nAnother line"; }
+        };
+
+        $root = realpath(__DIR__.'/../../../..');
+        $path = $root.'/src/Illuminate/Foundation/resources/exceptions/renderer/components/formatted-source.blade.php';
```
Comment (crynobone) [inline tests/Foundation/Exceptions/Renderer/RenderBladeFilesTest.php]: Use `Orchestra\Testbench\package_path('src/Illuminate/Foundation/resources/exceptions/renderer/components/formatted-source.blade.php');` function.

Comment (faisuc) [reply tests/Foundation/Exceptions/Renderer/RenderBladeFilesTest.php]: Thanks! PR updated.

File: src/Illuminate/Foundation/resources/exceptions/renderer/components/request-header.blade.php [hunk 2]
```diff
@@ -8,7 +8,7 @@
             <div class="uppercase text-neutral-500 dark:text-neutral-400 shrink-0">{{ $key }}</div>
             <div class="min-w-6 grow h-3 border-b-2 border-dotted border-neutral-300 dark:border-white/20"></div>
             <div class="truncate text-neutral-900 dark:text-white">
-                <span data-tippy-content="{{ $value }}">
+            <span data-tippy-content="{!! nl2br(e($value)) !!}">
```
Comment (crynobone) [inline src/Illuminate/Foundation/resources/exceptions/renderer/components/request-header.blade.php]:
```suggestion
                <span data-tippy-content="{!! nl2br(e($value)) !!}">
```

**Comment by crynobone** [comment]
Fixed failling tests

**Comment by avosalmon** [comment]
This PR wouldn't fix https://github.com/laravel/framework/issues/57246. The tooltip is not causing the issue, but text truncation is broken on syntax-highlighted queries. I opened a PR to fix text truncation. https://github.com/laravel/framework/pull/57315

Having said that, I think it's still nice to render newlines in the tooltip.

File: src/Illuminate/Foundation/resources/exceptions/renderer/components/formatted-source.blade.php [hunk 3]
```diff
@@ -19,5 +19,5 @@
     language="php"
     truncate
     class="text-xs min-w-0"
-    data-tippy-content="{{ $source }}"
+    data-tippy-content="{!! nl2br(e($source)) !!}"
```
Comment (avosalmon) [inline src/Illuminate/Foundation/resources/exceptions/renderer/components/formatted-source.blade.php]: I can't imagine `$source` contains newlines. The same goes for routing parameters and request headers.

File: src/Illuminate/Foundation/resources/exceptions/renderer/components/query.blade.php [hunk 4]
```diff
@@ -110,7 +110,7 @@ class="border border-neutral-200 dark:border-none bg-white dark:bg-white/[3%] ro
                     language="sql"
                     truncate
                     class="min-w-0"
-                    data-tippy-content="{{ $sql }}"
+                    data-tippy-content="{!! nl2br(e($sql)) !!}"
```
Comment (avosalmon) [inline src/Illuminate/Foundation/resources/exceptions/renderer/components/query.blade.php]: Blade automatically escapes the variable.

```suggestion
                    data-tippy-content="{{ nl2br($sql) }}"
```

Comment (faisuc) [reply src/Illuminate/Foundation/resources/exceptions/renderer/components/query.blade.php]: Thanks for the feedback!

For the query tooltip, the goal is to render actual line breaks inside the tooltip rather than escaped `<br>` tags. Using `{{ nl2br($sql) }}` would escape the `<br>` and show them as text, while `nl2br(e($sql))` inside `{!! !!}` keeps it safe (escaped first) and still displays formatted newlines correctly.

Regarding the suggestion to switch to `{{ nl2br($sql) }}`, that would break the newline rendering because Blade would re-escape the `<br>` tags. I’m keeping `nl2br(e($sql))` and outputting it as HTML so the SQL content is properly escaped before being rendered with `<br>`s:

`data-tippy-content="{!! nl2br(e($sql)) !!}"`


If you prefer avoiding raw braces, I can alternatively wrap it in an `HtmlString` so Blade won’t escape it again:

`data-tippy-content="{{ new \Illuminate\Support\HtmlString(nl2br(e($sql))) }}"`


I’ve updated the PR accordingly and kept this scoped only to queries, since other components like request headers or routing parameters are unlikely to contain newlines and don’t need the same handling.

Appreciate the clarification and review!

Comment (avosalmon) [reply src/Illuminate/Foundation/resources/exceptions/renderer/components/query.blade.php]: @faisuc With `{{ nl2br($sql) }}`, `nl2br` converts line breaks to `<br>` and then `{{ }}` escapes special characters, but [Tippy.js supports HTML content](https://atomiks.github.io/tippyjs/v6/all-props/#allowhtml).
https://github.com/laravel/framework/blob/95fc3d08a70e363c1cb3a6a9a5afe3566d777499/src/Illuminate/Foundation/resources/exceptions/renderer/scripts.js#L13

I tested this and confirmed that actual line breaks are rendered.

CleanShot 2025-10-10 at 13 40 30

File: src/Illuminate/Foundation/resources/exceptions/renderer/components/request-header.blade.php [hunk 5]
```diff
@@ -8,7 +8,7 @@
             <div class="uppercase text-neutral-500 dark:text-neutral-400 shrink-0">{{ $key }}</div>
             <div class="min-w-6 grow h-3 border-b-2 border-dotted border-neutral-300 dark:border-white/20"></div>
             <div class="truncate text-neutral-900 dark:text-white">
-                <span data-tippy-content="{{ $value }}">
+            <span data-tippy-content="{{ $value }}">
```
Comment (avosalmon) [inline src/Illuminate/Foundation/resources/exceptions/renderer/components/request-header.blade.php]:
```suggestion
                <span data-tippy-content="{{ $value }}">
```

File: src/Illuminate/Foundation/resources/exceptions/renderer/components/query.blade.php (hunk 4 above)
Comment (faisuc) [reply src/Illuminate/Foundation/resources/exceptions/renderer/components/query.blade.php]: PR updated
