### PR TITLE
[11.x] Where doesnt have nullable morph

### LINKED ISSUE #54315: whereDoesntHave not produce correct query when use with nullableMorphs
### Laravel Version

11.39.1

### PHP Version

8.2.12

### Database Driver & Version

sqlite / mysql

### Description

When use whereDoesntHave with nullableMorphs relation. it will not count nullable as dosent have.

### Steps To Reproduce

prepare project
1. create new project with laravel 10/11
2. create MainTable model by `php artisan make:model -m MainTable`
3. add `$table->nullableMorphs('relate');` to MainTable migration file
4. add morphTo relation to MainTable Model file `public function relate(){ return $this->morphTo(); }`
6. create Relate1model by `php artisan make:model -m Relate1`
7. migrate by `php artisan migrate`

test by this in `php artisan tinker`
```
use App\Models\MainTable;
use App\Models\Relate1;

$r1 = new Relate1();
$r1->save();


$m1 = new MainTable();
$m1->save();

$m2 = new MainTable();
$m2->relate()->associate($r1);
$m2->save();

DB::enableQueryLog();
echo MainTable::has('relate')->count(); // 1
echo MainTable::whereDoesntHave('relate')->count(); // 0 expect 1

var_dump(DB::getQueryLog());
```

it produce this query
```sql
select count(*) as aggregate from "main_tables" where (("main_tables"."relate_type" = ? and not exists (select * from "relate1s" where "main_tables"."relate_id" = "relate1s"."id")))
```
but it should be  (add `"main_tables"."relate_type" is null or `
```sql
select count(*) as aggregate from "main_tables" where ("main_tables"."relate_type" is null or ("main_tables"."relate_type" = ? and not exists (select * from "relate1s" where "main_tables"."relate_id" = "relate1s"."id")))
```

### PR DESCRIPTION
**Pull request by liamduckett**
Hey, this PR aims to resolve [this issue](https://github.com/laravel/framework/issues/54315).

The problem currently (as described in the issue) is that `QueriesRelationships::` excludes Models with a `null` `morph_type` value.

This is due to the logic in `QueriesRelationships::hasMorph` revolving around `types` (which exludes `null`):

```php
// src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php (231)
if ($types === ['*']) {
    $types = $this->model->newModelQuery()->distinct()->pluck($relation->getMorphType())
        ->filter()
        ->map(fn ($item) => enum_value($item))
        ->all();
}
```

My proposed solution adds a conditional clause to the query, to also include models with a `null` morph relation. I made the decision to widen the scope to include other operators - as this felt more complete of a solution than just solving for default `whereDoesntHave`. I understand this comes with it's own drawbacks, and am happy to partly undo if desired.

This only applies if the chosen `type` is wildcard, as I understand choosing types currently means any results must have that type of morph relation (and naturally, `null` cannot acheieve this). Truthfully I'm not particularily confident on this bit - would appreciate any checking over!

I've only added the test case from the issue, as it feels like the majority use case. 

Please see my logic for deciding which operators to include below.

```
operators;
1. >=
  a) positive: doesnt need nulls as is inclusionary
  b) zero:     will always be true...
  c) negative: will always be true...
2. >
  a) positive: doesnt need nulls as is inclusionary
  b) zero:     doesnt need nulls as is inclusionary
  c) negative: will always be true...
3. <=
  a) positive: needs nulls as is exclusionary
  b) zero:     needs nulls as is exclusionary
  c) negative: can never be true...
4. <
  a) positive: needs nulls as is exclusionary
  b) zero:      can never be true...
  c) negative: can never be true...
5. =
  a) positive: doesnt need nulls as is inclusionary
  b) zero:     needs nulls as is exclusionary
  c) negative: can never be true...
6. !=
  a) positive: needs nulls as is exclusionary
  b) zero:     doesnt need nulls as is inclusionary
  c) negative: will always be true...
```

### CODE REVIEW

File: src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php [hunk 1]
```diff
@@ -219,7 +212,6 @@ public function orWhereDoesntHave($relation, ?Closure $callback = null)
      * @param  string  $operator
      * @param  int  $count
      * @param  string  $boolean
-     * @param  \Closure|null  $callback
```
Comment (crynobone) [inline src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php:222]: You shouldn't remove existing docblock, please revert this.

File: src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php [hunk 2]
```diff
@@ -203,7 +197,6 @@ public function whereDoesntHave($relation, ?Closure $callback = null)
      * Add a relationship count / exists condition to the query with where clauses and an "or".
      *
      * @param  \Illuminate\Database\Eloquent\Relations\Relation<*, *, *>|string  $relation
-     * @param  \Closure|null  $callback
```
Comment (crynobone) [inline src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php:206]: You shouldn't remove existing docblock, please revert this.

File: src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php [hunk 3]
```diff
@@ -191,7 +186,6 @@ public function orWhereHas($relation, ?Closure $callback = null, $operator = '>=
      * Add a relationship count / exists condition to the query with where clauses.
      *
      * @param  \Illuminate\Database\Eloquent\Relations\Relation<*, *, *>|string  $relation
-     * @param  \Closure|null  $callback
```
Comment (crynobone) [inline src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php:194]: You shouldn't remove existing docblock, please revert this.

File: src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php [hunk 4]
```diff
@@ -177,7 +173,6 @@ public function withWhereHas($relation, ?Closure $callback = null, $operator = '
      * Add a relationship count / exists condition to the query with where clauses and an "or".
      *
      * @param  \Illuminate\Database\Eloquent\Relations\Relation<*, *, *>|string  $relation
-     * @param  \Closure|null  $callback
```
Comment (crynobone) [inline src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php:180]: You shouldn't remove existing docblock, please revert this.

File: src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php [hunk 5]
```diff
@@ -162,7 +159,6 @@ public function whereHas($relation, ?Closure $callback = null, $operator = '>=',
      * Also load the relationship with same condition.
      *
      * @param  \Illuminate\Database\Eloquent\Relations\Relation<*, *, *>|string  $relation
-     * @param  \Closure|null  $callback
```
Comment (crynobone) [inline src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php:165]: You shouldn't remove existing docblock, please revert this.

File: src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php [hunk 6]
```diff
@@ -308,7 +308,6 @@ public function orHasMorph($relation, $types, $operator = '>=', $count = 1)
      * @param  \Illuminate\Database\Eloquent\Relations\MorphTo<*, *>|string  $relation
      * @param  string|array  $types
      * @param  string  $boolean
-     * @param  \Closure|null  $callback
```
Comment (crynobone) [inline src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php:311]: You shouldn't remove existing docblock, please revert this.

File: src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php [hunk 7]
```diff
@@ -333,7 +332,6 @@ public function orDoesntHaveMorph($relation, $types)
      *
      * @param  \Illuminate\Database\Eloquent\Relations\MorphTo<*, *>|string  $relation
      * @param  string|array  $types
-     * @param  \Closure|null  $callback
```
Comment (crynobone) [inline src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php:336]: You shouldn't remove existing docblock, please revert this.

File: src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php [hunk 8]
```diff
@@ -348,7 +346,6 @@ public function whereHasMorph($relation, $types, ?Closure $callback = null, $ope
...
```
Comment (crynobone) [inline src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php:351]: You shouldn't remove existing docblock, please revert this.

File: src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php [hunk 9]
```diff
@@ -363,7 +360,6 @@ public function orWhereHasMorph($relation, $types, ?Closure $callback = null, $o
...
```
Comment (crynobone) [inline src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php:366]: You shouldn't remove existing docblock, please revert this.

File: src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php [hunk 10]
```diff
@@ -376,7 +372,6 @@ public function whereDoesntHaveMorph($relation, $types, ?Closure $callback = nul
...
```
Comment (crynobone) [inline src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php:379]: You shouldn't remove existing docblock, please revert this.

File: src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php [hunk 11]
```diff
@@ -930,11 +925,6 @@ public function mergeConstraintsFrom(Builder $from)
 
     /**
      * Updates the table name for any columns with a new qualified name.
-     *
-     * @param  array  $wheres
-     * @param  string  $from
-     * @param  string  $to
-     * @return array
```
Comment (crynobone) [inline src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php:937]: You shouldn't remove existing docblock, please revert this.

File: src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php [hunk 12]
```diff
@@ -950,7 +940,6 @@ protected function requalifyWhereTables(array $wheres, string $from, string $to)
     /**
      * Add a sub-query count clause to this query.
      *
-     * @param  \Illuminate\Database\Query\Builder  $query
```
Comment (crynobone) [inline src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php:953]: You shouldn't remove existing docblock, please revert this.

**Review by crynobone — CHANGES_REQUESTED** [review]

File: src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php (hunk 12 above)
Comment (liamduckett) [reply src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php]: Apologies - wasn't intentional!

**Review by crynobone — APPROVED** [review]
