### PR TITLE
[11.x] Fix deprecation warnings in `optimize:clear` and `optimize`

### LINKED ISSUE #54190: Deprecation on optimize commands
### Laravel Version

11.38.1

### PHP Version

8.4.2

### Database Driver & Version

_No response_

### Description

The command ```php artisan optimize``` and ```php artisan optimize:clear``` trigger some deprecations on the php ```explode()``` function.

```
[2025-01-14 21:00:31] local.WARNING: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/OptimizeClearCommand.php on line 37

[2025-01-14 21:00:31] local.WARNING: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/OptimizeCommand.php on line 37
```

### Steps To Reproduce

Enable deprecations and use the following commands:
php artisan optimize
php artisan optimize:clear

### PR DESCRIPTION
**Pull request by cosmastech**
To resolve https://github.com/laravel/framework/issues/54190

Passing null to `explode()` produces a deprecation warning. I coalesced the option to a blank string, and modified the tests so the tests will fail if there's a deprecation warning.

### CODE REVIEW

File: src/Illuminate/Foundation/Console/OptimizeClearCommand.php [hunk 1]
```diff
@@ -34,7 +34,7 @@ public function handle()
     {
         $this->components->info('Clearing cached bootstrap files.');
 
-        $exceptions = Collection::wrap(explode(',', $this->option('except')))
+        $exceptions = Collection::wrap(explode(',', $this->option('except') ?? ''))
```
Comment (shaedrich) [inline src/Illuminate/Foundation/Console/OptimizeClearCommand.php:37]: Is there the need, to call all these at all if `$this->option('except')` is null? Maybe let's just wrap that in an `if` statement

Comment (shaedrich) [reply src/Illuminate/Foundation/Console/OptimizeClearCommand.php:37]: see #54214
