### PR TITLE
[6.x] Fix channel names when broadcasting via redis

### LINKED ISSUE #407: Can't recieve broadcasted message from laravel echo server
In laravel-echo-console:
```

L A R A V E L  E C H O  S E R V E R

version 1.5.2

⚠ Starting server in DEV mode...

✔  Running at localhost on port 6001
✔  Channels are ready.
✔  Listening for redis events...

Server ready!

[7:07:00 PM] - YSTAl2zDJP0HtuoCAAAA joined channel: public
[7:07:00 PM] - Sending auth request to: https://xxxxx/broadcasting/auth

[7:07:00 PM] - YSTAl2zDJP0HtuoCAAAA authenticated for: private-survey.2
[7:07:00 PM] - YSTAl2zDJP0HtuoCAAAA joined channel: private-survey.2


Channel: laravel_database_private-survey.2
Event: server.message
```
All looks fine, but I can't recieve this message in browser:

```
window.Echo.private('survey.2')
 .listen('.server.message', (e) => {
        console.log(e)  
});
e {events: {…}, name: "private-survey.2", socket: p, options: {…}, eventFormatter: t}
```
My event class:
```

   public function __construct($message)
    {
        $this->message = $message;
    }

    public function broadcastOn()
    {
        return new PrivateChannel('survey.2');
    }

    public function broadcastAs()
    {
        return 'server.message';
    }
```
In laravel telescope I see:

```
{
  message: "wdfwsfwf",
  socket: null
}
```
does it normal that socket is null? Also always 0 listeners for this event.

What's wrong?

### LINKED ISSUE #477: Broadcasting not working with laravel/framework v6.11.0 (released 2020-01-14)
Broadcasting not working with v6.11.0. I had to reverted back to laravel/framework 6.10.1

v6.11.0 (2020-01-14)

Added
Added Illuminate\Database\Eloquent\Builder::firstWhere() method (#31089)
**Redis Broadcaster: Broadcast to multiple channels at once (#[31108](https://github.com/laravel/framework/pull/31108))**

### PR DESCRIPTION
**Pull request by timoschwarzer**
#31108 introduced publishing events to multiple channels at once using a Lua script. When publishing events through the Lua script, the `Redis::OPT_PREFIX` option does not apply and needs to be prepended manually.

Fixes in external projects:
Fixes https://github.com/tlaverdure/laravel-echo-server/issues/477
Fixes https://github.com/tlaverdure/laravel-echo-server/issues/407

### CODE REVIEW

File: src/Illuminate/Broadcasting/Broadcasters/Broadcaster.php [hunk 1]
```diff
@@ -233,12 +233,13 @@ protected function isImplicitlyBindable($key, $parameter)
      * Format the channel array into an array of strings.
      *
      * @param  array  $channels
+     * @param  string  $prefix
      * @return array
      */
-    protected function formatChannels(array $channels)
+    protected function formatChannels(array $channels, $prefix = '')
```
Comment (driesvints) [inline src/Illuminate/Broadcasting/Broadcasters/Broadcaster.php]: We can't break the method signature here on a minor release. Can this be solved any other way? Otherwise this will have to go to the master branch for the next release.

Comment (timoschwarzer) [reply src/Illuminate/Broadcasting/Broadcasters/Broadcaster.php]: Even if the parameter is optional?
I could also override `formatChannels` in `RedisBroadcaster` with a call to parent and then apply the prefix. What do you think about that?

Comment (timoschwarzer) [reply src/Illuminate/Broadcasting/Broadcasters/Broadcaster.php]: @driesvints should be resolved with my last commit.

**Review by GrahamCampbell — APPROVED** [review]
This looks much better than the first attempt.

File: src/Illuminate/Broadcasting/Broadcasters/Broadcaster.php (hunk 1 above)
Comment (driesvints) [reply src/Illuminate/Broadcasting/Broadcasters/Broadcaster.php]: > Even if the parameter is optional?
Yeah, if a downstream implementation of the broadcaster implements the method it'll break execution.

Comment (timoschwarzer) [reply src/Illuminate/Broadcasting/Broadcasters/Broadcaster.php]: Right, makes sense :man_facepalming:
