### PR TITLE
[5.6] Fix #23592 (SeeInOrder)

### LINKED ISSUE #23592: assertSeeInOrder does not actually assert anything
- Laravel Version: 5.6.12
- PHP Version: 7.2

$response->assertSeeInOrder does not actually assert anything, but instead calls PHPUnit::fail() if the conditions are not met. This causes tests which only have that assertion to be reported as "risky".

```
public function assertSeeInOrder(array $values)
    {
        $position = 0;

        foreach ($values as $value) {
            $valuePosition = mb_strpos($this->getContent(), $value, $position);

            if ($valuePosition === false || $valuePosition < $position) {
                PHPUnit::fail(
                    'Failed asserting that \''.$this->getContent().
                    '\' contains "'.$value.'" in specified order.'
                );
            }

            $position = $valuePosition + mb_strlen($value);
        }

        return $this;
    }

// A test which only uses this assertion will be reported as "risky" by PHPUnit because of not running any assertions.
public function canViewAlbumTitleFromBandView()
    {
        $band = factory(Band::class)->create();
        $album = factory(Album::class)->create([
            'band_id' => $band->id
        ]);

        // visit the page
        $response = $this->get("/bands/$band->id");

        // assert we can see the data
        $response->assertSeeInOrder(['Albums:', $album->name]);
    }
```

Yes, in my case I could just write different assertions that would assert reliably, but isn't this bad practice to be including built-in custom assertions that don't actually assert anything? Shouldn't we be able to write a custom assertion class instead?

### PR DESCRIPTION
**Pull request by Jantho1990**
This adds a SeeInOrder PHPUnit Constraint to address Issue #23592. Calling `assertSeeInOrder()` or `assertSeeTextInOrder()` should now result in PHPUnit registering that assertions were made (and thus not marking tests with only those assertions as risky). Also added a test file to make sure PHPUnit is calling the assertions.

### CODE REVIEW

File: src/Illuminate/Foundation/Testing/Constraints/SeeInOrder.php [hunk 1]
```diff
@@ -0,0 +1,85 @@
...
+     * The value that failed. Used to display in the error message.
+     *
+     * @var string
+     */
+    protected $failedValue;
+
+    /**
+     * The string we want to check the content of.
+     *
+     * @var
```
Comment (carusogabriel) [inline src/Illuminate/Foundation/Testing/Constraints/SeeInOrder.php]: Missing `var` type.

Strange that Style CI didn't cached it :thinking:

**Review by carusogabriel — CHANGES_REQUESTED** [review]

File: src/Illuminate/Foundation/Testing/Constraints/SeeInOrder.php (hunk 1 above)
Comment (GrahamCampbell) [reply src/Illuminate/Foundation/Testing/Constraints/SeeInOrder.php]: It's not a code style bug, that's why. It's just a syntax error.
