### PR TITLE
[11.X] "Model::preventAccessingMissingAttributes()" Causes Exception During Pagination with ResourceCollection

### LINKED ISSUE #52214: "Model::preventAccessingMissingAttributes()" Causes Exception During Pagination with ResourceCollection
### Laravel Version

11.16.0

### PHP Version

8.3.9

### Database Driver & Version

MariaDB 11.4.2

### Description

When using pagination with `ResourceCollection` while `Model::preventAccessingMissingAttributes()` is activated, an attempt to access `resource` attributes occurs. This access results in a violation of the prevent access to missing attributes policy, causing an exception to be thrown.

```
"message": "The attribute [resource] either does not exist or was not retrieved for model [App\\Models\\User].",
"exception": "Illuminate\\Database\\Eloquent\\MissingAttributeException"
```

### Steps To Reproduce

- install new laravel instance
- create 1 user using the default seeder `php artisan db:seed`
- in `AppServiceProvider` add in the register method this `Model::shouldBeStrict();` or this `Model::preventAccessingMissingAttributes();`
- make a UserCollection `php artisan make:resource UserCollection`
- in any route now return this `return new UserCollection(User::paginate());`

### PR DESCRIPTION
**Pull request by Katalam**
Will close #52214

Hopefully the test will pass, I had some problems with it while running it locally.

The problem is that we expect a null value here, but at the same time we prevent a non present access of properties

### CODE REVIEW

File: src/Illuminate/Http/Resources/Json/PaginatedResourceResponse.php [hunk 1]
```diff
@@ -28,7 +28,7 @@ public function toResponse($request)
             $this->resource->jsonOptions()
         ), function ($response) use ($request) {
             $response->original = $this->resource->resource->map(function ($item) {
-                return is_array($item) ? Arr::get($item, 'resource') : $item->resource;
+                return is_array($item) ? Arr::get($item, 'resource') : optional($item)->resource;
```
Comment (andreich1980) [inline src/Illuminate/Http/Resources/Json/PaginatedResourceResponse.php:31]: `$item?->resource`?
🤔
