### PR TITLE
[10.x] Fix collection shift less than one item

### LINKED ISSUE #51684: Collection->shift(0) shifts 2 items instead of 0
### Laravel Version

11.x

### PHP Version

8.1.28

### Database Driver & Version

_No response_

### Description

The method contains the following lines:

```
        foreach (range(1, min($count, $collectionCount)) as $item) {
            array_push($results, array_shift($this->items));
        }
```

Where `min($count, $collectionCount)` evaluates to 0 and then `range(1, 0)` evaluates to `[1, 0]`, which is an array with a length of 2, causing 2 items to be shifted instead of 0.

Passing in a negative argument makes it shift even more items, e.g. -1 shifts 3. Negative arguments should probably be disallowed and throw an InvalidArgumentException?

### Steps To Reproduce

In Tinker:
```
$c = collect([10, 20, 30, 40])
$c->shift(0) // returns [10, 20]
$c // [30, 40]
```

Expected behavior:
```
$c = collect([10, 20, 30, 40])
$c->shift(0) // returns []
$c // [10, 20, 30, 40]
```

### PR DESCRIPTION
**Pull request by faissaloux**
Helloo 👋🏻 

In this PR I have fixed the `collection shift()` behaviour when trying to shift less than one item.

Fixes #51684

----
#### Current
```php
$collection = new Collection(['foo', 'bar', 'baz']);
echo $collection->shift(0); // ['foo', 'bar']
echo $collection; // ['baz']
````

#### Expected
```php
$collection = new Collection(['foo', 'bar', 'baz']);
echo $collection->shift(0); // []
echo $collection; // ['foo', 'bar', 'baz']
````
----
#### Current
```php
$collection = new Collection(['foo', 'bar', 'baz']);
echo $collection->shift(-1); // ['foo', 'bar', 'baz']
echo $collection; // []
````

#### Expected
```php
$collection = new Collection(['foo', 'bar', 'baz']);
echo $collection->shift(-1); // InvalidArgumentException
```

### CODE REVIEW

File: src/Illuminate/Collections/Collection.php [hunk 1]
```diff
@@ -1124,15 +1125,21 @@ public function search($value, $strict = false)
...
-            return array_shift($this->items);
+        if ($count === 0 || $this->isEmpty()) {
+            return new static;
         }
 
-        if ($this->isEmpty()) {
-            return new static;
+        if ($count < 0) {
+            throw new InvalidArgumentException('can not shift less than 0.');
+        }
```
Comment (fgaroby) [inline src/Illuminate/Collections/Collection.php:1139]: I think this `if`` should be the first one.

**Comment by tanerkay** [comment]
this is a BC break when `count === 1` (the default)

the behaviour of `collect()->shift()` has now changed to return an empty collection instead of `null`
