### PR TITLE
[5.1] Fix bindings on unions by added a new binding type

### LINKED ISSUE #9777: [5.1.8] Query\Builder bindings order messed up
There is a bug with the order of the bindings when using `union()`. Code to reproduce:

```php
$a = \DB::table('foo')->where('a', 'eq a');
$b = \DB::table('bar')->groupBy('b')->having('b', '!=', 'neq b')->union($a);

$b->toSql();
// => "(select * from `bar` group by `b` having `b` != ?) union (select * from `foo` where `a` = ?)"
$b->getBindings();
// => [ "eq a", "neq b" ]
// Expected [ "neq b", "eq a" ]
```

### PR DESCRIPTION
**Pull request by thomasruiz**
Fixes #9777.

The query was not able to know which union query had which binding. We need to add a new binding type `union` that takes the subquery bindings instead of merging them.

### CODE REVIEW

**Comment by JesseLeite** [comment]
<3

File: tests/Database/DatabaseQueryBuilderTest.php [hunk 1]
```diff
@@ -310,6 +310,12 @@ public function testUnions()
         $builder->union($this->getMySqlBuilder()->select('*')->from('users')->where('id', '=', 2));
         $this->assertEquals('(select * from `users` where `id` = ?) union (select * from `users` where `id` = ?)', $builder->toSql());
         $this->assertEquals([0 => 1, 1 => 2], $builder->getBindings());
+
+        $builder = $this->getMysqlBuilder();
+        $second = $this->getMysqlBuilder()->select('*')->from('users')->orderByRaw('id = ?', 2);
+        $third = $this->getMysqlBuilder()->select('*')->from('users')->where('id', 3)->groupBy('id')->having('id', '!=', 4);
+        $builder->groupBy('a')->having('a', '=', 1)->union($second)->union($third);
+        $this->assertEquals([0 => 1, 1 => 2, 2 => 3, 3 => 4], $builder->getBindings());
```
Comment (lukasgeiter) [inline tests/Database/DatabaseQueryBuilderTest.php]: I think those tests should rather use the generic builder (`$this->getBuilder()`) instead of the MySQL specific one...

**Comment by thomasruiz** [comment]
I just noticed that unions were not the only ones causing problem.

Look at this test @GrahamCampbell:

```
$builder = $this->getBuilder();
$builder->select('*')->from('users')->where('email', '=', function ($q) {
    $q->select(new Raw('max(id)'))
        ->from('users')->where('email', '=', 'bar')
        ->groupBy('id')->having('id', '=', 4);
})->orWhere('id', '=', 'foo')->groupBy('id')->having('id', '=', 5);
// $builder->getBindings() -> ['bar', 'foo', 4, 5] instead of ['bar', 4, 'foo', 5]
```

**Comment by JesseLeite** [comment]
Dang.  Thank you for your work on this @thomasruiz.  These binding issues when using subqueries is pretty scary.

**Comment by taylorotwell** [comment]
Is this ready or needs more work?

**Comment by JesseLeite** [comment]
@thomasruiz thank you!
