### PR TITLE
[12.x] Rename `group` to `messageGroup` property

### LINKED ISSUE #56895: ExampleJob and Queueable define the same property ($group)
### Laravel Version

12.27.0

### PHP Version

8.4

### Database Driver & Version

N/A

### Description

See: https://github.com/laravel/framework/pull/56763

Adding the $group property to Queueable has broken existing Jobs that also define this property.

> [!CAUTION]
> App\Jobs\ExampleJob and Illuminate\Bus\Queueable define the same property ($group) in the composition of App\Jobs\ExampleJob. However, the definition differs and is considered incompatible. Class was composed

Obviously there will have to be some property name used here, but maybe we could agree on a term less common than $group?

Or we move it to a new trait?

### Steps To Reproduce

```php
<?php

namespace App\Jobs;

use App\Models\Group;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;

class ExampleJob implements ShouldQueue
{
    use Queueable;

    public function __construct(public Group $group) {}
}

```

### PR DESCRIPTION
**Pull request by crynobone**
fix #56895

### CODE REVIEW

File: src/Illuminate/Queue/SqsQueue.php [hunk 1]
```diff
@@ -223,7 +223,13 @@ protected function getQueueableOptions($job, $queue): array
 
         $transformToString = fn ($value) => strval($value);
 
-        $messageGroupId = transform($job->group ?? null, $transformToString);
+        $messageGroup = $job->messageGroup ?? null;
+
+        if (is_null($messageGroup) && isset($job->group) && is_string($job->group)) {
+            $messageGroup = $job->group;
+        }
```
Comment (crynobone) [inline src/Illuminate/Queue/SqsQueue.php]: This is just to prevent breaking changes on any existing queues. We can remove it for 13 release.

Comment (AhmedAlaa4611) [reply src/Illuminate/Queue/SqsQueue.php]: What if the job instance doesn't have the `$messageGroup` property but instead has a `$group` property that is **not related** to Amazon SQS? I believe the same issue we're trying to solve would still exist in that case.

Also, I don't think we need to worry about breaking changes here, since the original PR was only merged 5 days ago.

Comment (crynobone) [reply src/Illuminate/Queue/SqsQueue.php]: 1. It has to be a FIFO queue on SQS
2. `$group` has to a string and not unique to be grouped by SQS

the chance of that is minimal to non existent.

Comment (Brenneisen) [reply src/Illuminate/Queue/SqsQueue.php]: So, we have jobs that have a `$group` and also a `string` or hash value. The name `$group` is too general and will most likely also be used in the app context. Strings can also occur here. In my opinion, a name should simply be chosen that does not conflict with job attributes from the app context. I don't think it's a breaking change to consistently rename it now. The bigger breaking change is the variable `$group`, which breaks existing applications. There shouldn't be that many people who use the new feature directly in production and would therefore be affected by a change from `$group` to another name.

Comment (cosmastech) [reply src/Illuminate/Queue/SqsQueue.php]: Would using a property name like `$_messageGroup` solve the issue?

Comment (crynobone) [reply src/Illuminate/Queue/SqsQueue.php]: @Brenneisen are you using SQS FIFO queue at the moment with `$group` property but doesn't intend to use Fair queue by setting `onGroup()`?

By default, SQS uses standard queue and not affected by this.
