### PR TITLE
[12.x] Ensure File fail doesn't double translate in fail()

### LINKED ISSUE #58596: Illuminate\Validation\Rules\File tries to translate already translated phrases
### Laravel Version

12.44.0

### PHP Version

8.4.11

### Database Driver & Version

_No response_

### Description

Hello. We use `Lang::handleMissingKeysUsing` on our website to track missing translations. This feature helps a lot, but we encounter multiple false positive reports.

Long story short, there seems to be a bug in `Illuminate\Validation\Rules\File` class. The following code tries to translate already translated messages unconditionally:

```
    /**
     * Adds the given failures, and return false.
     *
     * @param  array|string  $messages
     * @return bool
     */
    protected function fail($messages)
    {
        $messages = Collection::wrap($messages)
            ->map(fn ($message) => $this->validator->getTranslator()->get($message))
            ->all();

        $this->messages = array_merge($this->messages, $messages);

        return false;
    }
```

### Steps To Reproduce

I've simplified our source code to this reproducer:

```
\Illuminate\Support\Facades\Lang::handleMissingKeysUsing(function ($key) {
	dump($key);
});

$request = new \Illuminate\Http\Request([
	'file' => \Illuminate\Http\UploadedFile::fake()->create('file.pdf'),
]);

try {
	$request->validate([
		'file' => [
			\Illuminate\Validation\Rules\File::types(['txt'])
		]
	]);
} catch (\Throwable) {

}
```

You'll see `The file field must be a file of type: txt.` among "missing" translation keys. Obviously, this phrase is already translated and should not be valued as untranslated.

### PR DESCRIPTION
**Pull request by jackbayliss**
Closes https://github.com/laravel/framework/issues/58596

The File validation `fail()` method attempts to translate messages that have already been translated by the validator, causing false positives when using `Lang::handleMissingKeysUsing()` to track missing translations.

The translation is already done via the validator addFailure method afaik. Thought this would be useful to remove as makes it a tiny bit more efficient either way.

Have added a test to cover this use case.. and added tests to cover custom messages for all file rules just to be sure there's no regression / we can be certain its not gonna break anything.

Can target 13.x if you prefer

### CODE REVIEW

File: src/Illuminate/Validation/Rules/File.php [hunk 1]
```diff
@@ -357,11 +356,7 @@ protected function buildMimetypes()
      */
     protected function fail($messages)
     {
-        $messages = Collection::wrap($messages)
-            ->map(fn ($message) => $this->validator->getTranslator()->get($message))
-            ->all();
-
-        $this->messages = array_merge($this->messages, $messages);
+        $this->messages = array_merge($this->messages, Arr::wrap($messages));
```
Comment (jackbayliss) [inline src/Illuminate/Validation/Rules/File.php:359]: We wrap here as $messages can be a string or array, this follows what the Password rule does.
