### PR TITLE
[6.x] Fixed bad dependency assumptions

### LINKED ISSUE #31891: Scheduler depends on globally available illuminate/foundation helpers
- Laravel Version: 5.4.0 - 7.0.4
- PHP Version: 7.3.7, not relevant
- Database Driver & Version: n/a

### Description:
At the moment the Scheduler component within `illuminate/console` depends on globally available `dispatch` and `dispatch_now` functions, this introduces an undocumented dependency between the Laravel framework as a whole, and the `illuminate/console` component. I'm willing to look into fixing this, because there has been a push in the past to make stuff less dependent on `illuminate/foundation`, but I'm raising an issue here first because most of my efforts towards these kinds of PRs have been met with lukewarm response so far.

The dependency on these helpers was introduced in the 5.4.0 branch, which is why I included it in the version range.

### Steps To Reproduce:
- `composer require illuminate/console`
- Create a Schedule, use it to dispatch stuff on crontab
- observe undefined function errors

### PR DESCRIPTION
**Pull request by GrahamCampbell**
1. The scheduler uses the native container (and not the contract), and so we must ensure that it is recommended to users both by composer, and by friendly runtime exceptions. If we wanna refactor it to use the contract, that is a job for the master branch.
2. We should not be calling stuff from the foundation helper functions file. We should instead be resolving the jobs and the job dispatcher from the container, and providing good developer experience if we fail to resolve it. Removal of the calls to the foundation functions also made it clear we actually had an dependency on `illuminate/queue` too, for packing Closures.

---

Closes #31891.

### CODE REVIEW

**Comment by nmokkenstorm** [comment]
I opened the issue to start a disccusion, but this works too. Wouldn't injecting an implementation of `Illuminate\Contracts\Container\Container` be way easier instead of dynamically checking if an instance can be resolved? Right now you're adding `illuminate\container` as an optional dependency, but in reality this whole class doesn't work without it being available.

This is by no means meant as critique, it just doesn't match the approach I had in mind, so I'm trying to follow your thought process here.

**Comment by GrahamCampbell** [comment]
> I opened the issue to start a disccusion, but this works too. Wouldn't injecting an implementation of Illuminate\Contracts\Container\Container be way easier instead of dynamically checking if an instance can be resolved?

We have no means of doing that without having a container, and even if we could, as I said, that would fall out of the remit of a bug fix. Such a refactoring would have to target the master branch.

**Comment by GrahamCampbell** [comment]
Hmmm. D'no why the tests are failing... They fail with or without my changes to the tests.

File: src/Illuminate/Console/Scheduling/Schedule.php [hunk 1]
```diff
@@ -107,18 +125,52 @@ public function command($command, array $parameters = [])
...
+            $job = is_string($job) ? Container::getInstance()->make($job) : $job;
 
             if ($job instanceof ShouldQueue) {
-                dispatch($job)
-                    ->onConnection($connection ?? $job->connection)
-                    ->onQueue($queue ?? $job->queue);
+                $this->disptachToQueue($job, $connection ?? $job->connection, $queue ?? $job->queue);
             } else {
-                dispatch_now($job);
+                $this->disptachNow($job);
```
Comment (peterchrjoergensen) [inline src/Illuminate/Console/Scheduling/Schedule.php]: Spelling

File: src/Illuminate/Console/Scheduling/Schedule.php [hunk 2]
```diff
@@ -107,18 +125,52 @@ public function command($command, array $parameters = [])
...
     {
         return $this->call(function () use ($job, $queue, $connection) {
-            $job = is_string($job) ? resolve($job) : $job;
+            $job = is_string($job) ? Container::getInstance()->make($job) : $job;
 
             if ($job instanceof ShouldQueue) {
-                dispatch($job)
-                    ->onConnection($connection ?? $job->connection)
-                    ->onQueue($queue ?? $job->queue);
+                $this->disptachToQueue($job, $connection ?? $job->connection, $queue ?? $job->queue);
```
Comment (peterchrjoergensen) [inline src/Illuminate/Console/Scheduling/Schedule.php]: Spelling
