### PR TITLE
[10.x] Fix validation message used for max file size

### LINKED ISSUE #49875: File validation message uses instanceof UploadedFile instead of File
### Laravel Version

10.34.2

### PHP Version

8.2.13

### Database Driver & Version

N/A

### Description

When using the validator with a manually passed `Illuminate\Http\File` object, the validation seems to work as expected. The `getSize` method checks for a Symfony file to determine on how to check that:

https://github.com/laravel/framework/blob/fb9d508f62690dbbfc44150dd2831c4bc1412f83/src/Illuminate/Validation/Concerns/ValidatesAttributes.php#L2482-L2484

But the returned error message is wrong, as it uses the `string` message. This seems to be due to the fact that the message formatter does an instanceof `Illuminate\Http\UploadedFile`:

https://github.com/laravel/framework/blob/fb9d508f62690dbbfc44150dd2831c4bc1412f83/src/Illuminate/Validation/Concerns/FormatsMessages.php#L225-L227

I'd expect to both use the same condition to determine on how to validate and on what message to use.

### Steps To Reproduce

Example Snippet:

```php
$v = \Illuminate\Support\Facades\Validator::make(
    ['file' => new \Illuminate\Http\File('composer.json')],
    ['file' => 'max:1']
);

dd($v->passes(), $v->messages()->all());
```

### PR DESCRIPTION
**Pull request by mateusjunges**
This attempts to fix #49875 

When validating a manually created file (`Illuminate\Http\File`) and applying a rule for file size, the validation message erroneously defaults to `validation.max.string`. This occurs due to the validator's failure to detect the attribute type, falling back to the string type.

I added a condition to check for an `Illuminate\Http\File` instance, which fixes the issue

### CODE REVIEW

File: src/Illuminate/Validation/Concerns/FormatsMessages.php [hunk 1]
```diff
@@ -218,15 +219,13 @@ protected function getAttributeType($attribute)
...
-        } elseif ($this->getValue($attribute) instanceof UploadedFile) {
-            return 'file';
-        }
-
-        return 'string';
+        return match (true) {
+            $this->hasRule($attribute, $this->numericRules) => 'numeric',
+            $this->hasRule($attribute, ['Array']) => 'array',
+            $this->getValue($attribute) instanceof UploadedFile => 'file',
+            $this->getValue($attribute) instanceof File => 'file',
```
Comment (driesvints) [inline src/Illuminate/Validation/Concerns/FormatsMessages.php:226]:
```suggestion
            $this->getValue($attribute) instanceof UploadedFile,
            $this->getValue($attribute) instanceof File => 'file',
```

**Review by driesvints — APPROVED** [review]

File: src/Illuminate/Validation/Concerns/FormatsMessages.php (hunk 1 above)
Comment (tinyoverflow) [inline src/Illuminate/Validation/Concerns/FormatsMessages.php]: I think a check for `instanceof Symfony\Component\HttpFoundation\File\File` would fit better here, as the ValidatesAttributes trait also uses this exact class to check against. This would also remove the need to check against both classes, as both are simply extending the `Symfony\Component\HttpFoundation\File\File` class.

```suggestion
            $this->getValue($attribute) instanceof File => 'file',
```

File: src/Illuminate/Validation/Concerns/FormatsMessages.php [hunk 2]
```diff
@@ -3,6 +3,7 @@
 namespace Illuminate\Validation\Concerns;
 
 use Closure;
+use Illuminate\Http\File;
```
Comment (tinyoverflow) [inline src/Illuminate/Validation/Concerns/FormatsMessages.php:6]: As suggested below, I'd suggest to use Symfonys file class to check against, as thats the one used inside the ValidatesAttributes class.

```suggestion
use Symfony\Component\HttpFoundation\File\File;
```

File: src/Illuminate/Validation/Concerns/FormatsMessages.php (hunk 1 above)
Comment (driesvints) [reply src/Illuminate/Validation/Concerns/FormatsMessages.php]: Yeah, that would be a good idea I think 👍

Comment (mateusjunges) [reply src/Illuminate/Validation/Concerns/FormatsMessages.php]: Agreed. Updated on https://github.com/laravel/framework/pull/49879/commits/9d741065a81668db13d43b256c7f76ed916f48ea
