### PR TITLE
[10.x] Allow serialization of NotificationSent

### LINKED ISSUE #47372: Unable to queue NotificationSent event listener for notifications with attachments
### Laravel Version

10.13.1

### PHP Version

8.2.4

### Database Driver & Version

MySQL 8 (Laravel Sail)

### Description

Hello!

I believe I found a problem in Laravel 10.13.1 introduced by [a recent change](https://github.com/laravel/framework/pull/47310/files).

The issue is related to notifications with attachments (like PDF files). Due to the change, the `NotificationSent` event listeners can't be queued anymore. An `InvalidPayloadException` exception is thrown.

I included more information in the "Steps To Reproduce" section below.

### Steps To Reproduce

Starting with a fresh installation of Laravel 10.13.1+:

**1. Set up a notification with a file attachment (binary file such as PDF)**

```php
class ExampleNotification extends Notification
{
    public function via(object $notifiable): array
    {
        return ['mail'];
    }

    public function toMail(object $notifiable): MailMessage
    {
        return (new MailMessage)
            ->line('Example notification with attachment.')
            ->attach(resource_path('files/sample.pdf'), [
                'as' => 'sample.pdf',
                'mime' => 'application/pdf',
             ]);
    }
}
```

**2. Set up a `NotificationSent` event listener**

```php
class ExampleListener implements ShouldQueue
{
    public function handle(NotificationSent $event): void
    {
        //
    }
}
```

**3. Listen to `NotificationSent` event**

```php
class EventServiceProvider extends ServiceProvider
{
    protected $listen = [
        NotificationSent::class => [
            ExampleListener::class,
        ],
    ];
}
```

**4. Notify a user**

```php
$user->notify(new \App\Notifications\ExampleNotification());
```

**Result:**

See `Illuminate\Queue\InvalidPayloadException` with `Unable to JSON encode payload. Error code: 5.` message.

### PR DESCRIPTION
**Pull request by cosmastech**
To close https://github.com/laravel/framework/issues/47372

- [x] Serialize SentMessage
- [x] Do not double serialize/encode SentMessage within MessageSent
- [x] Test serializing/unserializing SentMessage
- [x] ~~Test serializing/unserializing MessageSent~~ This is covered adequately by serializing MessageSent, but can add another test if requested.

MessageSent handily serializes and unserializes the raw message data (contained within SentMessage, which relies on Symfony's SentMessage class).

Since Illuminate's SentMessage is common to both MessageSent and NotificationSent, I thought it would make sense to move the base64 encoding/decoding and serialization of Symfony's SentMessage to Laravel's SentMessage class.

BTW, these names are confusing as hell to talk about, let alone work on. 😆

### CODE REVIEW

File: src/Illuminate/Mail/Events/MessageSent.php [hunk 1]
```diff
@@ -46,14 +46,10 @@ public function __serialize()
     {
         $hasAttachments = collect($this->message->getAttachments())->isNotEmpty();
 
-        return $hasAttachments ? [
-            'sent' => base64_encode(serialize($this->sent)),
-            'data' => base64_encode(serialize($this->data)),
-            'hasAttachments' => true,
-        ] : [
+        return [
             'sent' => $this->sent,
```
Comment (taylorotwell) [inline src/Illuminate/Mail/Events/MessageSent.php:50]: This never needs to be base 64 encoded and serialized anymore?

Comment (cosmastech) [reply src/Illuminate/Mail/Events/MessageSent.php:50]: Admittedly, I don't know all of the use cases here, but my thinking is: if `SentMessage` is being base64_encoded for attachments when it is serialized, then there's no need to encode it again when `MessageSent` is being serialized.

Do you see a flaw in that thinking?

Comment (taylorotwell) [reply src/Illuminate/Mail/Events/MessageSent.php:50]: Yeah, that could be true.
