### PR TITLE
[5.1] Fix app namespace determination

### LINKED ISSUE #8997: [5.1] Console generator commands don’t use correct namespace
I’ve created a Laravel 5.1 application to check out the new version. I appreciate it’s still in development, but I’m noticed an issue with the `make:` console commands: they don’t insert the correct (full) namespace into new files.

I set my application namespace to `YourFightSite\OnDemand` using `app:name`. I then used `make:model` to create a model, but instead of using the full namespace, it’s instead just inserting `YourFightSite` (and omitting the `OnDemand` portion).

I haven’t observed this behavior in any of my up-to-date 5.0.x Laravel applications, so can safely say this is a 5.1-specific issue.

Are there any gotchas I should know of when using nested namespaces? Or is this a bug?

### PR DESCRIPTION
**Pull request by arrilot**
Closes #8997

There are some problems with app namespace determination that was introduced in #8084
1. Nested namespaces doesn't work atm, but in L5.0 they work fine.
2. In some rare cases kernel classes can be overwriten since they are bound into the container in laravel/laravel https://github.com/laravel/laravel/blob/develop/bootstrap/app.php

So I guess it's better to return to the code we have in 5.0, sorry.

### CODE REVIEW

File: src/Illuminate/Foundation/Application.php [hunk 1]
```diff
@@ -1054,6 +1055,8 @@ protected function getKernel()
      * Get the application namespace.
      *
      * @return string
+     *
+     @ throws \RuntimeException
```
Comment (GrahamCampbell) [inline src/Illuminate/Foundation/Application.php]: This is formatted wrongly.

File: src/Illuminate/Foundation/Application.php [hunk 2]
```diff
@@ -1061,8 +1064,18 @@ public function getNamespace()
...
+                if (realpath(app_path()) == realpath(base_path().'/'.$pathChoice)) {
+                    $this->namespace = $namespace;
+
+                    return $this->namespace;
+                }
+            }
+        }
 
-        return $this->namespace;
+        throw new RuntimeException("Unable to detect application namespace.");
```
Comment (GrahamCampbell) [inline src/Illuminate/Foundation/Application.php]: Please use single quotes.

File: src/Illuminate/Foundation/Application.php [hunk 3]
```diff
@@ -1061,8 +1064,18 @@ public function getNamespace()
...
 
-        $this->namespace = strtok(get_class($this->getKernel()), '\\').'\\';
+        $composer = json_decode(file_get_contents(base_path().'/composer.json'), true);
+
+        foreach ((array) data_get($composer, 'autoload.psr-4') as $namespace => $path) {
+            foreach ((array) $path as $pathChoice) {
+                if (realpath(app_path()) == realpath(base_path().'/'.$pathChoice)) {
+                    $this->namespace = $namespace;
+
+                    return $this->namespace;
```
Comment (GrahamCampbell) [inline src/Illuminate/Foundation/Application.php]: Please return an asign on the same line.
