### PR TITLE
[5.2] fix #13527 by setting the model on ModelNotFoundException

### LINKED ISSUE #13527: model not defined on ModelNotFoundException
Hi, when I use the `firstOrFail` method on a `hasManyThrough` relation, `ModelNotFoundException` has not defined the model attribute.

I think the error is in `src/Illuminate/Database/Eloquent/Relations/HasManyThrough.php:247` and can be fixed replacing this:
```
    public function firstOrFail($columns = ['*'])
    {
        if (! is_null($model = $this->first($columns))) {
            return $model;
        }

        throw new ModelNotFoundException;
    }
```
with this:
```
    public function firstOrFail($columns = ['*'])
    {
        if (! is_null($model = $this->first($columns))) {
            return $model;
        }

        throw (new ModelNotFoundException)->setModel(get_class($this->related));
    }
```

### PR DESCRIPTION
**Pull request by themsaid**
Setting the model on `ModelNotFoundException` for `firstOrFail` in `BelongsToMany` and `HasManyThrough` relations.

### CODE REVIEW

File: tests/Database/DatabaseEloquentBelongsToManyTest.php [hunk 1]
```diff
@@ -335,6 +335,38 @@ public function testCreateMethodCreatesNewModelAndInsertsAttachmentRecord()
         $this->assertEquals($model, $relation->create(['attributes'], ['joining']));
     }
 
+    public function testFindOrFailThrowsException()
+    {
+        $relation = $this->getMock('Illuminate\Database\Eloquent\Relations\BelongsToMany', ['find'], $this->getRelationArguments());
+        $relation->expects($this->once())->method('find')->with('foo')->will($this->returnValue(null));
+
+        $this->setExpectedException(\Illuminate\Database\Eloquent\ModelNotFoundException::class);
```
Comment (GrahamCampbell) [inline tests/Database/DatabaseEloquentBelongsToManyTest.php]: Please avoid these leading slashes when we're not in a namespace.

Comment (themsaid) [inline tests/Database/DatabaseEloquentBelongsToManyTest.php]: Okay, will do.

Comment (GrahamCampbell) [inline tests/Database/DatabaseEloquentBelongsToManyTest.php]: No worries. Thanks for all the great PRs. ;)

Comment (themsaid) [inline tests/Database/DatabaseEloquentBelongsToManyTest.php]: Glad to help mate :)
