### PR TITLE
[5.8] Resolve columns with schema references

### LINKED ISSUE #29443: 5.8.30 to 5.8.31 update on postgresql causes issue
- Laravel Version: 5.8.31
- PHP Version: 7.3
- Postgresql (homestead or AWS)

### Description:
When updating model with timestamps enabled, an exception is thrown.  
Illuminate \ Database \ QueryException (42703)
SQLSTATE[42703]: Undefined column: 
It looks to be thrown because the "updated_at" column in the sql is prefixed with the table name. 

update "schema"."tablename" set "name" = CCCC, .....
"tablename"."updated_at" = 2019-08-07 04:20:58 where "id" = 1152

### Steps To Reproduce:
in composer.json set  "laravel/framework": "5.8.*" then run composer update

### WORK AROUND
in composer.json set  "laravel/framework": "5.8.30" then run composer update

### PR DESCRIPTION
**Pull request by jayked**
Postgres has schema references which we should keep in mind when we are resolving columns from strings.

Closes #29443

### CODE REVIEW

File: src/Illuminate/Database/Query/Grammars/PostgresGrammar.php [hunk 1]
```diff
@@ -248,7 +248,7 @@ protected function compileUpdateColumns($query, $values)
         // columns and convert it to a parameter value. Then we will concatenate a
         // list of the columns that can be added into this update query clauses.
         return collect($values)->map(function ($value, $key) {
-            $column = Str::after($key, '.');
+            $column = Arr::last(explode('.', $key));
```
Comment (staudenmeir) [inline src/Illuminate/Database/Query/Grammars/PostgresGrammar.php]: There is a global `last()` function that we can use:

```suggestion
            $column = last(explode('.', $key));
```

**Comment by staudenmeir** [comment]
Can you please add a test?

**Review by staudenmeir — APPROVED** [review]

File: src/Illuminate/Database/Query/Grammars/PostgresGrammar.php (hunk 1 above)
Comment (X-Coder264) [reply src/Illuminate/Database/Query/Grammars/PostgresGrammar.php]: why not just use the PHP `end` function directly? :smile:

Comment (staudenmeir) [reply src/Illuminate/Database/Query/Grammars/PostgresGrammar.php]: `end()` only works with variables, not with return values.

Comment (X-Coder264) [reply src/Illuminate/Database/Query/Grammars/PostgresGrammar.php]: `last()` is just an alias for `end()` though, or am I missing something?
