### PR TITLE
[11.x] Prevent unintended serialization and compression

### LINKED ISSUE #54307: Rate limiter no longer works when compression/serialization is enabled since v11.39.0
### Laravel Version

11.39.0

### PHP Version

8.4.3

### Database Driver & Version

_No response_

### Description

When using Redis as a cache driver combined with compression or serialization, the rate limiter no longer works in the latest release: the increment method always returns 0.

This seems to be related to https://github.com/laravel/framework/pull/54221

More specifically, it seems that adding a key and then incrementing that key is the thing that breaks the rate limiter

```
$added = $this->cache->add($key, 0, $decaySeconds);
$hits = (int) $this->cache->increment($key, $amount);
```

doing the above always returns 0.

That's because the incrby function in Redis only works on integers, not on serialized/compressed data.
I can try and submit a PR with a fix, but I'm not sure what the preferred way forward would be.

### Steps To Reproduce

I created a test case here: https://github.com/JeppeKnockaert/laravel-cache-bug-report/commit/e9836547bd514307850a4dbcc5e4976b451e2e13

To execute the tests:

```
cp .env.example .env
./vendor/bin/sail artisan key:generate
./vendor/bin/sail up -d    
./vendor/bin/sail test ./tests/Unit/CacheTest.php  
```

The first test is the only that succeeds, because no compression or serialisation are configured.

### PR DESCRIPTION
**Pull request by JeppeKnockaert**
This pull request fixes an issue when using serialization and compression combined with the increment function, introduced in https://github.com/laravel/framework/pull/54221. 

This is something used by the RateLimiter and causes it to fail since the v11.39.0.

This PR is intended to fix https://github.com/laravel/framework/issues/54307.

### CODE REVIEW

File: src/Illuminate/Cache/RedisStore.php [hunk 1]
```diff
@@ -444,6 +448,17 @@ protected function pack($value, $connection)
...
 
+    /**
+     * Determine if the given value should be stored as plain value or be serialized/compressed instead.
+     *
+     * @param  mixed  $value
+     * @return bool
+     */
+    protected function storePlainValue($value): bool
+    {
+        return is_numeric($value) && ! in_array($value, [INF, -INF]) && ! is_nan($value);
```
Comment (TheLevti) [inline src/Illuminate/Cache/RedisStore.php:459]: Please don't do this. You will break the cache component when serialization/compression is enabled. I will explain in the issue ticket.

Comment (TheLevti) [reply src/Illuminate/Cache/RedisStore.php:459]: Instead, we should ensure that the rate limiter component also is aware of those settings.

**Comment by TheLevti** [comment]
Is it possible to contribute here or should I open a new pull request on my own?

**Comment by taylorotwell** [comment]
@TheLevti what needs to be changed?

**Comment by TheLevti** [comment]
> @TheLevti what needs to be changed?

I just confirmed with the maintainers of phpredis, that this behaviour is by design. A value stored with serialization/encryption, can not be incremented/decremented.

So for us, inside the rate limit component when we set the initial counter value, we need to skip serialization and store the value as is (when serialization/compression is enabled).

Solution is basically similar to what is done here. Instead of globally skipping the pack call for any Cache component usage, we should do this only when used by the RateLimiter component. (for setting the initial counter value)

**Comment by taylorotwell** [comment]
@TheLevti is there a big issue with just doing it globally in the cache component?

**Comment by TheLevti** [comment]
> @TheLevti is there a big issue with just doing it globally in the cache component?

Also checked that. Theoretically possible even though it would be not correct. `phpredis` will return the value as is if the value can not be deserialized/uncompressed.

We can come up with a smarter solution later and use this proposal for now.

**Comment by TheLevti** [comment]
```php
<?php

$r = new Redis;
$r->connect('localhost', 6379);

shell_exec('redis-cli set foo not-valid-serialization');

$r->setOption(Redis::OPT_SERIALIZER, Redis::SERIALIZER_PHP);

var_dump($r->get('foo'));
```

```bash
❯ php /tmp/fallback.php
string(23) "not-valid-serialization"
```

So it will work

File: src/Illuminate/Cache/RedisStore.php (hunk 1 above)
Comment (TheLevti) [reply src/Illuminate/Cache/RedisStore.php:459]: We can merge this one

**Comment by TheLevti** [comment]
I have used the following test to confirm the rate limiter works:

```php
    /**
     * @param  string  $driver
     */
    #[DataProvider('redisDriverProvider')]
    public function testRedisCacheRateLimiter($driver)
    {
        $store = new RedisStore($this->redis[$driver]);
        $repository = new Repository($store);
        $rateLimiter = new RateLimiter($repository);

        $this->assertFalse($rateLimiter->tooManyAttempts('key', 1));
        $this->assertEquals(1, $rateLimiter->hit('key', 60));
        $this->assertTrue($rateLimiter->tooManyAttempts('key', 1));
    }
```

**Comment by vlakoff** [comment]
You could make use of [`is_finite()`](https://www.php.net/manual/en/function.is-finite.php):

Changing this:
```php
return is_numeric($value) && ! in_array($value, [INF, -INF]) && ! is_nan($value);
```

To this:
```php
return is_numeric($value) && is_finite($value);
```

**Comment by TheLevti** [comment]
> You could make use of [`is_finite()`](https://www.php.net/manual/en/function.is-finite.php):
> 
> Changing this:
> 
> ```
> return is_numeric($value) && ! in_array($value, [INF, -INF]) && ! is_nan($value);
> ```
> 
> To this:
> 
> ```
> return is_numeric($value) && is_finite($value);
> ```

Ah nice, did not know about this function. Will try to remember on next iteration of improvements on this part ^^
