### PR TITLE
[11.x] Prevent attributes cast to an enum from being set to another enum

### LINKED ISSUE #47454: Casting a model attribute to an enum does not prevent assigning the attribute to a different enum
### Laravel Version

10.13.5

### PHP Version

8.2.7

### Database Driver & Version

N/A

### Description

Casting a model attribute to an enum _does not_ prevent assigning the attribute to a different enum or a value not defined as a case on the enum.

For example, if an attribute is cast to `SomeEnum` you can freely set/update the value of that attribute to `AnotherEnum::WHATEVER` or any primitive value. In this event, if the backed value of `AnotherEnum::WHATEVER` or the primitive value matches a case on `SomeEnum` when we retrieve the model from the DB we will get an instance of `SomeEnum` back (fine, but unexpected). However, if the backed value of `AnotherEnum::WHATEVER` or the primitive value _does not_ match a case on `SomeEnum` we will get a `ValueError` on retrieval of the model since it can't create the `SomeEnum` from the value stored in the DB (i.e. `SomeEnum::from($value)`).

I believe the intent to allow setting an (uncast) attribute to an enum is at least somewhat intentional. However, **when the attribute is cast to a specific enum and attempting to assigning it to a _different_ enum or a string that is _not_ defined as a case on the enum should result in a error**. This would proactively avoid storing an incorrect value in the DB, prevent the `ValueError` on retrieval and preserve the benefits of using enums in the first place.

If this sounds like a reasonable change I can create a PR for this. Let me know what you think.

**NOTE:** For your reference and mine [here](https://github.com/laravel/framework/blob/ea5172eb59d4ecd87379591c2a2e34c96ca7d068/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L1166-L1191) is the code that sets and gets the value for an attribute cast to an enum.

### Steps To Reproduce

Create some enums.

```php
namespace App\Models\Enums;

enum SomeEnum: string
{
    case FOO = 'foo';
    case BAR = 'bar';
}
``` 

```php
namespace App\Models\Enums;

enum AnotherEnum: string
{
    case BAR = 'bar';
    case BAZ = 'baz';
}
```

Create a Model with an attribute cast to one of the enums.

```php
namespace App\Models;

use App\Models\Enums\SomeEnum;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Example extends Model
{
    use HasFactory;

    protected $casts = [
        'some_enum' => SomeEnum::class,
    ];
}
```

Set the attribute to the incorrect enum value.

```php
> $example = Example::factory()->makeOne(['some_enum' => SomeEnum::FOO])
= App\Models\Example {#6992
    some_enum: "foo",
  }

> $example->some_enum
= App\Models\Enums\SomeEnum {#6239
    +name: "FOO",
    +value: "foo",
  }

> $example->some_enum = AnotherEnum::BAR
= App\Models\Enums\AnotherEnum {#6243
    +name: "BAR",
    +value: "bar",
  }

> $example->some_enum
= App\Models\Enums\SomeEnum {#6238
    +name: "BAR",
    +value: "bar",
  }

> $example->some_enum = AnotherEnum::BAZ
= App\Models\Enums\AnotherEnum {#6211
    +name: "BAZ",
    +value: "baz",
  }

> $example->some_enum

   ValueError  "baz" is not a valid backing value for enum App\Models\Enums\SomeEnum.
```

### PR DESCRIPTION
**Pull request by PHLAK**
Prevent an attribute that is cast to an enum from being set to another enum value or a value not defined as a case on a `BackedEnum`. This will throw a `ValueError` like the following when attempting to do so.

```
Value [\App\SomeEnum::CASE] is not of the expected enum type [\App\AnotherEnum]
``` 

**NOTE:** This is technically a _breaking change_ but I'd consider it more of a bug fix so handle that as you will.

Resolves #47454

### CODE REVIEW

File: src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php [hunk 1]
```diff
@@ -1180,11 +1182,16 @@ protected function getEnumCaseFromValue($enumClass, $value)
     /**
      * Get the storable value from the given enum.
      *
+     * @param  string  $expectedEnum
      * @param  \UnitEnum|\BackedEnum  $value
      * @return string|int
      */
-    protected function getStorableEnumValue($value)
+    protected function getStorableEnumValue($expectedEnum, $value)
```
Comment (driesvints) [inline src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:1189]: This is a breaking change unfortunately. We can't change a method signature in a patch release.

**Review by driesvints — CHANGES_REQUESTED** [review]

File: src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php (hunk 1 above)
Comment (PHLAK) [reply src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:1188]: Can we think of an alternative way of accomplishing this that wont be a breaking change?

**Comment by PHLAK** [comment]
Hmm... I'm not sure why this is getting [errors in CI](https://github.com/laravel/framework/actions/runs/5293068510/jobs/9580720198?pr=47465#step:6:31). It's generating the error and passing locally. [This line](https://github.com/laravel/framework/blob/ea5172eb59d4ecd87379591c2a2e34c96ca7d068/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L1176) should be catching the invalid string and throwing the `ValueError.` Could this be because of a difference in PHP versions (CI: 8.1, Local: 8.2)?

File: src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php (hunk 1 above)
Comment (PHLAK) [reply src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:1188]: The only alternative I can see would be to add the `instanceof` check before calling `getStorableEnumValue()` (i.e. in `addCastAttributesToArray()` and `setEnumCastableAttribute()`).

The downside of this is duplicate code and if `getStorableEnumValue()` were to be added anywhere else in the future we'd need to remember to add the `instanceof` check there as well.

This doesn't seem like a good idea to me.

Comment (driesvints) [reply src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:1188]: If we can't do it differently then yeah master might be the only option

**Comment by PHLAK** [comment]
I've updated the PR to merge to `master`.
