### PR TITLE
[5.4] Flush application resources in application flush

### LINKED ISSUE #21015: [testcase] Memory leak
- Laravel Version: 5.4.32
- PHP Version: 7.0.18
- Database Driver & Version: MySQL:  5.7.11

### Description:

Laravel is not freeing up memory during the test cases.
Our application has ~2000 test cases, with each test case the memory consumption increases by ~2MB. By the end of all the test cases, the total memory consumption is ~4224MB.

This led us to believe that there is a memory leak somewhere because of which the memory consumption is increasing. On going through the code base, we realised that the `flush()` in only resetting certain properties.
We are overriding the `\Illuminate\Foundation\Application::flush()` with following changes
```php
public function flush()
{
    parent::flush();

    $this->bootingCallbacks         = [];
    $this->bootedCallbacks          = [];
    $this->middlewares              = [];
    $this->serviceProviders         = [];
    $this->deferredServices         = [];
    $this->reboundCallbacks         = [];
    $this->resolvingCallbacks       = [];
    $this->afterResolvingCallbacks  = [];
    $this->globalResolvingCallbacks = [];
    $this->buildStack               = [];
}
```

Apparently, `$bootingCallbacks`, `$serviceProviders` and `$bootedCallbacks` properties are not freeing up the memory even when the `$this->app = null` is executing.

I want to discuss why exactly `flush()` is not resetting these properties.
I'll create a PR for this once this solution is approved as I saw that the last change in `flush()` was made 3 years ago.

### Stats

Before this change:
```
Time: 5.24 minutes, Memory: 4150.00MB
```

After this change:
```
Time: 4.71 minutes, Memory: 162.00MB
```

### Steps To Reproduce:
1. Write multiple test cases.
2. Print memory usage in `teardown()`
3. With each test case, memory consumption increases.

### PR DESCRIPTION
**Pull request by ccrims0n**
Fixes #21015 in laravel 5.4

### CODE REVIEW

**Comment by ccrims0n** [comment]
@themsaid Can we merge this for laravel 5.4 and release this as minor update?

File: src/Illuminate/Foundation/Application.php [hunk 1]
```diff
@@ -1143,6 +1143,16 @@ public function flush()
         parent::flush();
 
         $this->loadedProviders = [];
+        $this->bootingCallbacks = [];
+        $this->bootedCallbacks = [];
+        $this->middlewares = [];
```
Comment (crynobone) [inline src/Illuminate/Foundation/Application.php]: I tried checking `Illuminate\Foundation\Application` and can't seem to find `middlewares` property. Where does this come from?

Comment (ccrims0n) [reply src/Illuminate/Foundation/Application.php]: @crynobone You are right, will file a pr to fix that.
