### PR TITLE
[11.x] Fix PHP and Artisan binary

### LINKED ISSUE #52752: Array offset error when using the Concurrency facade
### Laravel Version

11.23.2

### PHP Version

8.3.11

### Database Driver & Version

SQLite

### Description

The `Concurrency` facade returns a "Trying to access array offset on null" error, when attempting to use the `run` method. This error seems to be at `$result['successful']` within the ProcessDriver class.

From some testing I've done myself it still seems that Laravel is unable to find the php binary from Herd, as `(new PhpExecutableFinder)->find(false)` returns `false`.

### Steps To Reproduce

Create a route like the following:

``` php
Route::get('/concurrency', function () {
    [$test] = Concurrency::run([
        fn () => DB::table('users')->get(),
    ]);

    return response()->json([
        'test' => $test,
    ]);
});
```

Laravel will error out at the Concurrency::run line.

### PR DESCRIPTION
**Pull request by hafezdivandari**
This PR fixes usages of PHP and Artisan binary on different places of the framework.

### CODE REVIEW

File: src/Illuminate/Concurrency/ProcessDriver.php [hunk 1]
```diff
@@ -25,13 +25,18 @@ public function __construct(protected ProcessFactory $processFactory)
      */
     public function run(Closure|array $tasks): array
     {
-        $php = (new PhpExecutableFinder)->find(false);
+        $php = Application::phpBinary();
```
Comment (devajmeireles) [inline src/Illuminate/Concurrency/ProcessDriver.php:28]: This fixes issues caused by the binary path via Herd: `/Users/<user>/Library/Application Support/Herd/bin//php`, but I'm wondering if `Application` can be used here since Concurrency doesn't depend on it in `composer.json`?

**Comment by devajmeireles** [comment]
@hafezdivandari Are you going ahead with this? This fixes issues caused by the binary path via Herd: `/Users/<user>/Library/Application Support/Herd/bin//php`. The whitespace in `Application Support` causes an exception. I'm just wondering if `Application` can be used here since Concurrency doesn't depend on it in `composer.json`?

**Comment by hafezdivandari** [comment]
@devajmeireles yeah I'm gonna fix this if I can control my OCD!

**Comment by hafezdivandari** [comment]
> I'm just wondering if Application can be used here since Concurrency doesn't depend on it in composer.json

It's `Console\Application` and I think we already require `illuminate/console`, because `Cocurrency` works by calling [this command](https://github.com/laravel/framework/blob/11.x/src/Illuminate/Concurrency/Console/InvokeSerializedClosureCommand.php) that depends on `illuminate/console`?

**Comment by devajmeireles** [comment]
> > I'm just wondering if Application can be used here since Concurrency doesn't depend on it in composer.json
> 
> It uses `Console\Application` and I think we already require `illuminate/console`, because `Cocurrency` works by calling [this command](https://github.com/laravel/framework/blob/11.x/src/Illuminate/Concurrency/Console/InvokeSerializedClosureCommand.php) that depends on `illuminate/console`?

This is outdated. Previously you had entered `Illuminate\Foundation\Application`, but now it looks correct using `Illuminate\Console\Application`.

**Comment by crynobone** [comment]
https://github.com/symfony/symfony/pull/52409

There are some internal differences between passing a string and an array to Symfony Process where using an array can be twice to 4x faster.

CleanShot 2024-09-12 at 16 34 32
