### PR TITLE
[6.x] Replace asterisks before validation

### LINKED ISSUE #31228: Asterisk keys in validator input bypass array validation rules
- Laravel Version: 6.11.0
- PHP Version: 7.4.0
- Database Driver & Version: N/A

### Description:

When validating an array that has an asterisk (\*) as any of the keys: the value corresponding to that key will _bypass_ any array/wildcard rules in the validator (i.e. rules whose key includes an asterisk such as `data.*.date`).

### Steps To Reproduce:

Run the following code:
```
$input = [
    'data' => [
        0 => ['date' => '2019-01-24'],
        1 => ['date' => 'blah'],
        '*' => ['date' => 'blah']
    ]
];

$validator = \Illuminate\Support\Facades\Validator::make($input, [
    'data.*.date' => 'required|date'
]);

if($validator->fails()) {
    dd($validator->errors());
}
```
Note the lack of validation errors in the output regarding the asterisk entry in the data array:

```
Illuminate\Support\MessageBag {
  #messages: array:1 [
    "data.1.date" => array:1 [
      0 => "The data.1.date is not a valid date."
    ]
  ]
  #format: ":message"
}
```

### Further Details

I examined the code to find out what was happening and the issue occurs in `ValidationRuleParser::explodeRules`.  Each entry in an array to be validated has to have rules generated by the rule parser specifically for that entry.  An asterisk entry in the incoming data has rules generated for it that are _identical_ to the original rules set on the validator, and these rules are automatically unset and lost leading to zero validation on these entries.

Unfortunately we cannot simply detect this special case and stop the unset.  This is because there is a deeper issue (for this _specific_ case) in the way rules are generated, which involves an array merge leading to rule duplication (`ValidationRuleParser::mergeRulesForAttribute`).

I have not made a pull request as, due to the recursion occurring in this code, I am not confident enough to make a fix here.  In particular: I can't guarantee that any fix I thought up wouldn't break more complex rules e.g. `data.*.user.*.name`.

### PR DESCRIPTION
**Pull request by themsaid**
A different approach for https://github.com/laravel/framework/pull/31253 that fixes https://github.com/laravel/framework/issues/31228

### CODE REVIEW

File: src/Illuminate/Validation/Validator.php [hunk 1]
```diff
@@ -255,6 +255,8 @@ public function parseData(array $data)
             // array based validation rules plus Arr::dot later in the validations.
             if (Str::contains($key, '.')) {
                 $newData[str_replace('.', '->', $key)] = $value;
+            } elseif (Str::contains($key, '*')) {
```
Comment (GrahamCampbell) [inline src/Illuminate/Validation/Validator.php]: Why do we need this? Faster to always do the replace?

**Review by GrahamCampbell — CHANGES_REQUESTED** [review]

File: src/Illuminate/Validation/Validator.php (hunk 1 above)
Comment (themsaid) [reply src/Illuminate/Validation/Validator.php]: Yeah I just don't like to refactor in a PR that proposes a change. It's easier to review such PRs since it only contains the changes needed. Might send another PR to update the replacements and remove the checks.

Comment (GrahamCampbell) [reply src/Illuminate/Validation/Validator.php]: I don't understand what you mean? I'm suggesting you change your PR to contain even fewer changes...

Comment (GrahamCampbell) [reply src/Illuminate/Validation/Validator.php]:
```php
if (Str::contains($key, '.')) {
    $newData[str_replace('.', '->', $key)] = $value;
} else {
    $newData[str_replace('*', '__asterisk__', $key)] = $value;
}
```

**Review by GrahamCampbell — CHANGES_REQUESTED** [review]

File: src/Illuminate/Validation/Validator.php (hunk 1 above)
Comment (themsaid) [reply src/Illuminate/Validation/Validator.php]: the check for the dot has to go as well

Comment (GrahamCampbell) [reply src/Illuminate/Validation/Validator.php]: But removing that actually changes the behaviour?

Comment (GrahamCampbell) [reply src/Illuminate/Validation/Validator.php]: My version and your version behave exactly the same. If you remove the if check on the dot, then the behaviour changes.

Comment (36864) [reply src/Illuminate/Validation/Validator.php]: Why don't we want to replace asterisks if there's also a period in the same key?

Comment (GrahamCampbell) [reply src/Illuminate/Validation/Validator.php]: I'm not sure. If we do want that, then this PR has a bug that the tests don't show.

File: src/Illuminate/Validation/Validator.php [hunk 2]
```diff
@@ -250,14 +250,9 @@ public function parseData(array $data)
                 $value = $this->parseData($value);
             }
 
-            // If the data key contains a dot, we will replace it with another character
```
Comment (GrahamCampbell) [inline src/Illuminate/Validation/Validator.php]: We should keep this comment?

**Review by GrahamCampbell — CHANGES_REQUESTED** [review]
