### PR TITLE
[12.x] `ScheduledTaskFailed` not dispatched on scheduled forground task fails

### LINKED ISSUE #55614: Scheduled Task Failure Events Not Consistently Dispatched (Including runInBackground Cases)
### Laravel Version

12.x

### PHP Version

8.4

### Database Driver & Version

_No response_

### Description

Two related issues exist with scheduled task failure events:

1.  **Original Issue:**The ScheduledTaskFailed event doesn't dispatch consistently across all failure modes (exceptions, non-zero exit codes, background/system failures). While #55572 addressed part of this, there's still inconsistent behavior. thus it was reverted.
    
2.  **New runInBackground Issue:**When using ->runInBackground(), commands don't properly return status codes, causing exceptions in the scheduler. This prevents proper failure event dispatching for background tasks.
    

### Steps to Reproduce

**For Issue #1:**
```

// routes/console.php
Artisan::command('failing-command', function () {
    throw new Exception('Should trigger failure event');
})->everyMinute();

// AppServiceProvider.php
Event::listen(ScheduledTaskFailed::class, function () {
    Log::error('Failure event not received');
});

```

**For Issue #2:**

```
// routes/console.php
Schedule::command('app:command-exit')
    ->everyTenSeconds()
    ->runInBackground(); // Causes exceptions

```

### Expected Behavior

1.  All task failures (including background jobs) should dispatch ScheduledTaskFailed
    
2.  Background tasks should properly report their status without throwing scheduler exceptions
    

### Actual Behavior

1.  Some failure modes still don't trigger the event
    
2.  Background tasks cause scheduler exceptions instead of clean failure reporting
    

### Root Cause

1.  Incomplete failure state handling in the scheduler's execution flow
    
2.  Background process status checking isn't properly integrated with the event system
    

### Suggested Solution

Need to:

1.  Expand the scheduler's failure detection to cover all edge cases
    
2.  Properly handle background process status returns
    
3.  Ensure consistent event dispatching regardless of execution method

### Steps To Reproduce

```

// routes/console.php
Artisan::command('failing-command', function () {
    throw new Exception('Should trigger failure event');
})->everyMinute();

// AppServiceProvider.php
Event::listen(ScheduledTaskFailed::class, function () {
    Log::error('Failure event not received');
});

```

and for the second issue

```
// routes/console.php
Schedule::command('app:command-exit')
    ->everyTenSeconds()
    ->runInBackground(); // Causes exceptions

```

### PR DESCRIPTION
**Pull request by achrafAa**
Fix: Consistent Failure Event Dispatching for Foreground and Background Scheduled Tasks

### Description

This PR resolves inconsistencies in Laravel's scheduler related to how task failures are handled and how the ScheduledTaskFailed event is dispatched.

### Problem

Two main issues were affecting scheduled task failure behavior:

1.  **Foreground task failures** (e.g., exceptions or non-zero exit codes) did not always result in `ScheduledTaskFailed` being dispatched properly.
    
2.  **Background tasks** using runInBackground() could cause unexpected exceptions when exit codes were not returned or were null, disrupting the scheduler.
    

This led to unreliable error monitoring and regressions after PR #55572, which had to be reverted due to these side effects.

### Solution

This PR ensures:

*   **Foreground task failures** now reliably dispatch the ScheduledTaskFailed event when a task throws an exception or exits with a non-zero status code.
    
*   **Background tasks** (runInBackground()) are excluded from failure exceptions when exit codes are not explicitly returned, preventing unintended scheduler crashes.
    
*   The scheduler behaves consistently across both execution modes while preserving Laravel's event-driven error handling model.
 
- before this fix : 

|  Scenario | `ScheduledTaskFinished`  | `ScheduledTaskFailed`  |  
| ------------- | ------------- | ------------- |
| Command runs and throws an exception within itself | ✅ Dispatched | ❌ Not dispatched  |
| Command runs and returns non-zero $exitCode | ✅ Dispatched | ❌ Not dispatched  |
|`$event->run($this->laravel); `itself throws | ❌ Not dispatched | ✅ Dispatched  |

- after the fix : 

|  Scenario | `ScheduledTaskFinished`  | `ScheduledTaskFailed`  |  
| ------------- | ------------- | ------------- |
| Command runs and throws an exception within itself | ✅ Dispatched | ✅ Dispatched  |
| Command runs and returns non-zero $exitCode | ✅ Dispatched | ✅ Dispatched  |
|`$event->run($this->laravel); `itself throws | ❌ Not dispatched | ✅ Dispatched  |

So to be clear, ScheduledTaskFinished should always be dispatched unless the exception happens before or outside the actual command execution (e.g. command not found, or failure to start).

### Impact

*   Ensures accurate and consistent dispatching of the ScheduledTaskFailed event.
    
*   Prevents exceptions from being thrown for background tasks with null or missing exit codes.
    
*   Maintains backward compatibility and avoids introducing regressions.
    

### Related Issues

*   Fixes #55614
    
*   Builds on discussion from reverted PR #55572

### CODE REVIEW

**Comment by achrafAa** [comment]
if there is any other case you want me to test or handle, feel free to drop a comment. thanks

**Comment by achrafAa** [comment]
@erickcomp 
@tarkis

**Comment by erickcomp** [comment]
Now that it's restricted to foreground tasks, I think that no side effects will be encountered.

Thanks for your work, @achrafAa!

**Comment by achrafAa** [comment]
most welcome, always happy to help

File: src/Illuminate/Console/Scheduling/ScheduleRunCommand.php [hunk 1]
```diff
@@ -196,6 +197,10 @@ protected function runEvent($event)
                     round(microtime(true) - $start, 2)
                 ));
 
+                if ($event->exitCode != 0 && ! $event->runInBackground) {
```
Comment (rodrigopedra) [inline src/Illuminate/Console/Scheduling/ScheduleRunCommand.php:200]: Why is this `if` clause after dispatching the `ScheduledTaskFinished` event?

Wouldn't this be an inconsistency?

|  If a task...                |  `ScheduledTaskFinished` |  `ScheduledTaskFailed`  |
|:-----------------------------|:------------------------:|:-----------------------:|
| ... throws an exception      |  **NOT dispatched**      |  dispatched             |
| ... returns `$exitCode != 0` |  dispatched              |  dispatched             |

Comment (rodrigopedra) [reply src/Illuminate/Console/Scheduling/ScheduleRunCommand.php:200]: If the idea is to preserve previous behavior, then the `if` clause should be moved after the 

```php
$this->eventsRan = true;
```

statement, right?

Comment (achrafAa) [reply src/Illuminate/Console/Scheduling/ScheduleRunCommand.php:198]: @rodrigopedra Thanks for pointing this out — here's a breakdown to clarify the behavior:

- before this fix : 

|  Scenario | `ScheduledTaskFinished`  | `ScheduledTaskFailed`  |  
| ------------- | ------------- | ------------- |
| Command runs and throws an exception within itself | ✅ Dispatched | ❌ Not dispatched  |
| Command runs and returns non-zero $exitCode | ✅ Dispatched | ❌ Not dispatched  |
|`$event->run($this->laravel); `itself throws | ❌ Not dispatched | ✅ Dispatched  |

- after the fix : 

|  Scenario | `ScheduledTaskFinished`  | `ScheduledTaskFailed`  |  
| ------------- | ------------- | ------------- |
| Command runs and throws an exception within itself | ✅ Dispatched | ✅ Dispatched  |
| Command runs and returns non-zero $exitCode | ✅ Dispatched | ✅ Dispatched  |
|`$event->run($this->laravel); `itself throws | ❌ Not dispatched | ✅ Dispatched  |

So to be clear, ScheduledTaskFinished should always be dispatched unless the exception happens before or outside the actual command execution (e.g. command not found, or failure to start).

Regarding the placement of the if after setting `eventsRan= true` , I agree — it could be made cleaner or restructured to avoid confusion. and it was addressed.

**Comment by taylorotwell** [comment]
How does this actually work if you have a background task that runs for 10 seconds?

**Comment by achrafAa** [comment]
@taylorotwell This doesn't affect background tasks—only foreground tasks.

**Comment by taylorotwell** [comment]
I question if the Finished event should fire if the task failed.

**Comment by achrafAa** [comment]
I agree if a task failed it should not dispatch finished but i did not want to add any breaking changes, 
 
- before this fix : 

|  Scenario | `ScheduledTaskFinished`  | `ScheduledTaskFailed`  |  
| ------------- | ------------- | ------------- |
| Command runs and throws an exception within itself | ✅ Dispatched | ❌ Not dispatched  |
| Command runs and returns non-zero $exitCode | ✅ Dispatched | ❌ Not dispatched  |
|`$event->run($this->laravel); `itself throws | ❌ Not dispatched | ✅ Dispatched  |

- after the fix : 

|  Scenario | `ScheduledTaskFinished`  | `ScheduledTaskFailed`  |  
| ------------- | ------------- | ------------- |
| Command runs and throws an exception within itself | ✅ Dispatched | ✅ Dispatched  |
| Command runs and returns non-zero $exitCode | ✅ Dispatched | ✅ Dispatched  |
|`$event->run($this->laravel); `itself throws | ❌ Not dispatched | ✅ Dispatched  |

**Comment by achrafAa** [comment]
maybe task succeeded != task finished

**Comment by achrafAa** [comment]
I prefer to think of it like this:

```

try {
    dispatch(new ScheduledTaskStarting($task));

    // Execute the task logic here...

    dispatch(new ScheduledTaskSucceeded($task));
} catch (\Throwable $exception) {
    dispatch(new ScheduledTaskFailed($task, $exception));
} finally {
    dispatch(new ScheduledTaskFinished($task));
}

```
This way, ScheduledTaskFinished is always dispatched for cleanup or post-run hooks, regardless of success or failure. The ScheduledTaskSucceeded and ScheduledTaskFailed events give us a clear status to react accordingly.

**Comment by achrafAa** [comment]
## 1️⃣ First Proposition

> ✅ **Always dispatch `ScheduledTaskFinished`**  
> ✅ **Dispatch `ScheduledTaskSucceeded` or `ScheduledTaskFailed` depending on outcome**

```php
try {
    $event->run($this->laravel);
    $this->eventsRan = true;

    if (! $event->runInBackground) {
        if ($event->exitCode != 0) {
            throw new Exception("Scheduled command [{$event->command}] failed with exit code [{$event->exitCode}].");
        }

        $this->dispatcher->dispatch(new ScheduledTaskSucceeded(
            $event,
            round(microtime(true) - $start, 2)
        ));
    }

} catch (Throwable $e) {
    $this->dispatcher->dispatch(new ScheduledTaskFailed($event, $e));
    $this->handler->report($e);
} finally {
    $this->dispatcher->dispatch(new ScheduledTaskFinished(
        $event,
        round(microtime(true) - $start, 2)
    ));
}
```

### ✅ Pros:
- Always logs that the task has **finished**, regardless of success or failure.
- Separates clearly between **succeeded** and **failed** states.

### ❌ Cons:
- May log `ScheduledTaskFinished` even after a `ScheduledTaskFailed`, potentially duplicating effort.

---

## 2️⃣ Second Proposition

> ✅ **Dispatch `Succeeded` and `Finished` only if no exception is thrown**  
> ❌ **No `Finished` if the task fails**

```php
try {
    $event->run($this->laravel);
    $this->eventsRan = true;

    if (! $event->runInBackground) {
        if ($event->exitCode != 0) {
            throw new Exception("Scheduled command [{$event->command}] failed with exit code [{$event->exitCode}].");
        }

        $this->dispatcher->dispatch(new ScheduledTaskSucceeded(
            $event,
            round(microtime(true) - $start, 2)
        ));
    }

    $this->dispatcher->dispatch(new ScheduledTaskFinished(
        $event,
        round(microtime(true) - $start, 2)
    ));
} catch (Throwable $e) {
    $this->dispatcher->dispatch(new ScheduledTaskFailed($event, $e));
    $this->handler->report($e);
}
```

### ✅ Pros:
- Avoids unnecessary `Finished` dispatch after failure.

### ❌ Cons:
- Makes it **hard to track task completion** if it failed (no `Finished` event).
- Ambiguity in logs or observers about whether a task ever completed.

---

## 3️⃣ Third Proposition

> ❌ **No `Succeeded` dispatch at all**  
> ✅ **Dispatch `Finished` only if no exception is thrown**

```php
try {
    $event->run($this->laravel);
    $this->eventsRan = true;

    if (! $event->runInBackground) {
        if ($event->exitCode != 0) {
            throw new Exception("Scheduled command [{$event->command}] failed with exit code [{$event->exitCode}].");
        }
    }

    $this->dispatcher->dispatch(new ScheduledTaskFinished(
        $event,
        round(microtime(true) - $start, 2)
    ));
} catch (Throwable $e) {
    $this->dispatcher->dispatch(new ScheduledTaskFailed($event, $e));
    $this->handler->report($e);
}
```

### ✅ Pros:
- Very minimalist.

### ❌ Cons:
- No visibility into whether task **succeeded**—only that it didn’t fail.
- Could be confusing for observers or logs.
- Eliminates granularity between `succeeded` and `finished`.

---

## ✅ Recommendation

**First Proposition** is the **most complete and traceable** approach.

It ensures:
- Every task emits a final `Finished` state.
- It’s clear if a task **succeeded** or **failed**.
- Observability and logging are optimal for debugging and monitoring.

**Comment by AhmedAlaa4611** [comment]
I really appreciate PRs that focus on fixing existing issues, great work!

**Comment by LauJosefsen** [comment]
Is it really intended behavior that runInBackground does not trigger the ScheduledTaskFailed? Likewise is it intended the ScheduledTaskFinished event is triggered immediately, even though the command is still running in the background?

Would it make sense to wrap runInBackground-commands in a small handler such that the events are dispatched in the background thread that is spawned when using runInBackground?

**Comment by achrafAa** [comment]
@LauJosefsen Thanks for the follow-up!

I actually explored a few different options (check comments above) in the PR — including more aggressive tracking of success/failure states — and ended up going with what I outlined in **Proposition 1**:

> Always dispatch ScheduledTaskFinished, and conditionally dispatch ScheduledTaskSucceeded or ScheduledTaskFailed depending on the outcome.

### Why not track success/failure for background tasks?

With runInBackground(), the main limitation is that **Laravel doesn't wait for the process to complete** — so there's no exit code or exception to act on in real time.

That’s why I chose **not** to dispatch ScheduledTaskFailed or ScheduledTaskSucceeded in those cases:

> We simply don’t have enough information at that point to make that call reliably.

### On wrapping background tasks with a handler

I agree it’s an interesting idea to **wrap background tasks in a handler** that could dispatch events later. However:

*   It would require **bootstrapping Laravel again** in the background process just to send those events.
    
*   That adds **overhead and complexity** that I didn’t want to introduce in this PR.
    

The main goal was to **resolve inconsistencies in foreground behavior** without creating new risks.

### Future improvements

That said, I do think there’s room for improvement in how **background task lifecycle** is tracked — maybe via:

*   Optional hooks
    
*   Opt-in observability for long-running or critical tasks
    

Appreciate the suggestion — definitely something I’d be open to exploring further in a follow-up.

**Comment by LauJosefsen** [comment]
@achrafAa 

Ah, those are valid concerns. I did not really consider scheduled events could be non-artisan commands in my wrapping-based solution. Either way I find it is a bit confusing and should, if not fixable, be at least marked in the documentation that runInBackground events lack some of the observability that sync tasks have? An opt-in solution might be the only real solution, as it gives more flexibility to breaking changes to the way the events are fired and tasks run.

We are trying to make an observability solution that detects if scheduled commands are not running as they should, and it has proven difficult to observe runInBackground tasks due to this. (Might be open sourced in the future, basically prometheus metrics for scheduled commands using spatie/laravel-prometheus)

I will probably use the `Illuminate\Console\Events\CommandFinished` for now, as we internally almost never schedule non-artisan commands, and it can be used as a fallback for runInBackground tasks for commands.
